import test from 'node:test';
import assert from 'node:assert/strict';
import {CITIZEN_PHASES,type PopulationHistogram} from '../src/population-morphism';
import {REALM_LOGICAL_POPULATION,ensureRealmPopulation} from '../src/realm-population';
import {GATEWATCH_SHARD,REALM_HOUSEHOLDS} from '../src/realm-society';
import {SOCIAL_BOUNDARY_STATE_COUNT,SocialSeparatorTree,applySocialCertificate,sequentialWardBoundary,socialDeltaKey,socialSignalFromIndex,socialSignalKey,summarizeSocialCertificates,wardBoundaryCertificate,type SocialSignal} from '../src/social-separator';
import {ACTIVE_RUMOR_CAP,BidirectionalSocialRouter,HISTORY_EVENT_KINDS,advanceRealmHistoryToDay,buildHistoricalSocialRouter,causalParents,effectiveHouseholdShard,ensureRealmHistory,historicalWardCertificates,historicalWardPopulationHistograms,historyAccounting,liftProvenance,migrationAffectedWards,promoteCanonicalEvent,repairHistoricalSocialTree,routeRumor,validateHistoryDag} from '../src/provenance-frontier';
import {makePlayer,seedState} from '../src/state';

function signature(code:number):SocialSignal{return {kin:(code&3) as 0|1|2|3,market:((code>>2)&3) as 0|1|2|3,watch:((code>>4)&3) as 0|1|2|3,guild:((code>>6)&3) as 0|1|2|3};}
function world(seed=411){const w=seedState();w.worldSeed=seed;w.players['player-1']=makePlayer('Historian');ensureRealmPopulation(w);return w;}
function sum(histograms:PopulationHistogram[]){const out=Object.fromEntries(CITIZEN_PHASES.map(p=>[p,0])) as PopulationHistogram;for(const h of histograms)for(const p of CITIZEN_PHASES)out[p]+=h[p];return CITIZEN_PHASES.reduce((n,p)=>n+out[p],0);}

test('ordered social range queries are exact and logarithmic in both directions',()=>{const signatures=Array.from({length:256},(_,i)=>signature((Math.imul(i,109)+37)&255)),certs=signatures.map(wardBoundaryCertificate),router=new BidirectionalSocialRouter(certs);let x=0x59590210;for(let trial=0;trial<512;trial++){x=(Math.imul(x,1664525)+1013904223)>>>0;const a=x&255;x=(Math.imul(x,1664525)+1013904223)>>>0;const b=x&255,input=socialSignalFromIndex((x>>>8)&255),route=router.route(a,b),ordered=a<=b?signatures.slice(a,b+1):signatures.slice(b,a+1).reverse(),direct=sequentialWardBoundary(ordered,input),cut=applySocialCertificate(route,input);assert.equal(socialSignalKey(cut.signal),socialSignalKey(direct.signal));assert.equal(socialDeltaKey(cut.delta),socialDeltaKey(direct.delta));assert.equal(route.segmentCount,Math.abs(a-b)+1);assert.ok(router.lastRangeNodes<=18);}});

test('product lift preserves arbitrary source identity across all 256 social boundary states',()=>{const signatures=Array.from({length:31},(_,i)=>signature((i*53+11)&255)),certificate=summarizeSocialCertificates(signatures.map(wardBoundaryCertificate));for(let i=0;i<SOCIAL_BOUNDARY_STATE_COUNT;i++){const input=socialSignalFromIndex(i),expected=sequentialWardBoundary(signatures,input);for(const provenance of [`atom:${i}:A`,`atom:${i}:B`,JSON.stringify({source:i,house:i*97})]){const lifted=liftProvenance(certificate,{provenance,signal:input});assert.equal(lifted.provenance,provenance);assert.equal(socialSignalKey(lifted.signal),socialSignalKey(expected.signal));assert.equal(socialDeltaKey(lifted.delta),socialDeltaKey(expected.delta));assert.equal(lifted.segmentCount,31);}}});

test('bursty external gameplay keeps live causal frontier hard bounded while preserving canon',()=>{const w=world(1295);w.tick=3600*20;for(let i=0;i<200;i++)promoteCanonicalEvent(w,{source:i%2?'npc':'player',actorId:`actor-${i}`,actorName:`Actor ${i}`,ward:i%256,channel:i%3?'kin':'watch',externalKey:`burst-${i}`,summary:`Canonical burst event ${i}`});const h=ensureRealmHistory(w),a=historyAccounting(h);assert.equal(a.activeRumors,ACTIVE_RUMOR_CAP);assert.ok(a.atoms>=200);assert.equal(Object.keys(h.externalKeys).length,200);assert.ok(validateHistoryDag(h));});

test('external canon keys are idempotent and retain exact actor provenance',()=>{const w=world(595);w.tick=7200;const input={source:'player' as const,actorId:'player-1',actorName:'Historian',ward:72,channel:'watch' as const,externalKey:'player-saved-house-1',subjects:['house:777'],summary:'Historian saved House Ashcroft from a raid.'},a=promoteCanonicalEvent(w,input),b=promoteCanonicalEvent(w,input);assert.equal(a.id,b.id);assert.equal(a.actorId,'player-1');assert.equal(a.source,'player');assert.equal(a.channel,'watch');assert.equal(ensureRealmHistory(w).activeRumors.at(-1)?.sourceAtomId,a.id);});

test('five-thousand-day social history exercises every structural event and remains a valid causal graph',()=>{const w=world(595),h=advanceRealmHistoryToDay(w,5000),kinds=new Set(Object.values(h.atoms).map(a=>a.kind));for(const kind of HISTORY_EVENT_KINDS.filter(k=>k!=='deed'))assert.ok(kinds.has(kind),`missing ${kind}`);assert.ok(Object.keys(h.bornPeople).length>0);assert.ok(Object.values(h.households).some(p=>p.marriageTo!==undefined));assert.ok(Object.values(h.households).some(p=>p.migratedShard!==undefined));assert.ok(Object.values(h.households).some(p=>p.grudges.length>0));assert.ok(Object.keys(h.leaders).length>0);assert.ok(Object.values(h.atoms).some(a=>a.kind==='succession'&&causalParents(h,a.id).length>0));assert.ok(validateHistoryDag(h));});

test('migration and matured descendants preserve immutable million-person base accounting',()=>{const w=world(1679615),population=ensureRealmPopulation(w),h=advanceRealmHistoryToDay(w,5000),histograms=historicalWardPopulationHistograms(w),mature=Object.values(h.bornPeople).filter(p=>p.adultAtDay<=h.lastProcessedDay).length;assert.equal(sum(histograms),REALM_LOGICAL_POPULATION+mature);assert.equal(population.population,REALM_LOGICAL_POPULATION);for(const patch of Object.values(h.households).slice(0,100)){const shard=effectiveHouseholdShard(h,patch.householdOrdinal);assert.ok(shard>=0&&shard<256);}});

test('sparse migration repair equals a full separator rebuild',()=>{const w=world(902),h=advanceRealmHistoryToDay(w,1500),migration=Object.values(h.households).find(p=>p.migratedShard!==undefined);assert.ok(migration);const tree=new SocialSeparatorTree(historicalWardCertificates(w)),old=migration!.migratedShard!,next=(old+37)%256,origin=Math.floor(migration!.householdOrdinal/(REALM_HOUSEHOLDS/256));migration!.migratedShard=next;const wards=migrationAffectedWards(migration!.householdOrdinal,old,next),work=repairHistoricalSocialTree(tree,w,wards),rebuilt=new SocialSeparatorTree(historicalWardCertificates(w));assert.deepEqual(tree.root,rebuilt.root);assert.ok(wards.includes(origin)&&wards.includes(old)&&wards.includes(next));assert.ok(work<=wards.length*Math.log2(256));});

test('live rumor arrives at Gatewatch with exact source atom and logarithmic route',()=>{const w=world(411);w.tick=3600*9;const atom=promoteCanonicalEvent(w,{source:'npc',actorId:'npc:mara',actorName:'Mara Pennymarch',ward:4,channel:'market',externalKey:'mara-market-proof',summary:'Mara warned that iron prices moved east.'}),h=ensureRealmHistory(w),rumor=h.activeRumors.find(r=>r.sourceAtomId===atom.id)!;assert.ok(rumor);const router=buildHistoricalSocialRouter(w),routed=routeRumor(w,rumor,GATEWATCH_SHARD,router),certs=historicalWardCertificates(w),ordered=rumor.sourceWard<=GATEWATCH_SHARD?certs.slice(rumor.sourceWard,GATEWATCH_SHARD+1):certs.slice(GATEWATCH_SHARD,rumor.sourceWard+1).reverse(),direct=applySocialCertificate(summarizeSocialCertificates(ordered),rumor.signal);assert.equal(routed.transition.provenance,atom.id);assert.equal(routed.sourceName,'Mara Pennymarch');assert.equal(socialSignalKey(routed.transition.signal),socialSignalKey(direct.signal));assert.equal(socialDeltaKey(routed.transition.delta),socialDeltaKey(direct.delta));assert.ok(routed.rangeNodes<=18);});
