import test from 'node:test';
import assert from 'node:assert/strict';
import {makePlayer,seedState} from '../src/state';
import {promoteCanonicalEvent,BidirectionalSocialRouter,historicalWardCertificates} from '../src/provenance-frontier';
import {SOCIAL_CHANNELS,socialSignalIndex,zeroSocialSignal} from '../src/social-separator';
import {applyRealmConsequences,CONSEQUENCE_RECENT_CAP,DISTRICT_TRUST_CAP,FACTION_ECHO_CAP,householdTrustForActor,wardPressureAt,consequenceAccounting} from '../src/realm-consequences';
import {ensureRenown} from '../src/renown';
import {causalFactionEcho,standingForPlayer} from '../src/npc-outsider-standing';

test('consequence compiler is idempotent, bounded and does not duplicate canonical history',()=>{const world=seedState(),p=makePlayer('Builder');p.name='Builder';world.players[p.id]=p;for(let i=0;i<240;i++)promoteCanonicalEvent(world,{source:'player',actorId:p.id,actorName:p.name,ward:96+i%32,channel:SOCIAL_CHANNELS[i%4],externalKey:`burst:${i}`,summary:`${p.name} saved road crew ${i} and built a useful crossing.`});const atoms=Object.keys(world.realmHistory!.atoms).length,first=applyRealmConsequences(world),snapshot=JSON.stringify(first),second=applyRealmConsequences(world);assert.equal(JSON.stringify(second),snapshot);assert.equal(Object.keys(world.realmHistory!.atoms).length,atoms);assert.equal(first.actorEcho[p.id].deeds,240);assert.ok(first.recent.length<=CONSEQUENCE_RECENT_CAP);assert.ok(Object.keys(first.actorEcho[p.id].districtTrust).length<=16);for(const value of Object.values(first.actorEcho[p.id].districtTrust))assert.ok(Math.abs(value)<=DISTRICT_TRUST_CAP);for(const value of Object.values(first.actorEcho[p.id].factionEcho))assert.ok(Math.abs(value)<=FACTION_ECHO_CAP);for(const pressure of Object.values(first.wardPressure))for(const channel of SOCIAL_CHANNELS)assert.ok(pressure[channel]>=0&&pressure[channel]<=12);});

test('a directly touched household keeps a sparse exact memory edge to the actor',()=>{const world=seedState(),p=makePlayer('Ranger');p.name='Ranger';world.players[p.id]=p;const house=112*1024+77;promoteCanonicalEvent(world,{source:'player',actorId:p.id,actorName:p.name,ward:112,channel:'kin',subjects:[`house:${house}`],externalKey:'saved-house',summary:`${p.name} saved House Greywick from raiders and defended their road.`});applyRealmConsequences(world);assert.ok(householdTrustForActor(world,house,p.id)>0);assert.equal(Object.keys(world.realmConsequences!.householdMemory).length,1);assert.equal(world.realmConsequences!.householdMemory[String(house)].actors[p.id].mentions,1);});

test('remote deeds can become NPC standing only when the separator carries an echo home',()=>{const world=seedState(),p=makePlayer('Roadwarden');p.name='Roadwarden';world.players[p.id]=p;const before={...ensureRenown(p).reputation},router=new BidirectionalSocialRouter(historicalWardCertificates(world));let chosen:{ward:number;channel:typeof SOCIAL_CHANNELS[number]}|undefined;for(let ward=96;ward<128&&!chosen;ward++){for(const channel of SOCIAL_CHANNELS){const signal=zeroSocialSignal();signal[channel]=3;const step=router.route(ward,8).table[socialSignalIndex(signal)];if(Math.max(step.signal.kin,step.signal.market,step.signal.watch,step.signal.guild)>0){chosen={ward,channel};break;}}}assert.ok(chosen,'Crownroad must have at least one nonzero social route to the home district');promoteCanonicalEvent(world,{source:'player',actorId:p.id,actorName:p.name,ward:chosen!.ward,channel:chosen!.channel,externalKey:'remote-deed',summary:`${p.name} saved a Crownroad patrol and defended the road.`});applyRealmConsequences(world);assert.deepEqual(ensureRenown(p).reputation,before,'causal echo must not double-pay ordinary renown');const faction=chosen!.channel==='market'?'mara':chosen!.channel==='watch'?'gate-guard':'sigrid';assert.ok(causalFactionEcho(p,faction)>0);const withEcho=standingForPlayer(p,faction,0);delete p.causalStanding;const withoutEcho=standingForPlayer(p,faction,0);const rank=['outsider','known','trusted','negotiator','ally'];assert.ok(rank.indexOf(withEcho)>=rank.indexOf(withoutEcho));});

test('ward pressure decays with quiet days instead of accumulating forever',()=>{const world=seedState(),p=makePlayer('Scout');p.name='Scout';world.players[p.id]=p;promoteCanonicalEvent(world,{source:'player',actorId:p.id,actorName:p.name,ward:112,channel:'watch',externalKey:'watch-pressure',summary:`${p.name} defended Northwatch from raiders.`});applyRealmConsequences(world);const now=wardPressureAt(world,112,0).watch,later=wardPressureAt(world,112,40).watch;assert.ok(now>0);assert.ok(later<now);});

test('consequence accounting remains summary-sized relative to canon archive',()=>{const world=seedState(),p=makePlayer('Cartographer');p.name='Cartographer';world.players[p.id]=p;for(let i=0;i<1000;i++)promoteCanonicalEvent(world,{source:'player',actorId:p.id,actorName:p.name,ward:96+i%32,channel:'market',externalKey:`map:${i}`,summary:`${p.name} reached mapped road ${i}.`});applyRealmConsequences(world);const a=consequenceAccounting(world);assert.equal(a.applied,1000);assert.equal(a.actors,1);assert.ok(a.pressuredWards<=32);assert.equal(a.touchedHouseholds,0);});