import test from 'node:test';
import assert from 'node:assert/strict';
import {LocalAuthority,makePlayer,addItem,quantity,spend,seedState} from '../src/state';
import {tickVitals} from '../src/state';
import {stats} from '../src/definitions';
import {height} from '../src/terrain';
test('light sword connects at capsule reach but still misses rear and distant targets',()=>{
 for(const [position,expected] of [[[0,0,1.9],'hit'],[[.65,0,1.3],'hit'],[[0,0,2.4],'miss'],[[0,0,-1],'miss']] as const){
  const {a,p,e}=fight();e.position=[...position];beginAction(p,0,'attack');a.state.tick=26;assert.equal(resolveStrike(a.state,p,e).outcome,expected);
 }
});
import {seedEnemies,beginAction,resolveStrike,setGuard,combatState,impactFeedback} from '../src/combat-rules';
function realm(){const a=new LocalAuthority();const p=makePlayer('Warden');p.position=[0,0,0];a.state.players[p.id]=p;return {a,p};}
test('inventory stacks have stable IDs and never exceed capacity',()=>{const {a,p}=realm();addItem(a.state,p,'wood',205);assert.equal(quantity(p,'wood'),205);assert.ok(p.inventory.every(s=>s.count>0&&s.count<=99));assert.equal(new Set(p.inventory.map(s=>s.id)).size,p.inventory.length);});
test('failed recipe payment is atomic',()=>{const {a,p}=realm();addItem(a.state,p,'wood',3);const before=structuredClone(p.inventory);assert.equal(spend(p,{wood:2,iron:4}),false);assert.deepEqual(p.inventory,before);});
test('a player cannot equip a weapon they do not own',()=>{const {a,p}=realm();assert.equal(a.dispatch({type:'equip',playerId:p.id,item:'sword'}).ok,false);assert.equal(p.equipped,'axe');});
test('trees require multiple hits and never place wood directly in inventory',()=>{const {a,p}=realm();a.state.resources.oak={id:'oak',kind:'tree',position:[0,0,1.5],variant:0,health:6,phase:'standing',rotation:0};for(let i=0;i<6;i++){assert.equal(a.dispatch({type:'harvest',playerId:p.id,resourceId:'oak'}).ok,true);assert.equal(quantity(p,'wood'),0);}assert.equal(a.state.resources.oak.phase,'falling');assert.equal(a.dispatch({type:'harvest',playerId:p.id,resourceId:'oak'}).ok,false);});
test('harvesting validates both equipment and distance',()=>{const {a,p}=realm();a.state.resources.rock={id:'rock',kind:'rock',position:[0,0,1.5],variant:0,health:4,phase:'standing',rotation:0};assert.equal(a.dispatch({type:'harvest',playerId:p.id,resourceId:'rock'}).ok,false);a.dispatch({type:'equip',playerId:p.id,item:'pickaxe'});p.position=[10,0,0];assert.equal(a.dispatch({type:'harvest',playerId:p.id,resourceId:'rock'}).ok,false);assert.equal(a.state.resources.rock.health,4);});
test('pickup validates reach and removes exactly the selected world drop',()=>{const {a,p}=realm();a.state.drops.log={id:'log',item:'wood',count:6,position:[0,0,5],rotation:[0,0,0]};assert.equal(a.dispatch({type:'pickup',playerId:p.id,dropId:'log'}).ok,false);p.position=[0,0,4];assert.equal(a.dispatch({type:'pickup',playerId:p.id,dropId:'log'}).ok,true);assert.equal(quantity(p,'wood'),6);assert.equal(a.state.drops.log,undefined);assert.equal(a.dispatch({type:'pickup',playerId:p.id,dropId:'log'}).ok,false);});
test('realm snapshots serialize resources, inventory, structures and progression',()=>{const {a,p}=realm();addItem(a.state,p,'wood',12);a.state.structures.house={id:'house',kind:'foundation',position:[2,0,3],yaw:0,ownerId:p.id};a.state.progress.push('harvest-tree');assert.deepEqual(JSON.parse(JSON.stringify(a.state)),a.state);});
test('separate authorities do not share global local-player state',()=>{const one=realm(),two=realm();addItem(one.a.state,one.p,'wood',6);assert.equal(quantity(two.p,'wood'),0);assert.deepEqual(seedState().players,{});});

test('crafting requires the actual station, reach, and atomic payment',()=>{const {a,p}=realm();addItem(a.state,p,'wood',3);addItem(a.state,p,'stone',2);addItem(a.state,p,'iron',4);const before=structuredClone(p.inventory);assert.equal(a.dispatch({type:'craft',playerId:p.id,recipeId:'sword',stationId:'alderbrook-bench'}).ok,false);assert.deepEqual(p.inventory,before);p.position=[...a.state.stations['alderbrook-bench'].position];assert.equal(a.dispatch({type:'craft',playerId:p.id,recipeId:'sword',stationId:'alderbrook-bench'}).ok,true);assert.equal(quantity(p,'sword'),1);assert.equal(quantity(p,'iron'),0);assert.ok(a.state.progress.includes('crafted-sword'));assert.equal(a.dispatch({type:'craft',playerId:p.id,recipeId:'sword',stationId:'alderbrook-bench'}).ok,false);});
test('cooking creates food and eating grants a timed strategic buff',()=>{const {a,p}=realm();p.position=[...a.state.stations['alderbrook-fire'].position];addItem(a.state,p,'wood',1);assert.equal(a.dispatch({type:'craft',playerId:p.id,recipeId:'grilled_venison',stationId:'alderbrook-fire'}).ok,true);assert.equal(p.buffs.length,0);assert.equal(a.dispatch({type:'eat',playerId:p.id,item:'grilled_venison'}).ok,true);assert.equal(stats(p).health,145);assert.equal(quantity(p,'grilled_venison'),0);tickVitals(a.state,481);assert.equal(stats(p).health,110);assert.equal(p.buffs.length,0);});
test('construction rejects floating roofs and supports a connected home',()=>{
 const {a,p}=realm();p.position=[0,height(0,0),0];addItem(a.state,p,'wood',50);addItem(a.state,p,'stone',10);addItem(a.state,p,'fiber',4);const before=quantity(p,'wood');
 assert.equal(a.dispatch({type:'place',playerId:p.id,kind:'roof',position:[0,20,0],yaw:0}).ok,false);assert.equal(quantity(p,'wood'),before);
 assert.equal(a.dispatch({type:'place',playerId:p.id,kind:'foundation',position:[0,height(0,0),0],yaw:0}).ok,false,'Do not trap a survivor under the floor');
 p.position=[0,height(0,3),3];assert.equal(a.dispatch({type:'place',playerId:p.id,kind:'foundation',position:[0,height(0,0),0],yaw:0}).ok,true);const floor=Object.values(a.state.structures)[0];
 for(const z of [-1.5,1.5])assert.equal(a.dispatch({type:'place',playerId:p.id,kind:z>0?'doorway':'wall',position:[0,floor.position[1]+.44,z],yaw:0,supportId:floor.id}).ok,true);
 assert.equal(a.dispatch({type:'place',playerId:p.id,kind:'roof',position:[0,floor.position[1]+3.14,0],yaw:0,supportId:floor.id}).ok,true);assert.equal(a.dispatch({type:'dismantle',playerId:p.id,structureId:floor.id}).ok,false);
 const door=Object.values(a.state.structures).find(s=>s.kind==='doorway')!;assert.equal(a.dispatch({type:'toggle_door',playerId:p.id,structureId:door.id}).ok,true);assert.equal(door.doorOpen,true);assert.deepEqual(p.home,floor.position);
});
test('storage transfers conserve items and cannot be repeated or stolen remotely',()=>{const {a,p}=realm();a.state.containers.box={id:'box',name:'Home',ownerId:p.id,position:[0,0,0],inventory:[],looted:true};addItem(a.state,p,'wood',12);assert.equal(a.dispatch({type:'transfer',playerId:p.id,containerId:'box',item:'wood',count:12,direction:'deposit'}).ok,true);assert.equal(quantity(p,'wood'),0);assert.equal(a.state.containers.box.inventory[0].count,12);assert.equal(a.dispatch({type:'transfer',playerId:p.id,containerId:'box',item:'wood',count:12,direction:'deposit'}).ok,false);p.position=[10,0,0];assert.equal(a.dispatch({type:'transfer',playerId:p.id,containerId:'box',item:'wood',count:12,direction:'withdraw'}).ok,false);});
test('inventory drops persist in the world and clear a removed equipped tool',()=>{const {a,p}=realm();assert.equal(a.dispatch({type:'drop',playerId:p.id,item:'axe',count:1}).ok,true);assert.equal(p.equipped,null);assert.equal(quantity(p,'axe'),0);assert.equal(Object.values(a.state.drops)[0].item,'axe');assert.equal(a.dispatch({type:'drop',playerId:p.id,item:'axe',count:-1}).ok,false);});
test('wild flax requires reach and can only be gathered once',()=>{const {a,p}=realm();a.state.forage.flax={id:'flax',position:[0,0,1],harvested:false};assert.equal(a.dispatch({type:'forage',playerId:p.id,forageId:'flax'}).ok,true);assert.equal(a.dispatch({type:'forage',playerId:p.id,forageId:'flax'}).ok,false);assert.equal(quantity(p,'fiber'),4);});

function fight(){const {a,p}=realm();seedEnemies(a.state);const e=a.state.enemies['raider-camp-sentry'];p.position=[0,0,0];p.yaw=0;p.equipped='sword';addItem(a.state,p,'sword',1);e.position=[0,0,1.5];e.yaw=Math.PI;return {a,p,e};}
test('strikes require authored timing, range and facing, and cannot repeat damage',()=>{
 const {a,p,e}=fight();assert.ok(beginAction(p,a.state.tick,'attack').ok);assert.equal(p.stamina,88);assert.equal(beginAction(p,0,'attack').ok,false);assert.equal(resolveStrike(a.state,p,e).ok,false);a.state.tick=35;const hit=resolveStrike(a.state,p,e);assert.equal(hit.damage,24);assert.equal(e.health,64);assert.equal(resolveStrike(a.state,p,e).ok,false);assert.equal(e.health,64);
 a.state.tick=80;beginAction(p,80,'attack');a.state.tick=115;e.position=[0,0,5];assert.equal(resolveStrike(a.state,p,e).outcome,'miss');
 a.state.tick=160;beginAction(p,160,'attack');a.state.tick=195;e.position=[0,0,-1];assert.equal(resolveStrike(a.state,p,e).outcome,'miss');
});
test('directional guarding spends stamina, reduces damage and can be broken',()=>{
 const {a,p,e}=fight();setGuard(e,0,true);beginAction(p,0,'attack');a.state.tick=35;assert.equal(resolveStrike(a.state,p,e).outcome,'blocked');assert.equal(e.health,86);assert.equal(e.stamina,82);
 a.state.tick=80;e.stamina=10;setGuard(e,80,true);beginAction(p,80,'attack');a.state.tick=115;assert.equal(resolveStrike(a.state,p,e).outcome,'hit');assert.equal(e.health,62);assert.equal(combatState(e).kind,'hit');
});
test('a guard cannot block a strike from behind',()=>{const {a,p,e}=fight();e.yaw=0;setGuard(e,0,true);beginAction(p,0,'attack');a.state.tick=35;assert.equal(resolveStrike(a.state,p,e).damage,24);});
test('dodge evades only its defined middle window',()=>{
 const {a,p,e}=fight();beginAction(p,0,'attack');beginAction(e,20,'dodge');a.state.tick=35;assert.equal(resolveStrike(a.state,p,e).outcome,'dodged');assert.equal(e.health,88);
 a.state.tick=100;beginAction(p,100,'attack');beginAction(e,101,'dodge');a.state.tick=135;assert.equal(resolveStrike(a.state,p,e).outcome,'hit');
});
test('enemy death is persistent, drops supplies once and never auto-loots',()=>{
 const {a,p,e}=fight();e.health=10;beginAction(p,0,'attack');a.state.tick=35;assert.equal(resolveStrike(a.state,p,e).outcome,'killed');assert.equal(e.phase,'dead');assert.equal(Object.keys(a.state.drops).length,3);assert.equal(quantity(p,'hide'),0);const before=structuredClone(a.state.drops);a.state.tick=100;beginAction(p,100,'attack');a.state.tick=135;resolveStrike(a.state,p,e);seedEnemies(a.state);assert.deepEqual(a.state.drops,before);assert.equal(e.health,0);
});
test('camp loot cannot bypass a living guard through direct transfer',()=>{const {a,p,e}=fight();a.state.containers['raider-cache']={id:'raider-cache',name:'Raider supplies',position:[0,0,1],inventory:[{id:'cache-hide',item:'hide',count:3,quality:1}],looted:false};assert.equal(a.dispatch({type:'open_container',playerId:p.id,containerId:'raider-cache'}).ok,false);assert.equal(a.dispatch({type:'transfer',playerId:p.id,containerId:'raider-cache',item:'hide',count:3,direction:'withdraw'}).ok,false);e.health=0;assert.equal(a.dispatch({type:'open_container',playerId:p.id,containerId:'raider-cache'}).ok,true);});
test('player death keeps tools, drops materials and needs explicit respawn',()=>{
 const {a,p,e}=fight();p.health=5;p.buffs=[{id:'grilled_venison',remaining:100}];addItem(a.state,p,'wood',12);beginAction(e,0,'attack');a.state.tick=35;assert.equal(resolveStrike(a.state,e,p).outcome,'killed');assert.equal(quantity(p,'wood'),0);assert.equal(quantity(p,'axe'),1);assert.equal(Object.values(a.state.drops)[0].count,12);tickVitals(a.state,10);assert.equal(p.health,0);assert.equal(a.dispatch({type:'eat',playerId:p.id,item:'berries'}).ok,false);assert.equal(a.dispatch({type:'respawn',playerId:p.id}).ok,true);assert.equal(p.health,145);assert.equal(Object.values(a.state.drops)[0].count,12);assert.equal(a.dispatch({type:'respawn',playerId:p.id}).ok,false);
});
test('a hit reaction cancels an unresolved attack and equipment cannot swap mid-swing',()=>{const {a,p,e}=fight();beginAction(p,0,'attack');assert.equal(a.dispatch({type:'equip',playerId:p.id,item:'axe'}).ok,false);beginAction(e,10,'attack');a.state.tick=35;resolveStrike(a.state,p,e);a.state.tick=45;assert.equal(resolveStrike(a.state,e,p).ok,false);assert.equal(p.health,100);});
test('heavy strikes spend more stamina, wait for their own contact, and pressure guarding',()=>{const {a,p,e}=fight();assert.ok(beginAction(p,0,'heavy').ok);assert.equal(p.stamina,74);a.state.tick=26;assert.equal(resolveStrike(a.state,p,e).ok,false);a.state.tick=50;assert.equal(resolveStrike(a.state,p,e).damage,41);a.state.tick=100;e.stamina=28;setGuard(e,100,true);beginAction(p,100,'heavy');a.state.tick=150;assert.equal(resolveStrike(a.state,p,e).outcome,'hit');assert.equal(e.stamina,0);});
test('a solid barrier prevents damage even inside weapon reach',()=>{const {a,p,e}=fight();a.lineOfSight=()=>false;beginAction(p,0,'attack');a.state.tick=26;const out=a.dispatch({type:'strike',playerId:p.id,enemyId:e.id});assert.equal(out.message,'Strike obstructed');assert.equal(e.health,88);});
test('a narrow heavy cut misses a target standing clear of its blade corridor',()=>{const {a,p,e}=fight();e.position=[.65,0,1.25];beginAction(p,0,'heavy');a.state.tick=50;assert.equal(resolveStrike(a.state,p,e).message,'The blade passed clear');assert.equal(e.health,88);});
test('impact feedback keeps light, heavy, axe, block, parry and animal hits mechanically distinct',()=>{
 const {p}=realm();p.equipped='sword';p.combat={kind:'attack',started:0,until:50,consumed:true,blocking:false,weapon:'sword'};const light=impactFeedback(p,'hit');p.combat={...p.combat,kind:'heavy'};const heavy=impactFeedback(p,'hit');p.equipped='axe';p.combat={...p.combat,kind:'attack',weapon:'axe'};const axe=impactFeedback(p,'hit'),block=impactFeedback(p,'blocked'),parry=impactFeedback(p,'parried'),animal=impactFeedback(p,'hit','animal');
 assert.equal(light.sound,'light_sword');assert.equal(heavy.sound,'heavy_sword');assert.equal(axe.sound,'axe');assert.equal(block.sound,'block');assert.equal(parry.sound,'parry');assert.equal(animal.sound,'animal');assert.ok(heavy.freeze>light.freeze&&heavy.knockback>axe.knockback&&axe.knockback>light.knockback);assert.ok(parry.freeze>block.freeze);assert.equal(block.particles,'metal');
});
