import * as T from 'three';
import {GLTFLoader, type GLTF} from 'three/addons/loaders/GLTFLoader.js';
import {MeshoptDecoder} from 'three/addons/libs/meshopt_decoder.module.js';
import {clone} from 'three/addons/utils/SkeletonUtils.js';
import {normalizeBatchColors} from './geometry-batching';
import {architecturalSurface,meadowBlades} from './visual-surfaces';
import {humanoidVisualBounds} from './visual-culling';
import {normalizeMedievalAsset} from './medieval-asset-specs';
export class Assets {
 kit!:GLTF; survivor!:GLTF; nature!:GLTF; textures:Record<string,T.Texture>={}; medieval:Record<string,T.Object3D>={}; time={value:0}; detail:Record<string,T.Object3D>={};
 sight={value:new T.Vector4(0,0,0,0)};
 updateSight(camera:T.Camera,target:T.Vector3,viewport:T.Vector2,active:boolean){
  const point=target.clone().add(new T.Vector3(0,1,0));camera.updateMatrixWorld();
  const depth=-point.clone().applyMatrix4(camera.matrixWorldInverse).z;point.project(camera);
  this.sight.value.set((point.x*.5+.5)*viewport.x,(point.y*.5+.5)*viewport.y,active?viewport.y*.34:0,depth);
 }
 async load(progress:(message:string)=>void){
  const loader=new GLTFLoader().setMeshoptDecoder(MeshoptDecoder),tl=new T.TextureLoader();
  const medieval=['wall_plaster_straight','wall_plaster_door_flat','wall_plaster_window_wide_flat','doorframe_flat_wooddark','door_1_flat','window_wide_flat1','corner_exterior_wood','roof_roundtiles_6x6','chimney','crate','wagon','fence_wood_single','fence_wood_ext1','fence_wood_ext2','support','stairs_exterior','floor_wooddark','roof_wooden_2x1','wall_arch','vine_1','border_straight','hut_a','hut_b','hut_c','hut_d','towerhouse','watchtower','barracks','storage','market','towncenter','windmill','well','wall','farm','crops','barrel','cauldron','hay','wood_pile','lantern','torch','campfire_burning_q'];
  progress('Opening the old road…');
  await Promise.all([loader.loadAsync('/assets/frontier-kit.glb').then(g=>this.kit=g),loader.loadAsync('/assets/wildlife.glb').then(g=>{this.nature=g;g.scene.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=o.receiveShadow=true;}});}),loader.loadAsync('/assets/survivor.glb').then(g=>this.survivor=g),...medieval.map(async n=>loader.loadAsync(`/assets/medieval/${n}.glb`).then(g=>this.medieval[n]=normalizeMedievalAsset(n,g.scene))),...['bark','meadow','leaves','timber','stone','grass','soil','thatch','fern','wool','leather','plaster'].map(async n=>{const t=await tl.loadAsync(`/textures/${n}.webp`);t.colorSpace=T.SRGBColorSpace;t.wrapS=t.wrapT=T.RepeatWrapping;t.anisotropy=8;this.textures[n]=t;})]);
  await Promise.all(['field','litter','rock','oak'].flatMap(n=>['color','normal','rough'].map(async channel=>{const key=n+'-'+channel,t=await tl.loadAsync('/textures/terrain/'+key+'.webp');t.colorSpace=channel==='color'?T.SRGBColorSpace:T.NoColorSpace;t.wrapS=t.wrapT=T.RepeatWrapping;t.anisotropy=8;this.textures[key]=t;})));
  await Promise.all(['market_stall','barrel'].map(async n=>{const g=await loader.loadAsync('/assets/art/'+n+'.glb');this.detail[n]=g.scene;}));
  this.detail.grass=meadowBlades(this.time);
  this.medieval.barrel=this.detail.barrel;this.medieval.market=this.detail.market_stall;
  const surfaceCache=new Map<T.Material,T.Material>();
  const surface=(old:T.Material)=>{if(surfaceCache.has(old))return surfaceCache.get(old)!;const m=old.clone() as T.MeshStandardMaterial;architecturalSurface(m,this.textures);surfaceCache.set(old,m);return m;};
  for(const [name,root] of Object.entries(this.medieval))root.traverse(o=>{if(o instanceof T.Mesh&&!['barrel','market','crops','vine_1','torch','lantern','campfire_burning_q'].includes(name))o.material=Array.isArray(o.material)?o.material.map(surface):surface(o.material);});
  for(const root of Object.values(this.medieval))root.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=o.receiveShadow=true;const materials=(Array.isArray(o.material)?o.material:[o.material]) as T.MeshStandardMaterial[];for(const m of materials){m.roughness=Math.max(.72,m.roughness??.5);m.metalness=Math.min(.18,m.metalness??0);}}});
  const batchColors=(scene:T.Object3D)=>{const byMaterial=new Map<T.Material,T.BufferGeometry[]>();scene.traverse(o=>{if(!(o instanceof T.Mesh)||Array.isArray(o.material))return;if(!byMaterial.has(o.material))byMaterial.set(o.material,[]);byMaterial.get(o.material)!.push(o.geometry);});for(const geometries of byMaterial.values())normalizeBatchColors(geometries);};
  batchColors(this.kit.scene);batchColors(this.nature.scene);
  const cache=new Map<T.Material,T.Material>();
  this.textures.grass.flipY=false;this.textures.grass.needsUpdate=true;this.textures.leaves.flipY=false;this.textures.leaves.needsUpdate=true;this.textures.fern.flipY=false;this.textures.fern.needsUpdate=true;
  this.kit.scene.traverse(o=>{if(!(o instanceof T.Mesh))return;o.castShadow=o.receiveShadow=true;
   const setup=(old:T.Material)=>{if(cache.has(old))return cache.get(old)!;const m=old.clone() as T.MeshStandardMaterial;m.color.setRGB(1,1,1);m.roughness=.88;m.metalness=0;m.vertexColors=true;
    if(m.name==='AW_bark'){m.map=this.textures['oak-color'];m.normalMap=this.textures['oak-normal'];m.normalScale.set(.75,.75);m.roughnessMap=this.textures['oak-rough'];m.vertexColors=false;m.color.setRGB(.83,.85,.83);}
    if(m.name==='AW_leaf'){m.map=this.textures.leaves;m.alphaTest=.46;m.alphaToCoverage=true;m.side=T.DoubleSide;m.roughness=.95;m.color.setRGB(.78,.93,.72);this.wind(m,.025);}
    if(m.name==='AW_foliage'){m.side=T.DoubleSide;this.wind(m,.09);}
    if(m.name==='AW_fernleaf'){m.map=this.textures.fern;m.alphaTest=.5;m.alphaToCoverage=true;m.side=T.DoubleSide;m.roughness=1;this.wind(m,.045);}
    if(m.name==='AW_grass'){m.map=this.textures.grass;m.alphaTest=.48;m.alphaToCoverage=true;m.side=T.DoubleSide;m.roughness=1;m.color.setRGB(.78,.94,.72);this.wind(m,.045);const sway=m.onBeforeCompile;m.onBeforeCompile=(s,r)=>{sway.call(m,s,r);s.vertexShader='varying vec3 awMeadowPosition; varying float awBladeHeight;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>',`#include <begin_vertex>\nvec4 awLocal=vec4(position,1.0);\n#ifdef USE_INSTANCING\nawLocal=instanceMatrix*awLocal;\n#endif\nawMeadowPosition=(modelMatrix*awLocal).xyz;awBladeHeight=position.y;`);s.fragmentShader='varying vec3 awMeadowPosition; varying float awBladeHeight;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <map_fragment>',`#include <map_fragment>\nfloat awField=.5+.5*sin(awMeadowPosition.x*.17+sin(awMeadowPosition.z*.13)*2.0)*sin(awMeadowPosition.z*.19);diffuseColor.rgb*=mix(vec3(.66,.78,.67),vec3(1.02,.98,.83),awField)*mix(.68,1.0,smoothstep(0.0,.42,awBladeHeight));`);};m.customProgramCacheKey=()=> 'layered-meadow-wind-v2';}
    if(m.name==='AW_stone'){m.map=this.textures['rock-color'];m.normalMap=this.textures['rock-normal'];m.normalScale.set(.7,.7);m.roughnessMap=this.textures['rock-rough'];m.vertexColors=false;m.color.setRGB(.85,.90,.91);m.roughness=1;m.onBeforeCompile=s=>{s.fragmentShader=s.fragmentShader.replace('#include <map_fragment>','#include <map_fragment>\nfloat awStoneL=dot(diffuseColor.rgb,vec3(.2126,.7152,.0722));diffuseColor.rgb=mix(diffuseColor.rgb,vec3(awStoneL)*vec3(.91,.97,1.02),.78);');};m.customProgramCacheKey=()=> 'aw-weathered-grey-stone-v1';}
    if(m.name==='AW_highland'){m.fog=true;m.roughness=1;m.color.setRGB(1,1,1);m.onBeforeCompile=s=>{s.fragmentShader=s.fragmentShader.replace('vec3 outgoingLight = totalDiffuse + totalSpecular + totalEmissiveRadiance;','vec3 outgoingLight = diffuseColor.rgb;');};m.customProgramCacheKey=()=> 'baked-highland-light-v2';}
    if(m.name==='AW_wood'){m.map=this.textures.timber;m.bumpMap=m.map;m.bumpScale=.018;m.color.setRGB(1.9,1.9,1.9);m.roughness=.93;}
    if(m.name==='AW_frame'){m.map=this.textures.timber;m.bumpMap=m.map;m.bumpScale=.025;m.color.setRGB(1.75,1.8,1.9);m.roughness=.93;}
    if(m.name==='AW_plaster'){m.map=this.textures.plaster;m.bumpMap=m.map;m.bumpScale=.018;m.roughness=1;m.color.setRGB(.98,.98,.95);m.onBeforeCompile=s=>{s.vertexShader='varying vec3 awPlasterPos;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nawPlasterPos=position;');s.fragmentShader='varying vec3 awPlasterPos;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <map_fragment>',`#include <map_fragment>\nfloat awStain=(1.0-smoothstep(.1,.9,awPlasterPos.y))*.22;float awWear=sin(awPlasterPos.x*18.0+sin(awPlasterPos.y*21.0))*sin(awPlasterPos.y*24.0)*.026;diffuseColor.rgb*=1.0-awStain+awWear;`);};m.customProgramCacheKey=()=> 'weathered-lime-plaster-v1';}
    if(m.name==='AW_endgrain'){m.vertexColors=false;m.color.set('#b69560');m.roughness=1;}
    if(m.name==='AW_thatch'){m.map=this.textures.thatch;m.bumpMap=m.map;m.bumpScale=.035;m.color.setRGB(1.65,1.7,1.85);m.roughness=1;}
    if(m.name==='AW_iron'||m.name==='AW_edge'){m.metalness=.78;m.roughness=.42;if(m.name==='AW_iron')m.color.setRGB(.24,.27,.28);}
    if(m.name==='AW_flaxflower'){m.side=T.DoubleSide;m.roughness=1;}
    if(m.name==='AW_ember'){m.emissive.set('#ef4c08');m.emissiveIntensity=1.8;}
    if(m.name==='AW_grass'){const meadow=m.onBeforeCompile;m.onBeforeCompile=(s,r)=>{meadow.call(m,s,r);s.vertexShader=s.vertexShader.replace('#include <beginnormal_vertex>','#include <beginnormal_vertex>\nobjectNormal=normalize(vec3(objectNormal.x*.12,1.0,objectNormal.z*.12));');s.fragmentShader=s.fragmentShader.replace('#include <normal_fragment_begin>','#include <normal_fragment_begin>\n#ifdef DOUBLE_SIDED\nnormal*=faceDirection;\n#endif');};const key=m.customProgramCacheKey();m.customProgramCacheKey=()=>key+'-canopy-normal-v2';}
    if(m.name==='AW_leaf'||m.name==='AW_bark')this.sightCutaway(m);
    cache.set(old,m);return m;};o.material=Array.isArray(o.material)?o.material.map(setup):setup(o.material);
  });
  this.survivor.scene.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=o.receiveShadow=true;o.frustumCulled=false;for(const m of (Array.isArray(o.material)?o.material:[o.material]) as T.MeshStandardMaterial[]){if(m.name==='AW_CostumeWool'||m.name==='AW_CostumeLeather'){m.map=this.textures[m.name==='AW_CostumeWool'?'wool':'leather'];m.color.setRGB(1,1,1);m.bumpMap=m.map;m.bumpScale=.002;m.roughness=.94;m.side=T.DoubleSide;}}}});
 }
 authoredLonghouse(){
  const root=new T.Group();root.name='Quaternius authored Alderbrook house';
  const add=(name:string,x:number,y:number,z:number,yaw=0)=>{const source=this.medieval[name];if(!source)return;const o=source.clone(true);o.position.set(x,y,z);o.rotation.y=yaw;root.add(o);};
  for(const x of [-2,0,2]){add(x===-2?'wall_plaster_door_flat':x===2?'wall_plaster_window_wide_flat':'wall_plaster_straight',x,0,4.56,Math.PI);add('wall_plaster_straight',x,0,-1.56,0);}
  for(const z of [-.5,1.5,3.5]){add('wall_plaster_straight',-3.06,0,z,Math.PI/2);add('wall_plaster_straight',3.06,0,z,-Math.PI/2);}
  for(const x of [-3.06,3.06])for(const z of [-1.56,4.56])add('corner_exterior_wood',x,0,z,0);
  add('doorframe_flat_wooddark',-2,0,4.55,Math.PI);add('door_1_flat',-1.49,0,4.54,Math.PI);add('window_wide_flat1',2,.75,4.55,Math.PI);
  add('roof_roundtiles_6x6',0,3.10,1.5,0);
  const gable=this.kit?.scene.getObjectByName('village_gable'),roof=this.medieval.roof_roundtiles_6x6;
  if(gable&&roof){const box=new T.Box3().setFromObject(gable),size=box.getSize(new T.Vector3()),center=box.getCenter(new T.Vector3()),roofSize=new T.Box3().setFromObject(roof).getSize(new T.Vector3()),sx=(roofSize.x-.14)/size.x,sy=(roofSize.y-.12)/size.y;
   for(const [z,yaw] of [[4.56,0],[-1.56,Math.PI]]){const end=gable.clone(true);end.name='Finished longhouse gable';end.scale.set(sx,sy,1);end.rotation.y=yaw;end.position.set(-center.x*sx,3.10-box.min.y*sy,z);root.add(end);}
  }
  add('chimney',2.05,3.05,.15,0);add('crate',2.25,0,5.25,-.18);add('wagon',-4.75,0,1.8,Math.PI/2);add('fence_wood_single',4.45,0,3.4,Math.PI/2);return root;
 }
 authoredFortification(){const root=new T.Group();root.name='Quaternius frontier fortification';const add=(name:string,x:number,y:number,z:number,yaw=0,scale=1)=>{const source=this.medieval[name];if(!source)return;const o=source.clone(true);o.position.set(x,y,z);o.rotation.y=yaw;o.scale.setScalar(scale);root.add(o);};add('fence_wood_ext1',-1.0,0,0,0,.92);add('fence_wood_ext2',1.0,0,0,Math.PI,.92);add('support',-1.48,0,-.12,0,.92);add('support',1.48,0,-.12,0,.92);add('border_straight',0,.15,.08,0,.72);return root;}
 authoredCampShelter(){const root=new T.Group();root.name='Quaternius MegaKit field shelter';const add=(name:string,x:number,y:number,z:number,yaw=0,scale=1)=>{const source=this.medieval[name];if(!source)return;const o=source.clone(true);o.position.set(x,y,z);o.rotation.y=yaw;o.scale.setScalar(scale);root.add(o);};add('floor_wooddark',0,.03,0,0,1.35);for(const x of [-1.45,1.45])for(const z of [-1.05,1.05])add('support',x,0,z,0,1.05);add('roof_wooden_2x1',-.9,2.55,0,0,1.25);add('roof_wooden_2x1',.9,2.55,0,0,1.25);add('border_straight',0,.2,-1.2,0,1.15);add('crate',.85,.04,.55,.25,.62);return root;}
 authoredFieldClutter(){const root=new T.Group();root.name='Quaternius field clutter';const satchel=this.kit.scene.getObjectByName('satchel');if(satchel){const o=satchel.clone(true);o.scale.setScalar(.86);o.position.set(-.18,.02,.08);root.add(o);}const crate=this.medieval.crate?.clone(true);if(crate){crate.scale.setScalar(.42);crate.position.set(.42,0,-.18);crate.rotation.y=.31;root.add(crate);}return root;}
 wind(m:T.MeshStandardMaterial,strength:number){m.onBeforeCompile=s=>{s.uniforms.awTime=this.time;s.vertexShader='uniform float awTime;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>',`#include <begin_vertex>\nfloat awH=max(position.y,0.0); transformed.x += sin(awTime*1.7+position.x*.8+position.z*.6)*${strength}*awH; transformed.z += cos(awTime*1.4+position.z*.7)*${strength*.5}*awH;`);};m.customProgramCacheKey=()=>`aw-wind-${strength}`;}
 sightCutaway(m:T.MeshStandardMaterial){const prior=m.onBeforeCompile,key=m.customProgramCacheKey();m.onBeforeCompile=(s,r)=>{prior.call(m,s,r);s.uniforms.awSight=this.sight;s.fragmentShader='uniform vec4 awSight;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <clipping_planes_fragment>',`#include <clipping_planes_fragment>\n    if(awSight.z>0.0 && vViewPosition.z<awSight.w-1.0){\n     float radius=length(gl_FragCoord.xy-awSight.xy)/awSight.z;\n     float keep=smoothstep(.78,1.0,radius);\n     ${m.name==='AW_leaf'?'keep*=smoothstep(1.5,3.5,length(vViewPosition));':''}\n     float stipple=fract(52.9829189*fract(dot(gl_FragCoord.xy,vec2(.06711056,.00583715))));\n     if(keep<.001 || keep<stipple)discard;\n    }`);};m.customProgramCacheKey=()=>key+'-sight-cutaway-v1';}
 prop(name:string){if(name==='grass'&&this.detail.grass)return this.detail.grass.clone(true);if(name==='highland')return new T.Group();if(name==='palisade'&&this.medieval.fence_wood_ext1)return this.authoredFortification();if(name==='camp_shelter'&&this.medieval.support)return this.authoredCampShelter();if(name==='satchel'&&this.medieval.crate)return this.authoredFieldClutter();if(name==='village_details'&&this.medieval.wall_plaster_straight)return this.authoredLonghouse();if((name==='village_roof'||name==='village_gable')&&this.medieval.roof_roundtiles_6x6)return new T.Group();const o=this.medieval[name]??this.kit.scene.getObjectByName(name)??this.nature?.scene.getObjectByName(name);if(!o)throw new Error('Missing authored asset: '+name);return o.clone(true);}
 human(){const root=clone(this.survivor.scene);root.traverse(o=>{if(o instanceof T.Mesh)humanoidVisualBounds(o);});return root;}
}
