import type {ImpactSound} from './combat-rules';

export class Soundscape {
 context?:AudioContext;master?:GainNode;volume=.35;noise?:AudioBuffer;
 start(){if(this.context){void this.context.resume();return;}const c=this.context=new AudioContext();this.master=c.createGain();this.master.gain.value=this.volume;this.master.connect(c.destination);const n=c.createBuffer(1,c.sampleRate*3,c.sampleRate),d=n.getChannelData(0);let last=0;for(let i=0;i<d.length;i++){last=(last+Math.random()*.04-.02)/1.015;d[i]=last;}this.noise=n;const wind=c.createBufferSource();wind.buffer=n;wind.loop=true;const f=c.createBiquadFilter();f.type='lowpass';f.frequency.value=420;const g=c.createGain();g.gain.value=.17;wind.connect(f).connect(g).connect(this.master);wind.start();}
 setVolume(v:number){this.volume=v;if(this.master)this.master.gain.value=v;}
 combat(kind:'swing'|ImpactSound){
  if(kind==='block'||kind==='parry'){this.impactMetal(kind==='parry');return;}
  if(!this.context||!this.master||!this.noise)return;
  const c=this.context,t=c.currentTime,s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();s.buffer=this.noise;f.type='bandpass';
  const swing=kind==='swing',heavy=kind==='heavy_sword',axe=kind==='axe',pick=kind==='pick',animal=kind==='animal';
  const start=swing?1900:pick?760:axe?500:heavy?360:animal?300:430,end=swing?380:pick?150:axe?92:heavy?72:animal?85:105;
  f.frequency.setValueAtTime(start,t);f.frequency.exponentialRampToValueAtTime(end,t+(swing?.18:.13));f.Q.value=pick?1.1:.7;
  g.gain.setValueAtTime(.01,t);g.gain.linearRampToValueAtTime(swing?.78:heavy?1.9:axe?1.6:pick?1.35:animal?1.25:1.45,t+.022);g.gain.exponentialRampToValueAtTime(.001,t+(swing?.23:heavy?.26:.2));s.connect(f).connect(g).connect(this.master);s.start(t);s.stop(t+.28);
  if(!swing){const o=c.createOscillator(),og=c.createGain();o.type=pick?'square':'triangle';o.frequency.setValueAtTime(pick?165:heavy?72:axe?88:animal?96:112,t);o.frequency.exponentialRampToValueAtTime(42,t+.14);og.gain.setValueAtTime(pick?.08:heavy?.25:axe?.21:animal?.13:.16,t);og.gain.exponentialRampToValueAtTime(.001,t+.17);o.connect(og).connect(this.master);o.start(t);o.stop(t+.2);}
 }
 private impactMetal(parry=false){if(!this.context||!this.master||!this.noise)return;const c=this.context,t=c.currentTime,src=c.createBufferSource();src.buffer=this.noise;const f=c.createBiquadFilter();f.type='bandpass';f.frequency.value=parry?4300:2700;f.Q.value=parry?1.8:1;const g=c.createGain();g.gain.setValueAtTime(parry?1.45:1.05,t);g.gain.exponentialRampToValueAtTime(.001,t+(parry?.16:.12));src.connect(f).connect(g).connect(this.master);src.start(t);src.stop(t+.2);const o=c.createOscillator(),og=c.createGain();o.type='triangle';o.frequency.setValueAtTime(parry?980:620,t);o.frequency.exponentialRampToValueAtTime(parry?440:210,t+.12);og.gain.setValueAtTime(parry?.2:.12,t);og.gain.exponentialRampToValueAtTime(.001,t+.16);o.connect(og).connect(this.master);o.start(t);o.stop(t+.18);}
 impact(kind:'wood'|'stone'|'step'|'metal'){if(kind==='metal'){this.impactMetal(false);return;}if(!this.context||!this.master||!this.noise)return;const c=this.context,t=c.currentTime,src=c.createBufferSource();src.buffer=this.noise;const f=c.createBiquadFilter();f.type='bandpass';f.frequency.value=kind==='wood'?850:kind==='stone'?1700:310;f.Q.value=.7;const g=c.createGain();g.gain.setValueAtTime(kind==='step'?.3:1.3,t);g.gain.exponentialRampToValueAtTime(.001,t+.22);src.connect(f).connect(g).connect(this.master);src.start(t);src.stop(t+.3);const o=c.createOscillator(),og=c.createGain();o.type='triangle';o.frequency.setValueAtTime(kind==='wood'?110:65,t);o.frequency.exponentialRampToValueAtTime(40,t+.16);og.gain.setValueAtTime(kind==='step'?.07:.2,t);og.gain.exponentialRampToValueAtTime(.001,t+.2);o.connect(og).connect(this.master);o.start(t);o.stop(t+.25);}
}
