import './backpack-ui.css';
import {GamePanels} from './game-panels';
import {ITEMS,type PlayerState,type Stack} from './state';
import {qualityBonusText,qualityLabel,qualityTier} from './loot';
import {affixSummary,ensureItemAffixes,itemDisplayName} from './item-affixes';

export const BACKPACK_SLOTS=40;
export function stackRarityClass(stack:Stack){return 'tier-'+qualityTier(stack.quality??1);}
export function backpackCapacity(player:PlayerState){return {used:player.inventory.length,total:BACKPACK_SLOTS,overflow:Math.max(0,player.inventory.length-BACKPACK_SLOTS)};}

function detailText(stack:Stack){const tier=qualityTier(stack.quality??1),quality=tier==='common'?'Common':qualityLabel(stack.quality??1);return `${quality} · ${qualityBonusText(stack.quality??1)} · ${affixSummary(stack)}`;}
function decorate(panel:GamePanels){const p=panel.player(),shell=panel.ui.querySelector<HTMLElement>('.game-panel');if(!shell)return;shell.classList.add('aw-backpack-panel','aw-oldworld-panel');const content=shell.querySelector<HTMLElement>('.panel-content'),grid=shell.querySelector<HTMLElement>('.pack-grid');if(!content||!grid)return;grid.classList.add('backpack-grid');
 const cap=backpackCapacity(p),head=document.createElement('div');head.className='aw-backpack-head';head.innerHTML='<div><small>FIELD PACK · LEATHER, IRON & BAD DECISIONS</small><strong>The Wanderer’s Backpack</strong><span></span></div><div><small>CAPACITY</small><strong></strong><span>Stacks · resources still stack normally</span></div>';head.querySelector('div:first-child span')!.textContent=`${p.archetype} · ${p.inventory.reduce((n,s)=>n+s.count,0)} total pieces carried`;head.querySelector('div:last-child strong')!.textContent=`${cap.used} / ${cap.total}`;content.prepend(head);
 const cards=Array.from(grid.querySelectorAll<HTMLElement>('.pack-item'));cards.forEach((card,index)=>{const stack=p.inventory[index];if(!stack)return;ensureItemAffixes(stack);card.classList.add(stackRarityClass(stack));card.dataset.awCount=stack.count>1?`×${stack.count}`:'';card.dataset.awQuality=qualityTier(stack.quality)==='common'?'':qualityLabel(stack.quality);card.dataset.awEquipped=p.equipped===stack.item?'1':'0';const strong=card.querySelector('strong');if(strong)strong.textContent=itemDisplayName(stack);card.title=`${itemDisplayName(stack)}\n${ITEMS[stack.item].description}\n${detailText(stack)}`;});
 for(let i=cards.length;i<BACKPACK_SLOTS;i++){const empty=document.createElement('div');empty.className='backpack-empty-slot';empty.setAttribute('aria-label','Empty backpack slot');grid.append(empty);}
 const details=document.createElement('div');details.className='aw-backpack-detail';const best=p.inventory.filter(s=>['axe','pickaxe','sword','fine_sword','bow'].includes(s.item)).sort((a,b)=>(b.quality??1)-(a.quality??1))[0],rare=p.inventory.filter(s=>qualityTier(s.quality)!=='common').length;details.innerHTML='<div><small>BEST THING CURRENTLY IN THIS BAG</small><strong></strong><span></span></div><div><small>PACK LEDGER</small><strong></strong><span></span></div>';details.querySelector('div:first-child strong')!.textContent=best?itemDisplayName(best):'Mostly supplies and optimism';details.querySelector('div:first-child span')!.textContent=best?detailText(best):'Find captains, giants, hidden caches and high-skill crafting for serious equipment.';details.querySelector('div:last-child strong')!.textContent=`${rare} uncommon+ stacks`;details.querySelector('div:last-child span')!.textContent=cap.overflow?`${cap.overflow} stacks beyond the nominal field-pack grid. Nothing is deleted.`:'Tab remains your pack key. Equip, eat, drop and reorder still use the real authority commands.';content.append(details);
}

function skinOtherPanels(){document.querySelectorAll<HTMLElement>('.character-profile,.fun-profile,.fun-market,.journal-content').forEach(el=>el.classList.add('aw-oldworld-panel'));}
const installed=Symbol.for('alderwatch.backpack-ui.v1');
export function installBackpackUI(){const g=globalThis as any;if(g[installed])return;g[installed]=true;const proto=GamePanels.prototype as any,original=proto.inventory;if(!proto.__awBackpack){proto.inventory=function(...args:any[]){const out=original.apply(this,args);decorate(this);skinOtherPanels();return out;};proto.__awBackpack=true;}if(typeof document!=='undefined'){const observer=new MutationObserver(()=>queueMicrotask(skinOtherPanels));observer.observe(document.body,{childList:true,subtree:true});}}
