import {PLAYER_BOTS} from './simulated-players';
import {NPC_PERSONAS} from './npc-dialogue';

function mergeUnique(base:readonly string[],extra:readonly string[]){
 const seen=new Set(base);return [...base,...extra.filter(line=>!seen.has(line))];
}

const BOT_AMBIENT:Record<string,readonly string[]>={
 kestrel:[
  'who aggroed half the forest and then vanished emotionally',
  'that wolf pathing is personal',
  'somebody duel me after i finish pretending to gather',
  'free tip stop putting doors where enemies arrive',
  'i found your corpse. extremely educational',
  'bear diff',
  'whoever shot that deer across the road okay fine that was clean',
  'im not carrying stone unless somebody says please badly',
  'chat why are there three wolves on me specifically',
  'that pull was illegal in at least four kingdoms',
  'if youre gonna kite it through town at least make it cinematic',
  'just watched somebody miss a stationary tree. elite',
  'need arrows. preferably the kind that hit things',
  'who put storage this far from everything i hate cardio',
  'okay the camp kinda slaps now dont quote me',
  'im taking the north road. send condolences in advance',
  'one more bear and im starting a guild called consequences',
  'whoever looted that hide before me we are now rivals',
 ],
 mira:[
  'i made extra arrows if anybody is running around with hopes only',
  'berries by the west trees btw',
  'who left one wood in the chest lol',
  'im bringing food dont make this weird',
  'wait the camp actually looks cute now',
  'i can do a supply run if ppl are building',
  'pls stop kiting wolves through the crafting area',
  'found some hides. taking requests',
  'there is stew in storage. yes i labeled it no nobody will read that',
  'need fiber? i accidentally became the fiber department',
  'i saw a deer by the creek if anyone needs meat',
  'okay who is hurt and pretending theyre not',
  'left a spare bow near camp for whoever keeps punching wildlife',
  'someone come gather with me this forest is giving horror movie',
  'i have too much stone again. success i guess',
  'the south road is clear rn. emphasis on rn',
  'whoever built that little shelter ty its actually useful',
  'if we all survive five minutes i can cook something',
 ],
 vex:[
  'that pull was so bad the wolves looked embarrassed',
  'stop strafing into the doorway',
  'i have seen abandoned sheds with better defense',
  'nice shot. dont get used to hearing that',
  'you had one job and somehow invented two worse ones',
  'who placed this chest in the combat lane',
  'if youre gonna greed the bear at least commit',
  'im fixing the wall because apparently standards are extinct',
  'three people hitting one wolf and somehow the wolf has tempo',
  'dont chase it downhill. actually never mind learn naturally',
  'that roof is one weather event from becoming floor',
  'who is tanking. trick question apparently nobody',
  'you can loot after it stops trying to eat you',
  'finally somebody brought arrows',
  'i watched that dodge. unfortunate',
  'if the gate is open again im naming names',
  'good fight. disgusting positioning',
  'im going north. try not to redesign the camp into rubble',
 ],
 laggoblin:[
  'crow just landed facing north. omen or bad vibes',
  'the bison know something',
  'why is that stump breathing emotionally',
  'found a rock with admin energy',
  'dont follow me im testing a theory with no good ending',
  'someone tell the moon to stop buffering',
  'heard a noise behind me. there was only inventory',
  'i think the road moved two pixels',
  'one of the crows owes me money now',
  'the fog is shaped like a tax problem',
  'found mushrooms in a circle. absolutely joining them',
  'why did every deer look left at once',
  'there is a barrel here with main character energy',
  'wolf screamed then vanished behind a bush. normal probably',
  'im following this crow until one of us learns something',
  'the bridge made a wood noise. suspicious for a bridge',
  'if anybody asks i was never under the map spiritually',
  'new theory: bears can smell confidence',
 ],
 river:[
  'put storage near where you use it. shocking concept i know',
  'if the roof leaks thats between you and geometry',
  'good wall. ugly as sin. good wall',
  'quit moving the workbench every ten minutes',
  'ive rebuilt worse. not much worse',
  'two more beams and we can stop pretending this is temporary',
  'somebody fetch fiber before we discover twine is important again',
  'if you build on the slope you own the slope problems',
  'door swings clear. small victories',
  'who used the last stone and left the empty stack there',
  'foundation first. decorations when the wolves learn manners',
  'that corner is square enough for frontier work',
  'you can call it a fort after it survives weather',
  'need another chest before inventory becomes floor storage again',
  'campfire is too close to the wall. fire remains undefeated',
  'bring me wood and bad opinions. mostly wood',
  'somebody finally fixed the gate. civilization advances',
  'not every flat patch needs a building on it. just most of them',
 ],
 niko77:[
  'i see bear. not problem yet',
  'need fiber? i have some',
  'we make second chest maybe yes',
  'this road too busy. camp little east better',
  'i go hunt small one',
  'wait i repair first',
  'who need stone tell me',
  'good roof. rain can be angry somewhere else',
  'two wolf near trees. dont go alone maybe',
  'i found berries. many berries',
  'we need more arrows before night',
  'this place nice when nobody screaming bear',
  'i bring wood to camp now',
  'inventory full again. good problem',
  'deer run north. something maybe there',
  'i can help build after this',
  'who put axe on road lol',
  'small camp becoming real base now',
 ],
 toast:[
  'selling emergency arrows at non-emergency pricing',
  'wolves down bad hide market up',
  'i have acquired too much stone this is a liquidity event',
  'buy low sell after bear',
  'who wants suspiciously affordable berries',
  'inventory full. economy thriving',
  'i can bundle wood with unsolicited advice',
  'rare opportunity: i stop talking if you buy something',
  'bear north. meat futures extremely active',
  'buying fiber before everyone suddenly remembers roofs exist',
  'i will accept crowns hides or compelling gossip',
  'someone dumped stone in storage. market intervention',
  'arrows are basically portable demand',
  'im cornering the berry market by eating half the supply',
  'this is not hoarding this is strategic reserves',
  'who needs wood and has poor financial judgment',
  'crow milk remains a volatile asset class',
  'if the road closes my prices become educational',
 ],
 quietfox:[
  'tracks north',
  'missed',
  'good roof',
  'two wolves',
  'not worth it',
  'heard chains',
  'leave the bear',
  'clean shot',
  'deer east',
  'wrong hill',
  'fresh blood',
  'road is clear',
  'not alone out there',
  'need fiber',
  'big tracks',
  'camp is loud',
  'something moved north',
  'take the ridge',
 ],
};

const NPC_TOPICS:Record<string,Record<string,readonly string[]>>={
 mara:{
  trade:[
   'Scarcity is just a tragedy wearing a price tag.',
   'If everyone suddenly needs timber, congratulations: timber is expensive now.',
   'I do not set the market. I merely stand where it confesses.',
   'You call it junk. I call it inventory with poor representation.',
   'Buy before the road closes, sell after everyone discovers why that mattered.',
   'I can offer fair, fast, or generous. Pick one and stop smiling.',
  ],
  rumor:[
   'Three caravans mentioned the same broken marker stone. Three liars rarely coordinate for free.',
   'Someone is buying rope in quantities that suggest either construction or an apology.',
   'A trader came through paying extra for old iron and refusing to say why. Naturally I charged more.',
   'The north road has been quiet for two days. Roads do not get quiet without help.',
   'Someone keeps asking for maps beyond Stonewake. Nobody buying those maps looks like a tourist.',
  ],
  crowmilk:[
   'Tomas proposed a tasting booth. I proposed distance.',
   'The margins are excellent because the questions are terrible.',
   'If he gets repeat customers I am checking whether they are the same people.',
  ],
  player:[
   'You are becoming expensive to underestimate.',
   'People gossip about you while buying supplies. Efficient, really.',
   'Your name moves goods now. Mostly weapons and bandages, which is interesting.',
  ],
 },
 wulfric:{
  trade:[
   'A cheap arrow teaches an expensive lesson.',
   'If the string sings loud enough to impress you, it is too loud.',
   'Straight shaft, honest head, dry feathers. The rest is boasting.',
   'Do not pay extra for decoration on something you intend to lose in a deer.',
  ],
  rumor:[
   'Found wolf tracks crossing old human bootprints. Both sets were moving fast.',
   'Something took a deer without leaving much blood. I dislike tidy predators.',
   'Heard three shots beyond the ridge yesterday. None were mine.',
   'Birds went up all at once north of the creek. Something walked under them.',
  ],
  player:[
   'Better feet lately. Still noisy when proud.',
   'You are learning when not to loose. Harder lesson than shooting.',
  ],
 },
 elske:{
  bees:[
   'Bees remember routes better than some merchants remember debts.',
   'A hive forgives clumsy hands once.',
   'The queen does not rule. She persists. Important distinction.',
   'Smoke is a request. Too much smoke is an eviction.',
   'A good hive sounds busy, not angry. Learn the difference before opening it.',
  ],
  karma:[
   'Bees judge vibration. Humans merely invented more paperwork for it.',
   'A calm hand receives fewer opinions from the hive.',
  ],
  rumor:[
   'One hive sealed itself early. Bees do not waste wax on superstition.',
   'The eastern bees came home carrying black pollen. I do not know a flower here that makes it.',
   'A bear passed the meadow and ignored fresh honey. That worries me more than theft.',
  ],
  crowmilk:[
   'Tomas asked whether bees could cross-brand. The bees became violent.',
   'A crow is not a cow with better mobility.',
  ],
  player:[
   'The hives tolerate you. I would not over-interpret it.',
   'You move more gently around them now. They noticed before I did.',
  ],
 },
 pell:{
  food:[
   'Salt first, bravery later.',
   'If the stew is gray, we have either failed or invented winter food.',
   'Never argue with a hungry hunter holding the ingredients.',
   'A pot can forgive tough meat. It cannot forgive impatience.',
   'If it smells good enough, people stop asking which animal it was.',
   'Soup is what happens when inventory management becomes cuisine.',
  ],
  crowmilk:[
   'I strained it. It strained me back.',
   'The pot still smells ambitious.',
   'Tomas says the aftertaste is part of the identity. I say identity can leave my kitchen.',
  ],
  rumor:[
   'Someone traded me mushrooms that glow faintly. They are now outside.',
   'A hunter swears the north bison are eating around one patch of grass. Animals know when not to be curious.',
   'Three travelers ordered food to go and left before it was hot. Something hurried them.',
  ],
  player:[
   'You eat like someone expecting another fight before dessert.',
   'I can tell how bad the road was by how fast you finish the first bowl.',
  ],
 },
 sigrid:{
  building:[
   'A straight wall is cheaper than a heroic repair.',
   'Roofs fail from the top. Builders fail from the mouth.',
   'If you can kick it loose, weather can do better.',
   'A doorway is a hole you promised would not become a collapse.',
   'Measure twice. If you refuse, at least swear quietly when I make you rebuild it.',
   'A good beam looks boring for fifty years. That is the point.',
  ],
  rumor:[
   'Found iron nails bent outward on a camp past the ridge. Think about that before sleeping.',
   'Someone built a lean-to north of the survey stones with joints I have never seen here.',
   'The old bridge shifted half a hand overnight. No flood. No wagon heavy enough.',
  ],
  player:[
   'Your walls have improved. I have reduced my insults accordingly.',
   'You finally built something I would stand under during rain. Progress.',
  ],
 },
 tomas:{
  crowmilk:[
   'We are entering our artisanal extraction phase. Very exclusive.',
   'Skepticism is the first stage of customer education.',
   'Every great industry begins with one person being asked to leave the market square.',
   'The supply chain is mostly crow, herb, optimism, and one bucket nobody else may use.',
   'We are exploring a premium reserve label. Same liquid, stronger confidence.',
   'People keep asking whether it is milk. That means they remember the name.',
  ],
  trade:[
   'Mara calls my pricing imaginary. That is how vision looks before adoption.',
   'I am not discounting. I am creating an early-believer tier.',
   'Distribution remains our only obstacle besides production, demand, and several definitions.',
  ],
  rumor:[
   'A traveler asked if crow milk travels well. That makes us regional now.',
   'I heard a settlement east of here has no crow-milk provider. Untapped territory.',
  ],
  player:[
   'Your continued willingness to ask questions places you in our premium demographic.',
   'You have the look of a person ready to become a case study.',
  ],
 },
 ylva:{
  wolves:[
   'Young wolves test distance. Old wolves test decisions.',
   'If the pack fans out, you are already in the conversation.',
   'A wolf looking behind you is not distracted. Check behind you.',
   'Do not follow a retreating pack into brush unless you enjoy being corrected.',
  ],
  eagles:[
   'Eagles miss. The rabbit still has to survive the falling eagle.',
   'A circling eagle is watching a map you cannot see.',
   'When the shadow stops moving, move yourself.',
  ],
  rumor:[
   'Foxes abandoned the north hollow for two nights. Nothing obvious moved in.',
   'I found bear tracks stopping at a standing stone. Then circling it.',
   'The deer are bedding closer to the road. Something off-road bothers them more than us.',
   'Found a bison trail split around empty ground. Herds do not vote without a reason.',
  ],
  player:[
   'You are quieter now. Not quiet. Quieter.',
   'You look up more often. Good. Tracks are not always on the ground.',
  ],
 },
 'gate-guard':{
  bounty:[
   'The board is not a suggestion. Unfortunately, neither are the teeth.',
   'If it has a reward posted, someone already tried optimism.',
   'Bring proof, not a story. I have enough stories and fewer fingers than forms.',
   'A bounty means the problem survived being called a problem.',
  ],
  rumor:[
   'Two travelers reported lanterns moving off-road in formation. I hate organized mysteries.',
   'The north marker was moved. Stones do not usually freelance.',
   'A wagon arrived with every latch tied shut from the outside. Driver would not discuss it.',
   'Someone rang the gate bell from the wrong side of the wall at dawn. There was nobody there when I opened it.',
  ],
  player:[
   'I have fewer forms when you are cooperative. Please remain statistically convenient.',
   'Your reputation reaches the gate before you do. Lately it has been arriving out of breath.',
  ],
 },
 moss:{
  rumor:[
   'Heard knocking under a bridge with no underside. Did not investigate. Growth.',
   'There is a fox that keeps stealing blue cloth. Fashion or ritual, cannot say.',
   'Saw a campfire burning with nobody around and rain going through it. I left.',
   'A crow followed me for six miles and then delivered me to another crow.',
   'Someone has been stacking stones beside the old road. Very neat. Very unnecessary.',
   'Found fresh footprints that ended in the middle of dry ground. I respected the boundary.',
  ],
  secret:[
   'If a path looks too convenient, ask who needed you to take it.',
   'Broken signs are often better maps than intact ones.',
   'Look where a tired traveler would hide something and where a thief would be too lazy to check.',
   'The best caches are found by people who wonder why one rock is cleaner than the others.',
  ],
  crowmilk:[
   'Tomas calls it a category. My stomach called it an event.',
   'I drank it twice because the first time seemed statistically unfair. It was not.',
  ],
  player:[
   'You have started appearing in rumors before you arrive. Efficient travel.',
   'People say you attract trouble. I think trouble appreciates reliable company.',
  ],
 },
};

const NPC_SUGGESTIONS:Record<string,readonly string[]>={
 mara:['Anything moving on the road?','What is overpriced today?','Who owes you money?'],
 wulfric:['What tracks have you seen?','What makes a bad hunter?','Best arrow for the March?'],
 elske:['Are the hives acting strange?','What makes bees angry?','Anything wrong in the meadow?'],
 pell:['What should never go in stew?','What are hunters bringing in?','Feed me a rumor.'],
 sigrid:['What building mistake do you hate?','Anything strange beyond town?','What needs fixing next?'],
 tomas:['What is the crow-milk roadmap?','Any investors?','What is the premium tier?'],
 ylva:['What are the deer avoiding?','Where should I not hunt?','Any strange tracks?'],
 'gate-guard':['Anything odd at the gate?','What is on the bounty board?','Who came through today?'],
 moss:['Tell me a bad idea.','What did you refuse to investigate?','What is off the map?'],
};

for(const bot of PLAYER_BOTS){const extra=BOT_AMBIENT[bot.id];if(extra)bot.ambient=mergeUnique(bot.ambient,extra);}
for(const [npcId,topics] of Object.entries(NPC_TOPICS)){
 const persona=NPC_PERSONAS[npcId];if(!persona)continue;
 for(const [topic,extra] of Object.entries(topics))persona.topics[topic]=mergeUnique(persona.topics[topic]??[],extra);
 const suggestions=NPC_SUGGESTIONS[npcId];if(suggestions)persona.suggestions=mergeUnique(persona.suggestions,suggestions);
}
