import * as T from 'three';
import RAPIER from '@dimforge/rapier3d-compat';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {Assets} from './assets';
import {Character} from './character';
import {Input} from './input';
import {LocalAuthority,loadWorld,saveWorld,tickVitals,type Vec3} from './state';
import {stats} from './definitions';
import {ACTION_CAMERA} from './follow-camera';
import {CellWindow,type CellCoord} from './area-cell-stream';
import {cellId,worldInt,worldRandom} from './world-address';
import {CROWNROAD_VALE,IRONWARD_BASIN,WOLFPINE,rememberCurrentArea,requestAreaTravel} from './realm-save';
import {CROWNROAD_ACTIVE_RADIUS,CROWNROAD_AREA,CROWNROAD_CELL,CROWNROAD_HALF,CROWNROAD_POIS,crownroadCellInBounds,crownroadIsGreyhavenCell,crownroadLocationName,crownroadWardForCell,crownroadWardForPosition} from './crownroad-world';
import {advanceRealmHistoryToTick,historyAccounting,latestHistoryLore,promoteCanonicalEvent} from './provenance-frontier';
import {advanceRealmPopulationToTick,ensureRealmPopulation} from './realm-population';
import {advanceRealmSocietyToTick,ensureRealmSocial} from './realm-society';
import {applyRealmConsequences,consequenceAccounting,wardPressureAt} from './realm-consequences';
import {CrownroadResidentPopulation,representativeHouseholdOrdinal} from './crownroad-residents';
import {greyhavenProvisionQuote,nearGreyhavenProvisioner,useGreyhavenProvisioner} from './crownroad-services';
import {AreaGameplayShell,type AreaMapLandmark} from './area-gameplay-shell';
import {createStreamedAreaFarField} from './streamed-area-far-field';
import {StreamedAreaSurfaceSet} from './streamed-area-surface';
import './style.css';import './loading-experience.css';import './realm-travel.css';import './social-lore.css';

const SUN_OFFSET=new T.Vector3(-58,78,42),westGate=new T.Vector3(-294,0,0),eastGate=new T.Vector3(294,0,0);
const app=document.querySelector<HTMLDivElement>('#app')!;app.innerHTML='<div id="loading"><div class="sigil">A</div><h1>CROWNROAD VALE</h1><p id="load-status">Unrolling the King’s Road…</p><div class="load-line"></div></div><div id="ui"></div>';
const ui=document.querySelector<HTMLDivElement>('#ui')!,renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.04;renderer.domElement.id='world';app.prepend(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#9eb8c2');scene.fog=new T.FogExp2('#aab9b8',.0039);const camera=new T.PerspectiveCamera(ACTION_CAMERA.fov,innerWidth/innerHeight,.08,850),pmrem=new T.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;scene.environmentIntensity=.28;pmrem.dispose();scene.add(new T.HemisphereLight('#dcecf0','#554c3c',1.0));const sun=new T.DirectionalLight('#ffe1ac',3.2);sun.position.copy(SUN_OFFSET);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-48,right:48,top:48,bottom:-48,near:1,far:185});sun.shadow.camera.updateProjectionMatrix();scene.add(sun,sun.target);
const worldRoot=new T.Group();scene.add(worldRoot);const assets=new Assets(),input=new Input(renderer.domElement),saved=loadWorld();if(!saved)throw new Error('Crownroad Vale requires an existing Alderwatch realm');const authority=new LocalAuthority(saved),player=Object.values(authority.state.players)[0];if(!player)throw new Error('Crownroad Vale requires a survivor');player.areaId=CROWNROAD_VALE;
let physics:RAPIER.World,character:Character,stream:CellWindow<ValeCell>,residents:CrownroadResidentPopulation,shell:AreaGameplayShell,surfaces:StreamedAreaSurfaceSet;let yaw=player.yaw,pitch=ACTION_CAMERA.pitch,distance=ACTION_CAMERA.distance,last=0,acc=0,autosave=0,frames=0,fps=0,fpsClock=0,notice='',noticeUntil=0;
interface ValeCell{group:T.Group;generated:T.Object3D[];colliders:RAPIER.Collider[]}
function addr(coord:CellCoord,slot:number,tag:string){return {realmSeed:authority.state.worldSeed??197709,areaId:CROWNROAD_AREA,cellX:coord.x,cellZ:coord.z,slot,tag};}
function authored(name:string,parent:T.Group,x:number,z:number,yaw=0,scale=1){const source=assets.medieval[name];if(!source)return;const o=source.clone(true);o.position.set(x,0,z);o.rotation.y=yaw;o.scale.setScalar(scale);parent.add(o);return o;}
function obstacle(cell:ValeCell,x:number,z:number,hx:number,hz:number,hy=2){cell.colliders.push(physics.createCollider(RAPIER.ColliderDesc.cuboid(hx,hy,hz).setTranslation(x,hy,z)));}
function road(group:T.Group,w:number,h:number,x=0,z=0,yaw=0){const mesh=new T.Mesh(surfaces.geometry(w,h),surfaces.road);mesh.rotation.x=-Math.PI/2;mesh.rotation.z=yaw;mesh.position.set(x,.018,z);mesh.name='stream-generated-road';group.add(mesh);return mesh;}
function greyhavenBuild(coord:CellCoord,group:T.Group,cell:ValeCell){
 if(!crownroadIsGreyhavenCell(coord))return;
 const gx=coord.x*CROWNROAD_CELL,gz=coord.z*CROWNROAD_CELL,block=(x:number,z:number,hx:number,hz:number,hy=2)=>obstacle(cell,gx+x,gz+z,hx,hz,hy),id=`${coord.x},${coord.z}`;
 if(id==='0,0'){
  authored('towncenter',group,-11,-7,.1,.85);authored('market',group,11,-8,-.1,.84);authored('well',group,0,11,0,.85);authored('towerhouse',group,-13,12,.3,.78);authored('barracks',group,14,12,-.2,.8);
  block(-11,-7,3.8,3.6);block(11,-8,3.3,2.9);block(-13,12,3.1,3.1);block(14,12,3.5,3);
 }else if(id==='-1,0'){
  authored('storage',group,-11,-11,.2,.88);authored('hut_d',group,10,-12,-.2,.78);authored('market',group,8,11,.15,.82);authored('barrel',group,13,12,.2,.72);authored('wagon',group,-3,12,-.35,.7);
  block(-11,-11,3,3);block(10,-12,2.7,2.7);block(8,11,3.2,2.8);
 }else if(id==='1,0'){
  authored('towerhouse',group,-10,-11,-.1,.8);authored('storage',group,11,-10,.25,.9);authored('barracks',group,10,11,-.15,.78);authored('wood_pile',group,-11,12,.2,.75);authored('crate',group,-8,12,-.1,.72);
  block(-10,-11,3.2,3.2,3);block(11,-10,3,3);block(10,11,3.4,3);
 }else if(id==='0,-1'){
  authored('hut_a',group,-12,-8,.25,.8);authored('hut_b',group,12,-8,-.25,.8);authored('market',group,-12,10,.15,.78);authored('watchtower',group,-13,-17,.05,.78);const gate=assets.authoredFortification();gate.position.set(0,0,-18);gate.scale.setScalar(1.3);group.add(gate);
  block(-12,-8,2.8,2.8);block(12,-8,2.8,2.8);block(-12,10,3.1,2.7);block(-13,-17,1.5,1.5,3);
 }else if(id==='0,1'){
  authored('hut_c',group,-12,8,.2,.84);authored('hut_d',group,12,8,-.2,.8);authored('storage',group,-12,-10,.15,.86);authored('well',group,11,-10,0,.82);authored('watchtower',group,13,17,-.08,.8);const gate=assets.authoredFortification();gate.position.set(0,0,18);gate.rotation.y=Math.PI;gate.scale.setScalar(1.3);group.add(gate);
  block(-12,8,2.6,2.6);block(12,8,2.7,2.7);block(-12,-10,3,3);block(13,17,1.5,1.5,3);
 }else if(id==='-1,-1'){
  authored('farm',group,-11,-9,.15,.82);authored('crops',group,-10,11,0,.9);authored('hut_a',group,11,8,-.3,.77);authored('well',group,11,-10,0,.75);
  block(-11,-9,2.9,2.9);block(11,8,2.7,2.7);
 }else if(id==='1,-1'){
  authored('storage',group,-11,-9,.15,.88);authored('hut_b',group,11,-10,-.25,.78);authored('wood_pile',group,-10,10,.3,.8);authored('campfire_burning_q',group,8,10,0,.75);authored('wagon',group,12,9,-.4,.7);
  block(-11,-9,3,3);block(11,-10,2.7,2.7);
 }else if(id==='-1,1'){
  authored('towerhouse',group,-10,8,.1,.8);authored('hut_c',group,10,-8,-.2,.82);authored('well',group,10,10,0,.8);authored('market',group,-10,-10,.15,.76);
  block(-10,8,3.2,3.2,3);block(10,-8,2.6,2.6);block(-10,-10,3.1,2.7);
 }else if(id==='1,1'){
  authored('barracks',group,-10,8,.12,.8);authored('watchtower',group,11,-10,-.08,.84);authored('storage',group,10,10,-.18,.84);authored('wall',group,-11,-11,.2,.72);
  block(-10,8,3.4,3);block(11,-10,1.6,1.6,3);block(10,10,3,3);
 }
}
function poiBuild(coord:CellCoord,group:T.Group,cell:ValeCell){const gx=coord.x*CROWNROAD_CELL,gz=coord.z*CROWNROAD_CELL;
 if(coord.x===-4&&coord.z===0){const fort=assets.authoredFortification();fort.position.set(-13,0,0);fort.rotation.y=Math.PI/2;fort.scale.setScalar(1.4);group.add(fort);authored('watchtower',group,12,10,.2,.82);authored('wagon',group,8,-10,-.4,.76);obstacle(cell,gx+12,gz+10,1.6,1.6,3);}
 if(coord.x===-2&&coord.z===-3){authored('market',group,-10,-2,.2,.85);authored('storage',group,11,-4,-.3,.88);authored('wagon',group,6,11,.4,.78);authored('well',group,-8,11,0,.8);obstacle(cell,gx-10,gz-2,3.1,2.8);obstacle(cell,gx+11,gz-4,3,3);}
 if(coord.x===3&&coord.z===-3){authored('farm',group,-12,-4,.15,.84);authored('hut_c',group,11,-5,-.35,.82);authored('crops',group,-10,11,0,.9);authored('well',group,10,10,0,.8);obstacle(cell,gx-12,gz-4,2.8,2.8);obstacle(cell,gx+11,gz-5,2.5,2.5);}
 if(coord.x===1&&coord.z===5){authored('barracks',group,-9,-2,.15,.85);authored('watchtower',group,11,3,-.15,.9);authored('wall',group,0,13,0,.82);const fort=assets.authoredFortification();fort.position.set(0,0,-13);fort.scale.setScalar(1.35);group.add(fort);obstacle(cell,gx-9,gz-2,3.3,3);obstacle(cell,gx+11,gz+3,1.7,1.7,3);}
 if(coord.x===5&&coord.z===2){authored('wall',group,-12,-8,.5,.9);authored('wall',group,8,10,-.2,.88);authored('watchtower',group,12,-10,.4,.75);authored('wood_pile',group,-5,4,.2,.8);obstacle(cell,gx+12,gz-10,1.6,1.6,3);}
 if(coord.x===-3&&coord.z===4){authored('towerhouse',group,0,-5,0,.88);authored('hut_d',group,-13,8,.2,.77);authored('well',group,12,8,0,.82);authored('wall',group,0,15,0,.78);obstacle(cell,gx,gz-5,3.2,3.2,3);}
 if(coord.x===-6&&coord.z===0){const gate=assets.authoredFortification();gate.position.set(-5,0,0);gate.rotation.y=Math.PI/2;gate.scale.setScalar(1.65);group.add(gate);authored('watchtower',group,5,11,.15,.85);obstacle(cell,gx+5,gz+11,1.6,1.6,3);}
 if(coord.x===6&&coord.z===0){const gate=assets.authoredFortification();gate.position.set(5,0,0);gate.rotation.y=-Math.PI/2;gate.scale.setScalar(1.8);group.add(gate);authored('watchtower',group,-7,11,-.15,.9);authored('barracks',group,-9,-10,.2,.76);obstacle(cell,gx-7,gz+11,1.7,1.7,3);obstacle(cell,gx-9,gz-10,3.1,2.8);}
}
function causalDressing(coord:CellCoord,group:T.Group){const pressure=wardPressureAt(authority.state,crownroadWardForCell(coord));if(pressure.watch>=4)authored('fence_wood_ext1',group,-15,-15,.2,.72);if(pressure.market>=4){authored('wagon',group,14,-13,-.35,.68);authored('barrel',group,11,-12,.2,.72);}if(pressure.guild>=4){authored('wood_pile',group,-13,13,.4,.75);authored('crate',group,-10,13,-.2,.7);}if(pressure.kin>=4)authored('hay',group,14,14,.1,.7);}
function isRoadCell(coord:CellCoord){return coord.z===0||coord.x===0||(coord.x===-2&&coord.z>=-3&&coord.z<=0)||(coord.x===3&&coord.z>=-3&&coord.z<=0)||(coord.z===4&&coord.x>=-3&&coord.x<=0)||(coord.z===2&&coord.x>=0&&coord.x<=5);}
function buildCell(coord:CellCoord):ValeCell{const group=new T.Group();group.name='crownroad-cell-'+cellId(CROWNROAD_AREA,coord.x,coord.z);group.position.set(coord.x*CROWNROAD_CELL,0,coord.z*CROWNROAD_CELL);worldRoot.add(group);const cell:ValeCell={group,generated:[],colliders:[]};if(!crownroadCellInBounds(coord))return cell;const ground=new T.Mesh(surfaces.geometry(CROWNROAD_CELL+.3,CROWNROAD_CELL+.3),surfaces.ground);ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;ground.name='stream-generated-ground';group.add(ground);cell.generated.push(ground);if(coord.z===0)cell.generated.push(road(group,CROWNROAD_CELL+.5,7));if(coord.x===0)cell.generated.push(road(group,7,CROWNROAD_CELL+.5));if((coord.x===-2&&coord.z>=-3&&coord.z<=0)||(coord.x===3&&coord.z>=-3&&coord.z<=0))cell.generated.push(road(group,5,CROWNROAD_CELL+.5));if((coord.z===4&&coord.x>=-3&&coord.x<=0)||(coord.z===2&&coord.x>=0&&coord.x<=5))cell.generated.push(road(group,CROWNROAD_CELL+.5,5));const clutter=['barrel','hay','wood_pile','fence_wood_single','crate','wagon'] as const,roadside=isRoadCell(coord),count=crownroadIsGreyhavenCell(coord)?0:roadside?1+worldInt(addr(coord,2,'clutter-count'),3):worldInt(addr(coord,2,'clutter-count'),2);for(let i=0;i<count;i++){const name=clutter[worldInt(addr(coord,i,'clutter-kind'),clutter.length)],x=(worldRandom(addr(coord,i,'clutter-x'))-.5)*39,z=(worldRandom(addr(coord,i,'clutter-z'))-.5)*39;if((coord.z===0&&Math.abs(z)<5)||(coord.x===0&&Math.abs(x)<5))continue;authored(name,group,x,z,worldRandom(addr(coord,i,'clutter-yaw'))*Math.PI*2,.55+worldRandom(addr(coord,i,'clutter-scale'))*.4);}greyhavenBuild(coord,group,cell);poiBuild(coord,group,cell);causalDressing(coord,group);return cell;}
function disposeCell(handle:{value:ValeCell}){const cell=handle.value;for(const c of cell.colliders)physics.removeCollider(c,true);cell.group.removeFromParent();}
function buildVale(){physics=new RAPIER.World({x:0,y:-9.81,z:0});physics.createCollider(RAPIER.ColliderDesc.cuboid(CROWNROAD_HALF,.12,CROWNROAD_HALF).setTranslation(0,-.12,0));for(const [x,z,hx,hz] of [[-CROWNROAD_HALF,0,.35,CROWNROAD_HALF],[CROWNROAD_HALF,0,.35,CROWNROAD_HALF],[0,-CROWNROAD_HALF,CROWNROAD_HALF,.35],[0,CROWNROAD_HALF,CROWNROAD_HALF,.35]] as const)physics.createCollider(RAPIER.ColliderDesc.cuboid(hx,3,hz).setTranslation(x,3,z));surfaces=new StreamedAreaSurfaceSet(assets,{ground:'#aeb08a',road:'#a79a7d',groundRepeat:8,roadRepeat:10});worldRoot.add(createStreamedAreaFarField({width:CROWNROAD_HALF*2,depth:CROWNROAD_HALF*2,groundTexture:assets.textures['field-color']??assets.textures.meadow,roadTexture:assets.textures.soil,groundColor:'#aeb08a',roads:[{width:7,length:CROWNROAD_HALF*2,yaw:Math.PI/2,name:'far-king-road'},{width:7,length:CROWNROAD_HALF*2,name:'far-north-road'},{x:-96,z:-72,width:5,length:192,name:'far-carters-road'},{x:144,z:-72,width:5,length:192,name:'far-bellmere-road'},{x:-72,z:192,width:5,length:192,yaw:Math.PI/2,name:'far-abbey-road'},{x:120,z:96,width:5,length:288,yaw:Math.PI/2,name:'far-blackbarrow-road'}]}));stream=new CellWindow({cellSize:CROWNROAD_CELL,radius:CROWNROAD_ACTIVE_RADIUS,create:buildCell,dispose:disposeCell});character=new Character(assets,physics,player,worldRoot);character.getTick=()=>authority.state.tick;character.onActionRequest=action=>authority.dispatch({type:'combat_action',playerId:player.id,action}).ok;character.onImpact=()=>{};stream.update(player.position[0],player.position[2]);residents=new CrownroadResidentPopulation(worldRoot,assets,authority.state);residents.refresh(player.position[0],player.position[2]);input.active=true;input.captureCamera=true;}
function snapshot(){player.position=character.root.position.toArray() as Vec3;player.yaw=character.root.rotation.y;rememberCurrentArea(player);}
function save(){snapshot();advanceRealmPopulationToTick(authority.state);advanceRealmSocietyToTick(authority.state);advanceRealmHistoryToTick(authority.state);applyRealmConsequences(authority.state);saveWorld(authority.state);}
function transition(title:string,status:string){const el=document.createElement('div');el.className='realm-transition-loader';el.innerHTML='<div class="realm-loader-card"><div class="sigil"><span>A</span></div><small>CROWNROAD VALE</small><h2></h2><div class="realm-loader-status"></div><div class="realm-loader-track"><i></i></div></div>';el.querySelector('h2')!.textContent=title;el.querySelector<HTMLElement>('.realm-loader-status')!.textContent=status;document.body.append(el);}
function travelBasin(){save();requestAreaTravel(IRONWARD_BASIN);input.active=false;transition('RETURNING TO IRONWARD','Crossing Saint Orra’s road west toward the high basin…');requestAnimationFrame(()=>requestAnimationFrame(()=>location.reload()));}
function travelWolfpine(){save();requestAreaTravel(WOLFPINE);input.active=false;transition('PASSING KING’S EAST GATE','Greyhaven falls behind as the Crownroad enters Wolfpine…');requestAnimationFrame(()=>requestAnimationFrame(()=>location.reload()));}
function notify(message:string){notice=message;noticeUntil=performance.now()+6500;}
function hud(){ui.innerHTML='<div class="compass">N · CROWNROAD VALE</div><div class="location"><small>THE CROWNROAD</small><span>King’s West Gate</span></div><div class="quest"><small>THE KING’S ROAD</small><p>Reach Greyhaven, then follow the old road through King’s East Gate to Wolfpine.</p></div><div class="vitals"><div class="health"><i></i><span></span></div><div class="stamina"><i></i></div></div><div class="interaction" hidden></div><div class="controls">WASD Move · Shift Sprint · Space Dodge · Mouse Look · E gates / residents / Greyhaven market</div><output id="performance"></output><aside id="ironward-state"></aside><aside id="crownroad-history"></aside>';}
function discover(){const p=character.root.position;for(const poi of CROWNROAD_POIS){const x=poi.cell.x*CROWNROAD_CELL,z=poi.cell.z*CROWNROAD_CELL,flag='crownroad-poi:'+poi.id;if(authority.state.progress.includes(flag)||Math.hypot(p.x-x,p.z-z)>23)continue;authority.state.progress.push(flag);const ward=crownroadWardForPosition(p.x,p.z),house=representativeHouseholdOrdinal(authority.state,ward,poi.id);promoteCanonicalEvent(authority.state,{source:'player',actorId:player.id,actorName:player.name,ward,channel:poi.kind==='fort'||poi.kind==='ruin'?'watch':poi.kind==='market'||poi.kind==='city'?'market':'kin',externalKey:'discover:'+poi.id,subjects:[poi.id,`house:${house}`],summary:`${player.name} reached ${poi.name} and mapped the road into it. A local household witnessed the arrival and the discovery entered the realm’s causal record.`});applyRealmConsequences(authority.state);notice=`DISCOVERED · ${poi.name}`;noticeUntil=performance.now()+6000;}}
function updateHud(now:number){const max=stats(player),health=ui.querySelector<HTMLElement>('.health i'),stamina=ui.querySelector<HTMLElement>('.stamina i'),label=ui.querySelector<HTMLElement>('.health span')!;if(health)health.style.width=player.health/max.health*100+'%';if(stamina)stamina.style.width=player.stamina/max.stamina*100+'%';label.textContent=Math.ceil(player.health)+' / '+max.health;const p=character.root.position,west=p.distanceTo(westGate),east=p.distanceTo(eastGate),resident=residents.nearest(p.toArray() as Vec3),market=nearGreyhavenProvisioner(p.x,p.z),prompt=ui.querySelector<HTMLElement>('.interaction')!,interact=input.take('KeyE');prompt.hidden=west>5&&east>5&&!resident&&!market;const quote=market?greyhavenProvisionQuote(authority.state,player):undefined;prompt.textContent=west<=5?'E · Return to Ironward Basin':east<=5?'E · King’s East Gate · Enter Wolfpine':market&&quote?`E · Greyhaven provisioner · ${quote.timberCost} timber → ${quote.stewCount} Marcher’s stew${quote.stewCount>1?'s':''} · ${quote.standing.toUpperCase()}`:resident?`E · Speak to ${resident.descriptor.name}`:'';if(interact&&west<=5){travelBasin();return;}if(interact&&east<=5){travelWolfpine();return;}if(interact&&market&&west>5&&east>5){const out=useGreyhavenProvisioner(authority.state,player);notice=out.message;noticeUntil=performance.now()+7000;if(out.ok)save();}else if(interact&&resident&&west>5&&east>5){notice=residents.meet(resident,player);noticeUntil=performance.now()+7000;}ui.querySelector<HTMLElement>('.location span')!.textContent=crownroadLocationName(p.x,p.z);const history=historyAccounting(advanceRealmHistoryToTick(authority.state)),consequences=consequenceAccounting(authority.state),ward=crownroadWardForPosition(p.x,p.z),pressure=wardPressureAt(authority.state,ward);ui.querySelector<HTMLElement>('#ironward-state')!.textContent=`CROWNROAD · WARD ${ward} · ${stream.active.size}/${stream.maxActive} CORE · ${stream.residentSize}/${stream.maxResident} RESIDENT · ${residents.runtimes.length}/18 PEOPLE · ${history.activeRumors} LIVE THREADS · ${consequences.actors} REMEMBERED ACTORS`;ui.querySelector<HTMLElement>('#crownroad-history')!.textContent=`${latestHistoryLore(authority.state,ward)} · PRESSURE K${pressure.kin.toFixed(1)} M${pressure.market.toFixed(1)} W${pressure.watch.toFixed(1)} G${pressure.guild.toFixed(1)}`;ui.querySelector<HTMLElement>('#performance')!.textContent=`${fps} FPS · ${renderer.info.render.calls} draws`;ui.querySelector<HTMLElement>('.quest p')!.textContent=now<noticeUntil?notice:'Greyhaven, Bellmere, Northwatch, Blackbarrow and the Abbey live inside Crownroad; King’s East Gate now opens Wolfpine.';}
function mapLandmarks():AreaMapLandmark[]{const pois:CrownroadPOIMap[]=CROWNROAD_POIS.map(p=>({label:p.name,position:[p.cell.x*CROWNROAD_CELL,0,p.cell.z*CROWNROAD_CELL] as Vec3,kind:p.kind==='city'||p.kind==='village'?'settlement':p.kind==='fort'||p.kind==='crossing'?'gate':p.kind==='ruin'?'danger':'site'}));return [{label:'Gatewatch Road',position:westGate.toArray() as Vec3,kind:'gate'},...pois];}
type CrownroadPOIMap={label:string;position:Vec3;kind:AreaMapLandmark['kind']};
function frame(now:number){const frameDt=last?(now-last)/1000:.016,dt=Math.min(frameDt,.05);last=now;frames++;fpsClock+=frameDt;if(fpsClock>1){fps=Math.round(frames/fpsClock);frames=0;fpsClock=0;}const shellConsumed=shell.update();yaw+=input.dx*.003;pitch=T.MathUtils.clamp(pitch+input.dy*.002,ACTION_CAMERA.minPitch,ACTION_CAMERA.maxPitch);distance=T.MathUtils.clamp(distance+input.wheel*.85,ACTION_CAMERA.minDistance,ACTION_CAMERA.maxDistance);acc+=dt;while(acc>=1/60){character.preStep(1/60,input,yaw,!shell.blocked);physics.step();character.postStep(1/60);tickVitals(authority.state,1/60);authority.state.tick++;acc-=1/60;}stream.update(character.root.position.x,character.root.position.z);residents.refresh(character.root.position.x,character.root.position.z);residents.update(now/1000);if(!shell.blocked){discover();if(!shellConsumed)updateHud(now);else updateHud(now);}autosave+=dt;if(autosave>10){save();autosave=0;}const p=character.root.position,aim=p.clone().add(new T.Vector3(0,1.25,0));camera.position.copy(p).add(new T.Vector3(-Math.sin(yaw)*Math.cos(pitch)*distance,1.35+Math.sin(pitch)*distance,Math.cos(yaw)*Math.cos(pitch)*distance));const rayDir=camera.position.clone().sub(aim),rayLength=rayDir.length();rayDir.normalize();const hit=physics.castRay(new RAPIER.Ray(aim,rayDir),rayLength,true,undefined,undefined,character.collider,character.body);if(hit&&hit.timeOfImpact<rayLength)camera.position.copy(aim).addScaledVector(rayDir,Math.max(.7,hit.timeOfImpact-.25));camera.lookAt(aim);sun.position.copy(p).add(SUN_OFFSET);sun.target.position.copy(p);sun.target.updateMatrixWorld();renderer.render(scene,camera);input.endFrame();requestAnimationFrame(frame);}
async function init(){await RAPIER.init();await assets.load(message=>document.querySelector('#load-status')!.textContent=message);ensureRealmPopulation(authority.state);ensureRealmSocial(authority.state);advanceRealmHistoryToTick(authority.state);applyRealmConsequences(authority.state);if(!authority.state.progress.includes('entered-crownroad-vale')){authority.state.progress.push('entered-crownroad-vale');promoteCanonicalEvent(authority.state,{source:'player',actorId:player.id,actorName:player.name,ward:112,channel:'market',externalKey:'realm-entry:crownroad-vale',summary:`${player.name} crossed into Crownroad Vale, opening a new major region of the realm record.`});applyRealmConsequences(authority.state);notice='CROWNROAD VALE DISCOVERED · the realm just got much larger';noticeUntil=performance.now()+8000;}buildVale();hud();shell=new AreaGameplayShell({areaId:CROWNROAD_VALE,areaName:'Crownroad Vale',ui,authority,input,player:()=>player,bounds:{minX:-CROWNROAD_HALF,maxX:CROWNROAD_HALF,minZ:-CROWNROAD_HALF,maxZ:CROWNROAD_HALF},landmarks:mapLandmarks,renderHud:hud,save,equipVisual:item=>character.equip(item),notify});shell.mountHud();document.querySelector('#loading')!.remove();saveWorld(authority.state);requestAnimationFrame(frame);}
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});window.addEventListener('pagehide',()=>{if(character)save();stream?.dispose();residents?.dispose();surfaces?.dispose();});init().catch(error=>{console.error(error);document.querySelector('#load-status')!.textContent='Crownroad Vale could not load: '+(error instanceof Error?error.message:String(error));});
