import * as T from 'three';
import RAPIER from '@dimforge/rapier3d-compat';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {Assets} from './assets';
import {Character} from './character';
import {Input} from './input';
import {LocalAuthority,addItem,loadWorld,saveWorld,tickVitals,type Vec3} from './state';
import {stats} from './definitions';
import {ACTION_CAMERA} from './follow-camera';
import {DungeonGraphWindow} from './dungeon-graph-stream';
import {DEEP_IRON_GRAPH,DEEP_IRON_ROOM_BY_ID,DEEP_IRON_ROOMS,advanceDeepIronToTick,deepIronCertificateSummary,ensureDeepIron,nearestDeepIronRoom,type DeepIronRoom} from './deep-iron-dungeon';
import {DEEP_IRON_MINE,IRONWARD_BASIN,rememberCurrentArea,requestAreaTravel} from './realm-save';
import {worldInt,worldRandom} from './world-address';
import {AreaGameplayShell,type AreaMapLandmark} from './area-gameplay-shell';
import './style.css';
import './loading-experience.css';
import './realm-travel.css';

const ROOM=14,DOOR=4,WALL=.48,AREA='deep-iron-mine';
const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML='<div id="loading"><div class="sigil">A</div><h1>DEEP IRON MINE</h1><p id="load-status">Lighting the old workings…</p><div class="load-line"></div></div><div id="ui"></div>';
const ui=document.querySelector<HTMLDivElement>('#ui')!;
const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.9;renderer.domElement.id='world';app.prepend(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#080a09');scene.fog=new T.FogExp2('#090b0a',.026);const camera=new T.PerspectiveCamera(ACTION_CAMERA.fov,innerWidth/innerHeight,.08,220);
const pmrem=new T.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.02).texture;scene.environmentIntensity=.08;pmrem.dispose();scene.add(new T.HemisphereLight('#6e756e','#171511',.22));
const playerLight=new T.PointLight('#f1bf78',2.2,20,2);scene.add(playerLight);
const worldRoot=new T.Group();scene.add(worldRoot);const assets=new Assets(),input=new Input(renderer.domElement);const saved=loadWorld();if(!saved)throw new Error('Deep Iron requires an existing Alderwatch realm');const authority=new LocalAuthority(saved);const player=Object.values(authority.state.players)[0];if(!player)throw new Error('Deep Iron requires a survivor');player.areaId=DEEP_IRON_MINE;const dungeon=ensureDeepIron(authority.state);
let physics:RAPIER.World,character:Character,stream:DungeonGraphWindow<RoomRuntime>,shell:AreaGameplayShell;let currentRoom=nearestDeepIronRoom(player.position),yaw=0,pitch=ACTION_CAMERA.pitch,distance=Math.min(ACTION_CAMERA.distance,6.4),last=0,acc=0,autosave=0,frames=0,fps=0,fpsClock=0,toastUntil=0,toast='';
interface RoomRuntime{group:T.Group;generated:T.Object3D[];colliders:RAPIER.Collider[]}

function addr(room:DeepIronRoom,slot:number,tag:string){return {realmSeed:authority.state.worldSeed??197709,areaId:AREA,cellX:Math.round(room.position[0]/18),cellZ:Math.round(room.position[2]/18),slot,tag};}
function authored(name:string,parent:T.Group,x:number,y:number,z:number,yaw=0,scale=1){const source=assets.medieval[name];if(!source)return;const o=source.clone(true);o.position.set(x,y,z);o.rotation.y=yaw;o.scale.setScalar(scale);parent.add(o);return o;}
function collider(runtime:RoomRuntime,x:number,y:number,z:number,hx:number,hy:number,hz:number){const c=physics.createCollider(RAPIER.ColliderDesc.cuboid(hx,hy,hz).setTranslation(x,y,z));runtime.colliders.push(c);return c;}
function directionOpen(room:DeepIronRoom,axis:'x'|'z',sign:number){return DEEP_IRON_GRAPH[room.id].neighbors.some(id=>{const n=DEEP_IRON_ROOM_BY_ID[id],delta=axis==='x'?n.position[0]-room.position[0]:n.position[2]-room.position[2],other=axis==='x'?Math.abs(n.position[2]-room.position[2]):Math.abs(n.position[0]-room.position[0]);return Math.sign(delta)===sign&&Math.abs(delta)>=12&&other<10;});}
function wall(runtime:RoomRuntime,room:DeepIronRoom,axis:'x'|'z',sign:number,material:T.Material){const open=directionOpen(room,axis,sign),cx=room.position[0],cz=room.position[2],side=ROOM/2;if(axis==='x'){const x=cx+sign*side;if(open){for(const z of [cz-(DOOR/2+(ROOM-DOOR)/4),cz+(DOOR/2+(ROOM-DOOR)/4)]){const mesh=new T.Mesh(new T.BoxGeometry(WALL,4,(ROOM-DOOR)/2),material);mesh.position.set(x,2,z);mesh.castShadow=mesh.receiveShadow=true;worldRoot.add(mesh);runtime.generated.push(mesh);collider(runtime,x,2,z,WALL/2,2,(ROOM-DOOR)/4);}}else{const mesh=new T.Mesh(new T.BoxGeometry(WALL,4,ROOM),material);mesh.position.set(x,2,cz);mesh.castShadow=mesh.receiveShadow=true;worldRoot.add(mesh);runtime.generated.push(mesh);collider(runtime,x,2,cz,WALL/2,2,ROOM/2);}}else{const z=cz+sign*side;if(open){for(const x of [cx-(DOOR/2+(ROOM-DOOR)/4),cx+(DOOR/2+(ROOM-DOOR)/4)]){const mesh=new T.Mesh(new T.BoxGeometry((ROOM-DOOR)/2,4,WALL),material);mesh.position.set(x,2,z);mesh.castShadow=mesh.receiveShadow=true;worldRoot.add(mesh);runtime.generated.push(mesh);collider(runtime,x,2,z,(ROOM-DOOR)/4,2,WALL/2);}}else{const mesh=new T.Mesh(new T.BoxGeometry(ROOM,4,WALL),material);mesh.position.set(cx,2,z);mesh.castShadow=mesh.receiveShadow=true;worldRoot.add(mesh);runtime.generated.push(mesh);collider(runtime,cx,2,z,ROOM/2,2,WALL/2);}}}
function corridor(runtime:RoomRuntime,room:DeepIronRoom,other:DeepIronRoom,material:T.Material){if(room.id>other.id)return;const ax=room.position[0],az=room.position[2],bx=other.position[0],bz=other.position[2],dx=bx-ax,dz=bz-az,length=Math.hypot(dx,dz);if(length<ROOM||length>60)return;const floor=new T.Mesh(new T.PlaneGeometry(4,length-ROOM+1),material);floor.rotation.x=-Math.PI/2;floor.rotation.z=-Math.atan2(dx,dz);floor.position.set((ax+bx)/2,.012,(az+bz)/2);floor.receiveShadow=true;worldRoot.add(floor);runtime.generated.push(floor);}
function buildRoom(id:string):RoomRuntime{
 const room=DEEP_IRON_ROOM_BY_ID[id],group=new T.Group();group.name='deep-iron-room-'+id;worldRoot.add(group);const runtime:RoomRuntime={group,generated:[],colliders:[]};
 const stone=assets.textures.stone.clone();stone.needsUpdate=true;stone.repeat.set(3,3);const material=new T.MeshStandardMaterial({map:stone,color:new T.Color().setHSL(.09,.08,.25+worldRandom(addr(room,0,'stone'))*.05),roughness:1});
 const floor=new T.Mesh(new T.PlaneGeometry(ROOM,ROOM),material);floor.rotation.x=-Math.PI/2;floor.position.set(room.position[0],0,room.position[2]);floor.receiveShadow=true;worldRoot.add(floor);runtime.generated.push(floor);collider(runtime,room.position[0],-.12,room.position[2],ROOM/2,.12,ROOM/2);
 wall(runtime,room,'x',-1,material);wall(runtime,room,'x',1,material);wall(runtime,room,'z',-1,material);wall(runtime,room,'z',1,material);
 for(const neighborId of DEEP_IRON_GRAPH[id].neighbors)corridor(runtime,room,DEEP_IRON_ROOM_BY_ID[neighborId],material);
 for(const x of [-4.8,4.8])for(const z of [-4.8,4.8])authored('support',group,room.position[0]+x,0,room.position[2]+z,worldRandom(addr(room,1+Math.round(x+z),'support-yaw'))*.08,.8);
 authored('torch',group,room.position[0]-5.5,1.2,room.position[2],Math.PI/2,.72);
 const light=new T.PointLight('#d58b45',1.25,14,2);light.position.set(room.position[0]-4.8,2.4,room.position[2]);worldRoot.add(light);runtime.generated.push(light);
 const clutter=['barrel','crate','wood_pile','lantern'] as const;for(let i=0;i<2+worldInt(addr(room,30,'clutter-count'),3);i++){const kind=clutter[worldInt(addr(room,31+i,'clutter-kind'),clutter.length)],x=room.position[0]+(worldRandom(addr(room,40+i,'clutter-x'))-.5)*8,z=room.position[2]+(worldRandom(addr(room,50+i,'clutter-z'))-.5)*8;authored(kind,group,x,0,z,worldRandom(addr(room,60+i,'clutter-yaw'))*Math.PI*2,.55+worldRandom(addr(room,70+i,'clutter-scale'))*.3);}
 if(room.cache&&!dungeon.openedCaches.includes(room.id)){const cache=authored('storage',group,room.position[0]+3.8,0,room.position[2]-2.8,.35,.65);if(cache)cache.name='deep-iron-cache-'+room.id;}
 if(room.feature==='lever'&&!dungeon.unlockedShortcuts.includes('old-lift'))authored('border_straight',group,room.position[0]+3.8,.8,room.position[2],Math.PI/2,.55);
 if(room.feature==='lower-gate'){const boundary=deepIronCertificateSummary(authority.state);const gate=assets.authoredFortification();gate.position.set(room.position[0],0,room.position[2]+5.2);gate.scale.setScalar(boundary.passage==='blocked'?1.75:1.35);group.add(gate);if(boundary.passage==='blocked')collider(runtime,room.position[0],1.6,room.position[2]+5.2,2.6,1.6,.45);}
 return runtime;
}
function disposeRoom(handle:{value:RoomRuntime}){for(const c of handle.value.colliders)physics.removeCollider(c,true);for(const o of handle.value.generated){if(o instanceof T.Mesh){o.geometry.dispose();for(const m of (Array.isArray(o.material)?o.material:[o.material]))m.dispose();}o.removeFromParent();}handle.value.group.removeFromParent();}
function buildMine(){physics=new RAPIER.World({x:0,y:-9.81,z:0});stream=new DungeonGraphWindow({graph:DEEP_IRON_GRAPH,budget:7,create:buildRoom,dispose:disposeRoom});character=new Character(assets,physics,player,worldRoot);character.getTick=()=>authority.state.tick;character.onActionRequest=action=>authority.dispatch({type:'combat_action',playerId:player.id,action}).ok;character.onImpact=()=>{};currentRoom=nearestDeepIronRoom(player.position);stream.update(currentRoom.id);input.active=true;input.captureCamera=true;}
function snapshot(){player.position=character.root.position.toArray() as Vec3;player.yaw=character.root.rotation.y;rememberCurrentArea(player);}
function save(){snapshot();advanceDeepIronToTick(authority.state);saveWorld(authority.state);}
function showTransition(title:string,status:string){const el=document.createElement('div');el.className='realm-transition-loader';el.innerHTML='<div class="realm-loader-card"><div class="sigil"><span>A</span></div><small>DEEP IRON</small><h2></h2><div class="realm-loader-status"></div><div class="realm-loader-track"><i></i></div></div>';el.querySelector('h2')!.textContent=title;el.querySelector<HTMLElement>('.realm-loader-status')!.textContent=status;document.body.append(el);}
function travelBasin(){save();requestAreaTravel(IRONWARD_BASIN);input.active=false;showTransition('CLIMBING TO IRONWARD','Cold daylight reaches down the entrance shaft…');requestAnimationFrame(()=>requestAnimationFrame(()=>location.reload()));}
function say(message:string,now:number){toast=message;toastUntil=now+4200;}
function notify(message:string){say(message,performance.now());}
function cacheLoot(room:DeepIronRoom,now:number){if(!room.cache||dungeon.openedCaches.includes(room.id))return false;const count=4+worldInt(addr(room,90,'cache-iron'),6),stone=2+worldInt(addr(room,91,'cache-stone'),5);addItem(authority.state,player,'iron',count);addItem(authority.state,player,'stone',stone);dungeon.openedCaches.push(room.id);say(`${room.name}: ${count} iron ore · ${stone} fieldstone`,now);save();return true;}
function interact(now:number){const room=currentRoom,p=character.root.position,center=new T.Vector3().fromArray(room.position);if(room.id==='entrance'&&p.distanceTo(center)<4){travelBasin();return;}if(cacheLoot(room,now))return;if(room.feature==='lever'&&!dungeon.unlockedShortcuts.includes('old-lift')){dungeon.unlockedShortcuts.push('old-lift');say('Old Winch released · the broken lift shortcut can move again',now);save();return;}if(room.feature==='lift'&&dungeon.unlockedShortcuts.includes('old-lift')){player.position=[0,.03,4];character.root.position.fromArray(player.position);character.body.setNextKinematicTranslation({x:0,y:.93,z:4});currentRoom=DEEP_IRON_ROOM_BY_ID.entrance;stream.update(currentRoom.id);say('The old lift groans back toward the Ironvein Mouth',now);return;}if(room.feature==='lower-gate'){const b=deepIronCertificateSummary(authority.state);say(`Lower Works certificate ${b.certificate} · ${b.alarm} alarm · ${b.passage} passage · ${b.rubble} rubble sectors`,now);return;}say(room.name+' · old workings, no usable mechanism nearby',now);}
function hud(){ui.innerHTML='<div class="compass">DEEP IRON · LOWER ROAD</div><div class="location"><small>IRONVEIN WORKINGS</small><span>Ironvein Mouth</span></div><div class="quest"><small>THE DEEP IRON</small><p>Descend through the old mine. The Lower Works are still changing beyond the sealed cut.</p></div><div class="vitals"><div class="health"><i></i><span></span></div><div class="stamina"><i></i></div></div><div class="interaction" hidden></div><div class="controls">WASD Move · Shift Sprint · Space Dodge · Mouse Look · E Interact</div><output id="performance"></output><aside id="ironward-state"></aside>';}
function updateHud(now:number){const max=stats(player),health=ui.querySelector<HTMLElement>('.health i'),stamina=ui.querySelector<HTMLElement>('.stamina i'),label=ui.querySelector<HTMLElement>('.health span')!;if(health)health.style.width=player.health/max.health*100+'%';if(stamina)stamina.style.width=player.stamina/max.stamina*100+'%';label.textContent=Math.ceil(player.health)+' / '+max.health;ui.querySelector<HTMLElement>('.location span')!.textContent=currentRoom.name;if(!dungeon.discovered.includes(currentRoom.id)){dungeon.discovered.push(currentRoom.id);dungeon.deepestDepth=Math.max(dungeon.deepestDepth,currentRoom.depth);say(`DISCOVERED · ${currentRoom.name}`,now);}const prompt=ui.querySelector<HTMLElement>('.interaction')!;let text='';if(currentRoom.id==='entrance')text='E · Climb back to Ironward Basin';else if(currentRoom.cache&&!dungeon.openedCaches.includes(currentRoom.id))text='E · Search the old mine cache';else if(currentRoom.feature==='lever'&&!dungeon.unlockedShortcuts.includes('old-lift'))text='E · Release the old winch';else if(currentRoom.feature==='lift'&&dungeon.unlockedShortcuts.includes('old-lift'))text='E · Ride the old lift to the entrance';else if(currentRoom.feature==='lower-gate')text='E · Inspect the sealed Lower Works';prompt.hidden=!text;prompt.textContent=text;const b=deepIronCertificateSummary(authority.state);ui.querySelector<HTMLElement>('#ironward-state')!.textContent=`DEEP IRON · DEPTH ${dungeon.deepestDepth}/12 · ${dungeon.discovered.length}/${DEEP_IRON_ROOMS.length} ROOMS · ${stream.active.size}/${stream.maxActive} ACTIVE · CUT CERT ${b.certificate} · ${b.alarm.toUpperCase()} · ${b.passage.toUpperCase()} · ORE OUT ${b.delivered}`;ui.querySelector<HTMLElement>('#performance')!.textContent=`${fps} FPS · ${renderer.info.render.calls} draws`;ui.querySelector<HTMLElement>('.quest p')!.textContent=now<toastUntil?toast:(dungeon.lowerWorks.recent.at(-1)??'Descend through the old mine. The Lower Works are still changing beyond the sealed cut.');}
function mapLandmarks():AreaMapLandmark[]{const known=new Set([...dungeon.discovered,'entrance',currentRoom.id]);return DEEP_IRON_ROOMS.filter(room=>known.has(room.id)).map(room=>({label:room.name,position:room.position,kind:room.id==='entrance'?'gate':room.feature==='lower-gate'?'danger':'site'}));}
function frame(now:number){const frameDt=last?(now-last)/1000:.016,dt=Math.min(frameDt,.05);last=now;frames++;fpsClock+=frameDt;if(fpsClock>1){fps=Math.round(frames/fpsClock);frames=0;fpsClock=0;}const shellConsumed=shell.update();if(!shellConsumed&&!shell.blocked&&input.take('KeyE'))interact(now);yaw+=input.dx*.003;pitch=T.MathUtils.clamp(pitch+input.dy*.002,ACTION_CAMERA.minPitch,ACTION_CAMERA.maxPitch);distance=T.MathUtils.clamp(distance+input.wheel*.65,3.6,8);acc+=dt;while(acc>=1/60){character.preStep(1/60,input,yaw,!shell.blocked);physics.step();character.postStep(1/60);tickVitals(authority.state,1/60);authority.state.tick++;acc-=1/60;}const room=nearestDeepIronRoom(character.root.position.toArray() as Vec3);if(room.id!==currentRoom.id){currentRoom=room;stream.update(room.id);}autosave+=dt;if(autosave>10){save();autosave=0;}if(!shell.blocked)updateHud(now);const p=character.root.position,aim=p.clone().add(new T.Vector3(0,1.2,0));camera.position.copy(p).add(new T.Vector3(-Math.sin(yaw)*Math.cos(pitch)*distance,1.25+Math.sin(pitch)*distance,Math.cos(yaw)*Math.cos(pitch)*distance));const rayDir=camera.position.clone().sub(aim),rayLength=rayDir.length();rayDir.normalize();const hit=physics.castRay(new RAPIER.Ray(aim,rayDir),rayLength,true,undefined,undefined,character.collider,character.body);if(hit&&hit.timeOfImpact<rayLength)camera.position.copy(aim).addScaledVector(rayDir,Math.max(.65,hit.timeOfImpact-.2));camera.lookAt(aim);playerLight.position.copy(p).add(new T.Vector3(0,2,0));renderer.render(scene,camera);input.endFrame();requestAnimationFrame(frame);}
async function init(){await RAPIER.init();await assets.load(message=>document.querySelector('#load-status')!.textContent=message);advanceDeepIronToTick(authority.state);buildMine();hud();shell=new AreaGameplayShell({areaId:DEEP_IRON_MINE,areaName:'Deep Iron Mine',ui,authority,input,player:()=>player,bounds:{minX:-52,maxX:52,minZ:-8,maxZ:110},landmarks:mapLandmarks,renderHud:hud,save,equipVisual:item=>character.equip(item),notify});shell.mountHud();document.querySelector('#loading')!.remove();saveWorld(authority.state);requestAnimationFrame(frame);}
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});window.addEventListener('pagehide',()=>{if(character)save();});
init().catch(error=>{console.error(error);document.querySelector('#load-status')!.textContent='Deep Iron could not load: '+(error.message??error);});