import './fun-systems.css';
import {Assets} from './assets';
import {Landscape} from './landscape';
import {LocalAuthority,ITEMS,type Command,type ItemId,type PlayerState,type WorldState} from './state';
import {SKILLS,SKILL_ORDER,characterTitle,ensureSkills,skillRank,skillTitle,type SkillId} from './skills';
import {ACHIEVEMENTS,ensureRenown,fameTitle,karmaTitle,recordRenownEvent,reputationTitle,type AchievementDefinition,type RenownEvent} from './renown';
import {MARKET_GOODS,marketBuy,marketSell} from './market';
import {NpcPopulation,activeNpcPopulation,setActiveNpcPopulation} from './npcs';
import {sanitizeWorldProp} from './world-sanity';

let activeState:WorldState|undefined;
let activeAuthority:LocalAuthority|undefined;
let seenAnimals=new Set<string>(),seenEnemies=new Set<string>();
let skillSnapshot:Record<string,number>={};
let talkTimer=0;
const populations=new WeakMap<Landscape,NpcPopulation>();
const installed=Symbol.for('alderwatch.fun-systems.v1');

function player(){return activeState?Object.values(activeState.players)[0]:undefined;}
function persist(){if(activeState)try{localStorage.setItem('alderwatch.realm.v1',JSON.stringify(activeState));}catch{}}
function setState(state:WorldState){if(activeState===state)return;activeState=state;const p=player();if(p)ensureRenown(p);seenAnimals=new Set(Object.values(state.animals??{}).filter(a=>a.dead).map(a=>a.id));seenEnemies=new Set(Object.values(state.enemies??{}).filter(e=>e.health<=0).map(e=>e.id));skillSnapshot=p?{...ensureSkills(p)}:{};}
function feed(){let el=document.querySelector<HTMLElement>('.achievement-feed');if(!el){el=document.createElement('div');el.className='achievement-feed';document.body.append(el);}return el;}
function achievementPop(a:AchievementDefinition){const line=document.createElement('div');line.className='achievement-pop';line.innerHTML='<small>ACHIEVEMENT UNLOCKED</small><strong></strong><span></span>';line.querySelector('strong')!.textContent=a.title;line.querySelector('span')!.textContent=a.description;feed().prepend(line);while(feed().children.length>4)feed().lastElementChild?.remove();setTimeout(()=>line.remove(),9000);}
function announce(unlocked:readonly AchievementDefinition[]){for(const a of unlocked)achievementPop(a);if(unlocked.length)persist();}
function event(p:PlayerState,id:RenownEvent,amount=1){announce(recordRenownEvent(p,id,amount,activeState?.tick??0));}
function toastNpc(name:string,role:string,line:string){let el=document.querySelector<HTMLElement>('.npc-talk');if(!el){el=document.createElement('div');el.className='npc-talk';document.body.append(el);}el.innerHTML='<small></small><strong></strong><div></div>';el.querySelector('small')!.textContent=role.toUpperCase();el.querySelector('strong')!.textContent=name;el.querySelector('div')!.textContent=line;clearTimeout(talkTimer);talkTimer=window.setTimeout(()=>el?.remove(),5200);}

function installAssetSanity(){const proto=Assets.prototype as any;if(proto.__awFunProp)return;const original=proto.prop;proto.prop=function(name:string){return sanitizeWorldProp(original.call(this,name));};proto.__awFunProp=true;}
function installNpcWorld(){const proto=Landscape.prototype as any;if(proto.__awFunWorld)return;const terrain=proto.terrain,update=proto.update;proto.terrain=function(...args:any[]){const out=terrain.apply(this,args);setState(this.state);const old=activeNpcPopulation();old?.dispose();const population=new NpcPopulation(this.scene,this.assets,this.state);populations.set(this,population);setActiveNpcPopulation(population);return out;};proto.update=function(time:number,...args:any[]){const out=update.apply(this,[time,...args]);const pop=populations.get(this);if(pop){setState(this.state);setActiveNpcPopulation(pop);pop.update(time);}return out;};proto.__awFunWorld=true;}
function installAuthorityEvents(){const proto=LocalAuthority.prototype as any;if(proto.__awFunDispatch)return;const original=proto.dispatch;proto.dispatch=function(c:Command){activeAuthority=this;setState(this.state);const p=this.state.players[(c as any).playerId] as PlayerState|undefined;const beforeBounty=p?.bounties?.completed.length??0,beforeExp=!!p?.expedition?.completed;const out=original.call(this,c);if(out.ok&&p){if(c.type==='forage')event(p,'forage');else if(c.type==='craft')event(p,'craft');else if(c.type==='place')event(p,'build');else if(c.type==='rest')event(p,'rest');else if(c.type==='eat'&&c.item==='crow_milk')event(p,'drink_crow_milk');else if(c.type==='eat'&&c.item==='wild_honey')event(p,'drink_honey');if((p.bounties?.completed.length??0)>beforeBounty)event(p,'complete_bounty');if(!beforeExp&&p.expedition?.completed)event(p,'complete_expedition');persist();}return out;};proto.__awFunDispatch=true;}

function syncWorld(){const p=player();if(!activeState||!p)return;ensureRenown(p);
 for(const a of Object.values(activeState.animals??{}))if(a.dead&&!seenAnimals.has(a.id)){seenAnimals.add(a.id);if(a.killedBy==='player'){const key=('kill_'+a.kind) as RenownEvent;if(['kill_hare','kill_crow','kill_goat','kill_sheep','kill_deer','kill_bison','kill_wolf','kill_bear','kill_eagle'].includes(key))event(p,key);}}
 for(const e of Object.values(activeState.enemies))if(e.health<=0&&!seenEnemies.has(e.id)){seenEnemies.add(e.id);event(p,'kill_baddie');}
 const skills=ensureSkills(p);for(const id of SKILL_ORDER){const before=skillSnapshot[id]??skills[id]??0,after=skills[id]??0;if(after>before+.0001){event(p,'skill_gain');if(before<100&&after>=100)event(p,'grandmaster');}skillSnapshot[id]=after;}
 ensureHud();
}
function stat(label:string,value:string){return `<div class="renown-stat"><small>${label}</small><strong>${value}</strong></div>`;}
function openProfile(){const old=document.querySelector('.fun-profile');if(old){old.remove();return;}const p=player();if(!p)return;const r=ensureRenown(p),skills=ensureSkills(p),unlocked=new Set(Object.keys(r.achievements));const panel=document.createElement('section');panel.className='fun-profile';panel.innerHTML='<button class="fun-close">×</button><div class="fun-eyebrow">THE COMPLETE CHARACTER RECORD · P</div><h2></h2><div class="profile-summary"></div><div class="renown-strip"></div><div class="profile-section-title">REPUTATION</div><div class="rep-grid"></div><div class="profile-section-title">ULTIMA-STYLE SKILLS</div><div class="profile-skill-grid"></div><div class="profile-section-title">ACHIEVEMENTS</div><div class="achievement-grid"></div><p class="fun-note">Skills rise by doing. Karma measures what you do. Fame measures how loudly the March talks about it. They are intentionally not the same thing.</p>';panel.querySelector<HTMLButtonElement>('.fun-close')!.onclick=()=>panel.remove();panel.querySelector('h2')!.textContent=p.name;panel.querySelector('.profile-summary')!.textContent=`${fameTitle(r.fame)} · ${karmaTitle(r.karma)} · ${characterTitle(p)}`;panel.querySelector('.renown-strip')!.innerHTML=stat('KARMA',r.karma.toFixed(1))+stat('FAME',r.fame.toFixed(1))+stat('CROWNS',String(r.gold))+stat('ACHIEVEMENTS',`${unlocked.size}/${ACHIEVEMENTS.length}`);
 const reps=panel.querySelector('.rep-grid')!;for(const [name,value] of Object.entries(r.reputation)){const card=document.createElement('div');card.className='rep-card';card.innerHTML='<strong></strong><small></small>';card.querySelector('strong')!.textContent=name;card.querySelector('small')!.textContent=`${value.toFixed(1)} · ${reputationTitle(value)}`;reps.append(card);}const sheet=panel.querySelector('.profile-skill-grid')!;for(const id of SKILL_ORDER){const value=skills[id]??0,row=document.createElement('div');row.className='profile-skill';row.innerHTML='<strong></strong><small></small><meter min="0" max="100"></meter>';row.querySelector('strong')!.textContent=`${SKILLS[id].name} · ${value.toFixed(1)}`;row.querySelector('small')!.textContent=skillTitle(id,value);row.querySelector('meter')!.value=value;sheet.append(row);}const grid=panel.querySelector('.achievement-grid')!;for(const a of ACHIEVEMENTS){const got=unlocked.has(a.id),row=document.createElement('div');row.className='achievement-row '+(got?'unlocked':'locked');row.innerHTML='<strong></strong><small></small>';row.querySelector('strong')!.textContent=got?a.title:(a.hidden?'???':a.title);row.querySelector('small')!.textContent=got||!a.hidden?a.description:'A deeply unnecessary secret remains.';grid.append(row);}document.body.append(panel);}
function renderMarket(){const p=player();if(!p)return;const r=ensureRenown(p);let panel=document.querySelector<HTMLElement>('.fun-market');if(!panel){panel=document.createElement('section');panel.className='fun-market';document.body.append(panel);}panel.innerHTML='<button class="fun-close">×</button><div class="fun-eyebrow">ALDERBROOK MARKET · MARA PENNYMARCH</div><h2>Buy low. Sell questionable.</h2><div class="market-gold"></div><p class="fun-note">Number key = buy · Shift + number = sell · E or Esc = close. Mara pays bounty money because otherwise nobody here has a functioning economy.</p><div class="market-grid"></div>';panel.querySelector<HTMLButtonElement>('.fun-close')!.onclick=()=>panel?.remove();panel.querySelector('.market-gold')!.textContent=`Your purse · ${r.gold} crowns`;const grid=panel.querySelector('.market-grid')!;MARKET_GOODS.slice(0,9).forEach((g,i)=>{const card=document.createElement('div');card.className='market-card';card.innerHTML='<strong></strong><small></small><div class="market-actions"></div>';card.querySelector('strong')!.textContent=`${i+1} · ${ITEMS[g.item].name} ×${g.count}`;card.querySelector('small')!.textContent=`Buy ${g.buy} · Sell ${g.sell} crowns · ${g.note}`;const actions=card.querySelector('.market-actions')!;const buy=document.createElement('button'),sell=document.createElement('button');buy.textContent='Buy';sell.textContent='Sell';buy.onclick=()=>trade(i,false);sell.onclick=()=>trade(i,true);actions.append(buy,sell);grid.append(card);});}
function trade(index:number,sell:boolean){const p=player(),g=MARKET_GOODS[index];if(!activeState||!p||!g)return;const out=sell?marketSell(activeState,p,g.item):marketBuy(activeState,p,g.item);announce(out.unlocked);toastNpc('Mara Pennymarch','Trader',out.message);persist();renderMarket();}
function openMarket(){if(document.querySelector('.fun-market')){document.querySelector('.fun-market')?.remove();return;}renderMarket();}
function ensureHud(){if(!document.querySelector('.hotbar'))return;let profile=document.querySelector<HTMLButtonElement>('.fun-hud-profile');if(!profile){profile=document.createElement('button');profile.className='fun-hud-profile';profile.textContent='P · PROFILE';profile.onclick=openProfile;document.body.append(profile);}let market=document.querySelector<HTMLButtonElement>('.fun-hud-market');if(!market){market=document.createElement('button');market.className='fun-hud-market';market.textContent='E · MARA';market.onclick=openMarket;document.body.append(market);}const p=player();market.hidden=!p||Math.hypot(p.position[0]+6,p.position[2]+28)>8;}
function handleKey(e:KeyboardEvent){if((e.target as HTMLElement)?.matches('input,select,textarea'))return;const market=document.querySelector('.fun-market');if(market){if(e.code==='Escape'||e.code==='KeyE'){e.preventDefault();e.stopImmediatePropagation();market.remove();return;}if(/^Digit[1-9]$/.test(e.code)){e.preventDefault();e.stopImmediatePropagation();trade(Number(e.code.slice(-1))-1,e.shiftKey);return;}}
 if(e.code==='KeyP'&&!e.repeat){e.preventDefault();e.stopImmediatePropagation();openProfile();return;}const p=player(),pop=activeNpcPopulation();if(e.code==='KeyE'&&p&&pop){const npc=pop.nearest(p.position);if(npc){e.preventDefault();e.stopImmediatePropagation();if(npc.definition.role==='Trader')openMarket();else toastNpc(npc.definition.name,npc.definition.role,pop.line(npc,activeState?.tick??0));}}
}
function install(){const g=globalThis as any;if(g[installed])return;g[installed]=true;installAssetSanity();installNpcWorld();installAuthorityEvents();window.addEventListener('keydown',handleKey,true);window.setInterval(syncWorld,180);}
if(typeof window!=='undefined'&&typeof document!=='undefined')install();
