import * as T from 'three';
import RAPIER from '@dimforge/rapier3d-compat';
import {Assets} from './assets';
import {Landscape,height} from './landscape';
import {LocalAuthority,ITEMS,type DropState,type ItemId,type PlayerState} from './state';
import {Soundscape} from './audio';
import {gainSkill} from './skills';
type Falling={id:string;body:RAPIER.RigidBody;object:T.Object3D;age:number;half:number;scale:number};
type PhysicalDrop={body:RAPIER.RigidBody;object:T.Object3D;state:DropState};
export class Gathering {
 falling:Falling[]=[];drops=new Map<string,PhysicalDrop>();notches=new Map<string,T.Mesh>();particles:T.InstancedMesh;chipData:{position:T.Vector3;velocity:T.Vector3;life:number;scale:number}[]=[];dummy=new T.Object3D();shake=0;
 constructor(public world:T.Group,public assets:Assets,public physics:RAPIER.World,public authority:LocalAuthority,public land:Landscape,public sound:Soundscape){
  const source=assets.prop('rock_1');let geometry!:T.BufferGeometry;source.traverse(o=>{if(o instanceof T.Mesh)geometry=o.geometry;});this.particles=new T.InstancedMesh(geometry,new T.MeshStandardMaterial({color:'#b89760',roughness:1}),100);this.particles.instanceMatrix.setUsage(T.DynamicDrawUsage);this.particles.frustumCulled=false;for(let i=0;i<100;i++){this.chipData.push({position:new T.Vector3(),velocity:new T.Vector3(),life:0,scale:0});this.dummy.scale.setScalar(0);this.dummy.updateMatrix();this.particles.setMatrixAt(i,this.dummy.matrix);}world.add(this.particles);
  for(const d of Object.values(authority.state.drops))this.materializeDrop(d,false);
  for(const r of Object.values(authority.state.resources)){if(r.phase==='falling')this.fell(r.id,new T.Vector3(0,0,-1));else if(r.phase==='standing'&&r.health<(r.kind==='tree'?6:4))this.notch(r.id,new T.Vector3(0,0,1));}
 }
 burst(point:T.Vector3,stone=false){let n=0;for(const c of this.chipData){if(c.life>0)continue;c.position.copy(point);c.velocity.set((Math.random()-.5)*4,1+Math.random()*3,(Math.random()-.5)*4);c.life=.5+Math.random()*.6;c.scale=stone?.035+Math.random()*.05:.02+Math.random()*.025;if(++n===16)break;}this.shake=.1;}
 notch(id:string,normal:T.Vector3){const r=this.authority.state.resources[id];if(r.kind!=='tree')return;let mesh=this.notches.get(id);if(!mesh){const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute([-.42,0,0, .38,.04,0, .12,.13,0, -.17,.11,0],3));geo.setIndex([0,1,2,0,2,3]);geo.computeVertexNormals();mesh=new T.Mesh(geo,new T.MeshStandardMaterial({color:'#b8945c',roughness:1,side:T.DoubleSide,polygonOffset:true,polygonOffsetFactor:-2}));this.notches.set(id,mesh);this.world.add(mesh);}mesh.position.fromArray(r.position).addScaledVector(normal,.87);mesh.position.y+=1.02;mesh.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),normal);mesh.scale.set(1+(6-r.health)*.1,1+(6-r.health)*.5,1);}
 hit(player:PlayerState,id:string){const r=this.authority.state.resources[id];if(!r)return {ok:false,message:'Find a resource within reach'};const out=this.authority.dispatch({type:'harvest',playerId:player.id,resourceId:id});if(!out.ok)return out;gainSkill(player,r.kind==='tree'?'lumberjacking':'mining');const normal=new T.Vector3(player.position[0]-r.position[0],0,player.position[2]-r.position[2]).normalize();const point=new T.Vector3(...r.position).addScaledVector(normal,.85);point.y+=1.05;this.burst(point,r.kind==='rock');this.sound.impact(r.kind==='tree'?'wood':'stone');this.notch(id,normal);
  if(r.health===0){if(r.kind==='tree')this.fell(id,normal.clone().negate());else{const obj=this.land.resources.get(id);obj?.removeFromParent();this.land.resources.delete(id);const c=this.land.colliders.get(id);if(c)this.physics.removeCollider(c,true);this.land.colliders.delete(id);for(let i=0;i<6;i++)this.spawnDrop(i<4?'stone':'iron',i<4?3:2,new T.Vector3(r.position[0]+Math.cos(i)*.8,r.position[1]+.9,r.position[2]+Math.sin(i)*.8));}}
  return out;
 }
 fell(id:string,direction:T.Vector3){const object=this.land.resources.get(id);if(!object)return;const r=this.authority.state.resources[id];
  // Bias the initial physical impulse toward open ground, preventing neighboring trunks from pinning the fall upright.
  let best=-Infinity;const requested=direction.clone();for(let i=0;i<16;i++){const d=new T.Vector3(Math.sin(i*Math.PI/8),0,Math.cos(i*Math.PI/8));let clearance=12;for(const other of Object.values(this.authority.state.resources)){if(other.id===id||other.phase!=='standing'||other.kind!=='tree')continue;for(const t of [2,4,6,8])clearance=Math.min(clearance,Math.hypot(r.position[0]+d.x*t-other.position[0],r.position[2]+d.z*t-other.position[2]));}const score=clearance+Math.max(-.6,requested.dot(d))*.4;if(score>best){best=score;direction.copy(d);}}
  const col=this.land.colliders.get(id);if(col)this.physics.removeCollider(col,true);this.land.colliders.delete(id);this.notches.get(id)?.removeFromParent();this.notches.delete(id);const half=4.8*object.scale.y;const body=this.physics.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(r.position[0],r.position[1]+half,r.position[2]).setAngularDamping(.2).setLinearDamping(.15));this.physics.createCollider(RAPIER.ColliderDesc.cylinder(half,.5).setDensity(160).setFriction(.8),body);body.setAngvel({x:direction.z*.75,y:0,z:-direction.x*.75},true);const originalYaw=object.rotation.y;body.setRotation({x:0,y:Math.sin(originalYaw/2),z:0,w:Math.cos(originalYaw/2)},true);this.falling.push({id,body,object,age:0,half,scale:object.scale.y});this.land.place('stump',r.position[0],r.position[2],r.rotation,object.scale.y);this.sound.impact('wood');}
 spawnDrop(item:ItemId,count:number,point:T.Vector3){const s:DropState={id:'drop-'+this.authority.state.nextId++,item,count,position:point.toArray(),rotation:[Math.random(),Math.random()*6.28,Math.random()]};this.authority.state.drops[s.id]=s;this.materializeDrop(s,true);}
 materializeDrop(s:DropState,impulse:boolean){const log=s.item==='wood',stone=s.item==='stone'||s.item==='iron',tool=['axe','pickaxe','hammer','sword','fine_sword'].includes(s.item);const object=this.assets.prop(log?'log':stone?'rock_0':tool?s.item==='fine_sword'?'sword':s.item:'satchel');object.scale.setScalar(log?.75:stone?.19:1);const body=this.physics.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(...s.position).setLinearDamping(.55).setAngularDamping(.8));const q=new T.Quaternion().setFromEuler(new T.Euler(...s.rotation));body.setRotation(q,true);this.physics.createCollider(log?RAPIER.ColliderDesc.cylinder(.825,.26).setFriction(.9).setDensity(30):RAPIER.ColliderDesc.ball(.22).setFriction(.8),body);if(impulse)body.setLinvel({x:(Math.random()-.5)*2,y:1,z:(Math.random()-.5)*2},true);object.userData.entityId=s.id;this.world.add(object);this.drops.set(s.id,{body,object,state:s});}
 nearest(player:PlayerState){let best:DropState|undefined,dist=2.5;for(const d of Object.values(this.authority.state.drops)){const n=Math.hypot(player.position[0]-d.position[0],player.position[2]-d.position[2]);if(n<dist){dist=n;best=d;}}return best;}
 pickup(player:PlayerState){const d=this.nearest(player);if(!d)return {ok:false,message:'Move closer to a loose log or stone'};const result=this.authority.dispatch({type:'pickup',playerId:player.id,dropId:d.id});if(result.ok){const obj=this.drops.get(d.id);if(obj){obj.object.removeFromParent();this.physics.removeRigidBody(obj.body);}this.drops.delete(d.id);}return result;}
 update(dt:number){for(const f of [...this.falling]){f.age+=dt;const q=f.body.rotation(),p=f.body.translation();f.object.quaternion.set(q.x,q.y,q.z,q.w);f.object.position.set(p.x,p.y,p.z).add(new T.Vector3(0,-f.half,0).applyQuaternion(f.object.quaternion));if(f.age>3.5&&new T.Vector3(0,1,0).applyQuaternion(f.object.quaternion).y<.45){const origin=f.object.position.clone();const axis=new T.Vector3(0,1,0).applyQuaternion(f.object.quaternion);for(let i=0;i<4;i++){const at=origin.clone().addScaledVector(axis,1.5+i*1.7);at.y=Math.max(at.y,height(at.x,at.z)+.6);this.spawnDrop('wood',6,at);}f.object.removeFromParent();this.physics.removeRigidBody(f.body);this.authority.state.resources[f.id].phase='fallen';this.land.resources.delete(f.id);this.falling.splice(this.falling.indexOf(f),1);this.sound.impact('wood');}}
  for(const s of Object.values(this.authority.state.drops))if(!this.drops.has(s.id))this.materializeDrop(s,false);
  for(const d of this.drops.values()){const p=d.body.translation(),q=d.body.rotation();d.object.position.set(p.x,p.y,p.z);d.object.quaternion.set(q.x,q.y,q.z,q.w);if(d.state.item==='wood')d.object.position.add(new T.Vector3(0,-.825,0).applyQuaternion(d.object.quaternion));d.state.position=[p.x,p.y,p.z];d.state.rotation=new T.Euler().setFromQuaternion(d.object.quaternion).toArray().slice(0,3) as [number,number,number];}
  for(let i=0;i<this.chipData.length;i++){const c=this.chipData[i];c.life-=dt;if(c.life>0){c.velocity.y-=dt*12;c.position.addScaledVector(c.velocity,dt);this.dummy.position.copy(c.position);this.dummy.scale.set(c.scale*2,c.scale*.5,c.scale);this.dummy.rotation.x+=dt*4;}else this.dummy.scale.setScalar(0);this.dummy.updateMatrix();this.particles.setMatrixAt(i,this.dummy.matrix);}this.particles.instanceMatrix.needsUpdate=true;this.shake=Math.max(0,this.shake-dt*.5);
 }
 prompt(player:PlayerState){const d=this.nearest(player);return d?`E  Collect ${d.count} × ${ITEMS[d.item].name}`:'';}
}
