import * as T from 'three';
import RAPIER from '@dimforge/rapier3d-compat';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {Assets} from './assets';
import {Character} from './character';
import {Input} from './input';
import {LocalAuthority,loadWorld,saveWorld,tickVitals,type Vec3} from './state';
import {stats} from './definitions';
import {ACTION_CAMERA} from './follow-camera';
import {CellWindow,type CellCoord} from './area-cell-stream';
import {cellId,worldInt,worldRandom} from './world-address';
import {advanceIronwardToTick,ensureIronwardCapsule} from './ironward-simulation';
import {advanceDeepIronToTick} from './deep-iron-dungeon';
import {advanceRealmHistoryToTick} from './provenance-frontier';
import {CROWNROAD_VALE,DEEP_IRON_MINE,IRONWARD_BASIN,IRONWARD_CROSSING,rememberCurrentArea,requestAreaTravel} from './realm-save';
import './style.css';
import './loading-experience.css';
import './realm-travel.css';

const CELL=48,HALF=168,AREA='ironward-basin';
const SUN_OFFSET=new T.Vector3(-50,72,35);
const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML='<div id="loading"><div class="sigil">A</div><h1>IRONWARD BASIN</h1><p id="load-status">Opening the high road…</p><div class="load-line"></div></div><div id="ui"></div>';
const ui=document.querySelector<HTMLDivElement>('#ui')!;
const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.03;renderer.domElement.id='world';app.prepend(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#91adba');scene.fog=new T.FogExp2('#9baeb0',.0048);const camera=new T.PerspectiveCamera(ACTION_CAMERA.fov,innerWidth/innerHeight,.08,700);
const pmrem=new T.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;scene.environmentIntensity=.3;pmrem.dispose();scene.add(new T.HemisphereLight('#d8e8ef','#4c493d',.95));const sun=new T.DirectionalLight('#ffe0ae',3.15);sun.position.copy(SUN_OFFSET);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-42,right:42,top:42,bottom:-42,near:1,far:170});sun.shadow.camera.updateProjectionMatrix();scene.add(sun,sun.target);
const worldRoot=new T.Group();scene.add(worldRoot);const assets=new Assets(),input=new Input(renderer.domElement);const saved=loadWorld();if(!saved)throw new Error('Ironward Basin requires an existing Alderwatch realm');const authority=new LocalAuthority(saved);const player=Object.values(authority.state.players)[0];if(!player)throw new Error('Ironward Basin requires a survivor');player.areaId=IRONWARD_BASIN;
let physics:RAPIER.World,character:Character,stream:CellWindow<BasinCell>;let yaw=0,pitch=ACTION_CAMERA.pitch,distance=ACTION_CAMERA.distance,last=0,acc=0,autosave=0,frames=0,fps=0,fpsClock=0;let noticeUntil=0,notice='';
const southGate=new T.Vector3(0,0,-150),northGate=new T.Vector3(0,0,150),eastGate=new T.Vector3(150,0,0);
interface BasinCell {group:T.Group;generated:T.Object3D[];colliders:RAPIER.Collider[]}

function addr(coord:CellCoord,slot:number,tag:string){return {realmSeed:authority.state.worldSeed??197709,areaId:AREA,cellX:coord.x,cellZ:coord.z,slot,tag};}
function authored(name:string,parent:T.Group,x:number,z:number,yaw=0,scale=1){const source=assets.medieval[name];if(!source)return;const o=source.clone(true);o.position.set(x,0,z);o.rotation.y=yaw;o.scale.setScalar(scale);parent.add(o);return o;}
function obstacle(cell:BasinCell,x:number,z:number,hx:number,hz:number,hy=2){const c=physics.createCollider(RAPIER.ColliderDesc.cuboid(hx,hy,hz).setTranslation(x,hy,z));cell.colliders.push(c);}
function buildCell(coord:CellCoord):BasinCell{
 const group=new T.Group();group.name='ironward-cell-'+cellId(AREA,coord.x,coord.z);group.position.set(coord.x*CELL,0,coord.z*CELL);worldRoot.add(group);const cell:BasinCell={group,generated:[],colliders:[]};
 if(Math.abs(coord.x)>3||Math.abs(coord.z)>3)return cell;
 const ground=new T.Mesh(new T.PlaneGeometry(CELL+.3,CELL+.3),new T.MeshStandardMaterial({map:assets.textures.meadow,color:new T.Color().setHSL(.19+worldRandom(addr(coord,0,'ground-hue'))*.025,.23,.52+worldRandom(addr(coord,1,'ground-light'))*.07),roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;ground.name='stream-generated-ground';group.add(ground);cell.generated.push(ground);
 if(coord.x===0){const road=new T.Mesh(new T.PlaneGeometry(7,CELL+.5),new T.MeshStandardMaterial({map:assets.textures.soil,color:'#a69879',roughness:1}));road.rotation.x=-Math.PI/2;road.position.y=.018;road.name='stream-generated-road';group.add(road);cell.generated.push(road);}
 if(coord.z===0){const road=new T.Mesh(new T.PlaneGeometry(CELL+.5,6),new T.MeshStandardMaterial({map:assets.textures.soil,color:'#a99a7b',roughness:1}));road.rotation.x=-Math.PI/2;road.position.y=.019;road.name='stream-generated-crownroad';group.add(road);cell.generated.push(road);}
 const clutter=['barrel','hay','wood_pile','fence_wood_single','crate'] as const;const count=2+worldInt(addr(coord,2,'clutter-count'),4);for(let i=0;i<count;i++){const name=clutter[worldInt(addr(coord,i,'clutter-kind'),clutter.length)],x=(worldRandom(addr(coord,i,'clutter-x'))-.5)*38,z=(worldRandom(addr(coord,i,'clutter-z'))-.5)*38;if((Math.abs(x)<5&&coord.x===0)||(Math.abs(z)<5&&coord.z===0))continue;authored(name,group,x,z,worldRandom(addr(coord,i,'clutter-yaw'))*Math.PI*2,.55+worldRandom(addr(coord,i,'clutter-scale'))*.35);}
 const gx=coord.x*CELL,gz=coord.z*CELL;
 if(coord.x===0&&coord.z===-3){authored('watchtower',group,-11,-3,.1,.82);authored('fence_wood_ext1',group,-4,-6,0,.9);authored('fence_wood_ext2',group,4,-6,Math.PI,.9);const gate=assets.authoredFortification();gate.position.set(0,0,-6);gate.rotation.y=Math.PI;gate.scale.setScalar(1.6);group.add(gate);obstacle(cell,gx-11,gz-3,1.6,1.6,3);}
 if(coord.x===0&&coord.z===-2){authored('farm',group,-13,4,.2,.85);authored('crops',group,13,5,-.2,.9);authored('hut_a',group,-13,-11,.5,.8);obstacle(cell,gx-13,gz-11,2.6,2.6);}
 if(coord.x===0&&coord.z===-1){authored('windmill',group,14,2,-.4,.78);authored('farm',group,-14,-7,.2,.82);authored('crops',group,-14,9,0,.92);obstacle(cell,gx+14,gz+2,2.8,2.8,3);}
 if(coord.x===0&&coord.z===0){authored('towncenter',group,-12,0,.15,.78);authored('market',group,12,-2,-.15,.8);authored('well',group,8,11,0,.8);authored('hut_b',group,-12,12,.6,.78);obstacle(cell,gx-12,gz,3.8,3.8);obstacle(cell,gx+12,gz-2,3.3,2.8);const macro=ensureIronwardCapsule(authority.state).state;if(macro.danger>22||macro.regime==='besieged'){const barricade=assets.authoredFortification();barricade.position.set(0,0,10);barricade.scale.setScalar(1.25);group.add(barricade);}}
 if(coord.x===1&&coord.z===0){authored('storage',group,-9,-6,.4,.9);authored('wagon',group,8,7,-.5,.75);authored('barrel',group,-3,8,.2,.8);authored('barrel',group,-1.8,8.4,-.2,.8);obstacle(cell,gx-9,gz-6,3,3);}
 if(coord.x===-1&&coord.z===1){authored('barracks',group,8,0,-.2,.82);authored('watchtower',group,-10,-7,.15,.84);authored('wall',group,-2,12,0,.8);obstacle(cell,gx+8,gz,3.5,3);obstacle(cell,gx-10,gz-7,1.6,1.6,3);}
 if(coord.x===0&&coord.z===1){authored('hut_c',group,-13,5,.3,.82);authored('hut_d',group,13,6,-.25,.82);authored('well',group,-9,-8,0,.8);obstacle(cell,gx-13,gz+5,2.6,2.6);obstacle(cell,gx+13,gz+6,2.6,2.6);}
 if(coord.x===0&&coord.z===2){authored('towerhouse',group,-13,1,.15,.8);authored('storage',group,13,-4,-.2,.9);authored('wagon',group,10,11,.3,.75);obstacle(cell,gx-13,gz+1,3.2,3.2,3);obstacle(cell,gx+13,gz-4,3,3);}
 if(coord.x===0&&coord.z===3){const gate=assets.authoredFortification();gate.position.set(0,0,6);gate.scale.setScalar(1.8);group.add(gate);authored('watchtower',group,-12,7,.1,.9);authored('storage',group,12,3,-.2,.8);obstacle(cell,gx-12,gz+7,1.7,1.7,3);}
 if(coord.x===3&&coord.z===0){const gate=assets.authoredFortification();gate.position.set(6,0,0);gate.rotation.y=-Math.PI/2;gate.scale.setScalar(1.75);group.add(gate);authored('watchtower',group,-8,10,-.1,.88);authored('wagon',group,-8,-10,.3,.78);obstacle(cell,gx-8,gz+10,1.7,1.7,3);}
 return cell;
}
function disposeCell(handle:{value:BasinCell}){const cell=handle.value;for(const c of cell.colliders)physics.removeCollider(c,true);for(const o of cell.generated){if(o instanceof T.Mesh){o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats)m.dispose();}}cell.group.removeFromParent();}
function buildBasin(){physics=new RAPIER.World({x:0,y:-9.81,z:0});physics.createCollider(RAPIER.ColliderDesc.cuboid(HALF,.12,HALF).setTranslation(0,-.12,0));for(const [x,z,hx,hz] of [[-HALF,0,.35,HALF],[HALF,0,.35,HALF],[0,-HALF,HALF,.35],[0,HALF,HALF,.35]] as const)physics.createCollider(RAPIER.ColliderDesc.cuboid(hx,3,hz).setTranslation(x,3,z));stream=new CellWindow({cellSize:CELL,radius:1,create:buildCell,dispose:disposeCell});character=new Character(assets,physics,player,worldRoot);character.getTick=()=>authority.state.tick;character.onActionRequest=action=>authority.dispatch({type:'combat_action',playerId:player.id,action}).ok;character.onImpact=()=>{};stream.update(player.position[0],player.position[2]);input.active=true;input.captureCamera=true;}
function snapshot(){player.position=character.root.position.toArray() as Vec3;player.yaw=character.root.rotation.y;rememberCurrentArea(player);}
function save(){snapshot();advanceIronwardToTick(authority.state);advanceDeepIronToTick(authority.state);advanceRealmHistoryToTick(authority.state);saveWorld(authority.state);}
function showTransition(title:string,status:string){const el=document.createElement('div');el.className='realm-transition-loader';el.innerHTML='<div class="realm-loader-card"><div class="sigil"><span>A</span></div><small>IRONWARD BASIN</small><h2></h2><div class="realm-loader-status"></div><div class="realm-loader-track"><i></i></div></div>';el.querySelector('h2')!.textContent=title;el.querySelector<HTMLElement>('.realm-loader-status')!.textContent=status;document.body.append(el);}
function travelCrossing(){save();requestAreaTravel(IRONWARD_CROSSING);input.active=false;showTransition('LEAVING IRONWARD BASIN','Following the south road back to the Crossing…');requestAnimationFrame(()=>requestAnimationFrame(()=>location.reload()));}
function travelMine(){save();requestAreaTravel(DEEP_IRON_MINE);input.active=false;showTransition('DESCENDING INTO DEEP IRON','Lantern light disappears beneath the Ironvein gate…');requestAnimationFrame(()=>requestAnimationFrame(()=>location.reload()));}
function travelCrownroad(){save();requestAreaTravel(CROWNROAD_VALE);input.active=false;showTransition('TAKING THE KING’S ROAD','Gatewatch falls behind as the road opens into Crownroad Vale…');requestAnimationFrame(()=>requestAnimationFrame(()=>location.reload()));}
function hud(){ui.innerHTML='<div class="compass">N · IRONWARD BASIN</div><div class="location"><small>IRONWARD</small><span>South Gate Road</span></div><div class="quest"><small>THE HIGH BASIN</small><p>North reaches Deep Iron. The new eastern kingroad reaches Crownroad Vale.</p></div><div class="vitals"><div class="health"><i></i><span></span></div><div class="stamina"><i></i></div></div><div class="interaction" hidden></div><div class="controls">WASD Move · Shift Sprint · Space Dodge · Mouse Look · E at realm gates</div><output id="performance"></output><aside id="ironward-state"></aside>';}
function areaName(p:T.Vector3){if(p.z<-105)return 'South Gate Road';if(p.z<-35)return 'Lower Farms';if(Math.abs(p.z)<32&&p.x>105)return 'Eastern Kingroad Gate';if(Math.abs(p.z)<32&&Math.abs(p.x)<45)return 'Gatewatch';if(p.x>45&&Math.abs(p.z)<55)return 'Ironward Quarry';if(p.x<-45&&p.z>20)return 'Marcher Barracks';if(p.z>105)return 'Ironvein Mine Road';return 'High Basin';}
function updateHud(now:number){const max=stats(player),health=ui.querySelector<HTMLElement>('.health i'),stamina=ui.querySelector<HTMLElement>('.stamina i'),label=ui.querySelector<HTMLElement>('.health span')!;if(health)health.style.width=player.health/max.health*100+'%';if(stamina)stamina.style.width=player.stamina/max.stamina*100+'%';label.textContent=Math.ceil(player.health)+' / '+max.health;const p=character.root.position,south=p.distanceTo(southGate),north=p.distanceTo(northGate),east=p.distanceTo(eastGate),prompt=ui.querySelector<HTMLElement>('.interaction')!;prompt.hidden=south>4&&north>5&&east>5;prompt.textContent=south<=4?'E · Return to Ironward Crossing':north<=5?'E · Descend into Deep Iron Mine':'E · Follow the King’s Road into Crownroad Vale';const interact=input.take('KeyE');if(interact&&south<=4){travelCrossing();return;}if(interact&&north<=5){travelMine();return;}if(interact&&east<=5){travelCrownroad();return;}ui.querySelector<HTMLElement>('.location span')!.textContent=areaName(p);const macro=ensureIronwardCapsule(authority.state);ui.querySelector<HTMLElement>('#ironward-state')!.textContent=`GATEWATCH · ${macro.state.regime.toUpperCase()} · POP ${macro.state.population} · FOOD ${macro.state.food} · IRON ${macro.state.iron} · GUARDS ${macro.state.guards} · DANGER ${macro.state.danger} · ${stream.active.size}/${stream.maxActive} CELLS`;ui.querySelector<HTMLElement>('#performance')!.textContent=`${fps} FPS · ${renderer.info.render.calls} draws`;const quest=ui.querySelector<HTMLElement>('.quest p')!;quest.textContent=now<noticeUntil?notice:(macro.recentEvents.at(-1)??'North reaches Deep Iron. The eastern road now reaches Crownroad Vale.');}
function frame(now:number){const frameDt=last?(now-last)/1000:.016,dt=Math.min(frameDt,.05);last=now;frames++;fpsClock+=frameDt;if(fpsClock>1){fps=Math.round(frames/fpsClock);frames=0;fpsClock=0;}yaw+=input.dx*.003;pitch=T.MathUtils.clamp(pitch+input.dy*.002,ACTION_CAMERA.minPitch,ACTION_CAMERA.maxPitch);distance=T.MathUtils.clamp(distance+input.wheel*.85,ACTION_CAMERA.minDistance,ACTION_CAMERA.maxDistance);acc+=dt;while(acc>=1/60){character.preStep(1/60,input,yaw,true);physics.step();character.postStep(1/60);tickVitals(authority.state,1/60);authority.state.tick++;acc-=1/60;}stream.update(character.root.position.x,character.root.position.z);autosave+=dt;if(autosave>10){save();autosave=0;}updateHud(now);const p=character.root.position,aim=p.clone().add(new T.Vector3(0,1.25,0));camera.position.copy(p).add(new T.Vector3(-Math.sin(yaw)*Math.cos(pitch)*distance,1.35+Math.sin(pitch)*distance,Math.cos(yaw)*Math.cos(pitch)*distance));const rayDir=camera.position.clone().sub(aim),rayLength=rayDir.length();rayDir.normalize();const hit=physics.castRay(new RAPIER.Ray(aim,rayDir),rayLength,true,undefined,undefined,character.collider,character.body);if(hit&&hit.timeOfImpact<rayLength)camera.position.copy(aim).addScaledVector(rayDir,Math.max(.7,hit.timeOfImpact-.25));camera.lookAt(aim);sun.position.copy(p).add(SUN_OFFSET);sun.target.position.copy(p);sun.target.updateMatrixWorld();renderer.render(scene,camera);input.endFrame();requestAnimationFrame(frame);}
async function init(){await RAPIER.init();await assets.load(message=>document.querySelector('#load-status')!.textContent=message);const catchup=advanceIronwardToTick(authority.state);advanceDeepIronToTick(authority.state);advanceRealmHistoryToTick(authority.state);if(catchup.days){notice=`Gatewatch lived ${catchup.days} days while you were away · ${catchup.eventCount} events compiled`;noticeUntil=performance.now()+7000;}buildBasin();hud();document.querySelector('#loading')!.remove();saveWorld(authority.state);requestAnimationFrame(frame);}
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});window.addEventListener('pagehide',()=>{if(character)save();stream?.dispose();});init().catch(error=>{console.error(error);document.querySelector('#load-status')!.textContent='Ironward Basin could not load: '+(error.message??error);});
