import './loading-experience.css';

export const REALM_ENTRY_LABELS=new Set(['CONTINUE','ENTER THE MARCH','START A NEW REALM','RETURN NEAR HOME','RETURN TO ALDERBROOK ROAD']);
const messages=['Reading the old road…','Settling terrain and village geometry…','Waking wildlife and predator state…','Calling the townsfolk back from lunch…','Checking that no sheep has become a mandatory quest…'];
let active:HTMLElement|undefined,timer=0,bypass=false;
function createLoader(title='ENTERING THE MARCH'){active?.remove();const el=document.createElement('div');el.className='realm-transition-loader';el.innerHTML='<div class="realm-loader-card"><div class="sigil"><span>A</span></div><small>THE FAR MARCH</small><h2></h2><div class="realm-loader-status"></div><div class="realm-loader-track"><i></i></div></div>';el.querySelector('h2')!.textContent=title;document.body.append(el);active=el;let i=0;const status=el.querySelector<HTMLElement>('.realm-loader-status')!;status.textContent=messages[0];clearInterval(timer);timer=window.setInterval(()=>{status.textContent=messages[++i%messages.length];},520);return el;}
function hideLoader(delay=80){const el=active;if(!el)return;clearInterval(timer);window.setTimeout(()=>{requestAnimationFrame(()=>requestAnimationFrame(()=>{el.classList.add('leaving');setTimeout(()=>el.remove(),400);if(active===el)active=undefined;}));},delay);}
function waitForGameplay(){const started=performance.now();const check=()=>{if(document.querySelector('.hotbar')||performance.now()-started>8000){hideLoader(120);return;}requestAnimationFrame(check);};requestAnimationFrame(check);}
function installEntryGate(){document.addEventListener('click',e=>{if(bypass)return;const button=(e.target as Element|null)?.closest('button');if(!(button instanceof HTMLButtonElement))return;const text=(button.textContent??'').trim().toUpperCase();if(!REALM_ENTRY_LABELS.has(text))return;e.preventDefault();e.stopImmediatePropagation();createLoader(text.includes('RETURN')?'RETURNING TO THE MARCH':'ENTERING THE MARCH');requestAnimationFrame(()=>requestAnimationFrame(()=>{bypass=true;button.click();bypass=false;waitForGameplay();}));},true);}
function installBootCurtain(){if(!document.querySelector('#loading'))return;createLoader('PREPARING ALDERWATCH');const started=performance.now();const check=()=>{if(!document.querySelector('#loading')&&document.querySelector('.title-panel')&&performance.now()-started>450){hideLoader(140);return;}requestAnimationFrame(check);};requestAnimationFrame(check);}
if(typeof document!=='undefined'){installBootCurtain();installEntryGate();}
