import * as T from 'three';
import RAPIER from '@dimforge/rapier3d-compat';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {Assets} from './assets';
import {Landscape,height} from './landscape';
import {Character} from './character';
import {Input} from './input';
import {Soundscape} from './audio';
import {LocalAuthority,makePlayer,seedState,loadWorld as loadSavedWorld,saveWorld as persistWorld,tickVitals,ITEMS,type Archetype,type ItemId,type Command,type WorldState} from './state';
import './style.css';
import {registerGameTools} from './webmcp';
import {Gathering} from './gathering';
import {Building} from './building';
import {GamePanels} from './game-panels';
import {stats,BUILDS,type BuildKind} from './definitions';
import {distance} from './economy';
import {Combat} from './combat';
import {Nature,forageAvailable} from './nature';
import {FollowCamera,ACTION_CAMERA} from './follow-camera';
const followCamera=new FollowCamera();
import {houseFixture,expeditionFixture,natureFixture,frontierFixture} from './development-fixtures';
import './minimap.css';
import {frontierObjective,regionAt} from './worldgen';
import {MiniMap} from './minimap';
import {bountyObjective} from './bounties';
import {expeditionObjective,expeditionProgress,bearing} from './expedition';

const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML='<div id="loading"><div class="sigil">A</div><h1>ALDERWATCH</h1><p id="load-status">Following the old road…</p><div class="load-line"></div></div><div id="ui"></div>';
const ui=document.querySelector<HTMLDivElement>('#ui')!;
const sound=new Soundscape();const authority=new LocalAuthority();
const rehearsalKind=import.meta.env.DEV?new URLSearchParams(location.search).get('rehearsal'):null;
const rehearsal=rehearsalKind==='combat'||rehearsalKind==='house'||rehearsalKind==='expedition'||rehearsalKind==='nature'||rehearsalKind==='frontier';
function saveWorld(state:WorldState){if(!rehearsal)persistWorld(state);}
function loadWorld(){return rehearsal?null:loadSavedWorld();}
function combatFixture(){const w=seedState(),p=makePlayer('Warden');p.position=[32,height(32,-17)+.02,-17];p.yaw=2.55;p.health=110;p.equipped='sword';p.inventory.push({id:'rehearsal-sword',item:'sword',count:1,quality:1});w.players[p.id]=p;return w;}
let mode:'title'|'creation'|'play'|'inventory'|'settings'|'credits'|'online'|'craft'|'storage'|'build'|'fallen'|'rehearsal-paused'|'journal'='title';let selected:Archetype='Warden';let cameraYaw=0,cameraPitch=ACTION_CAMERA.pitch,cameraDistance=ACTION_CAMERA.distance;let elapsed=0,accumulator=0,intro=0,autosave=0,toastUntil=0;let frames=0,fps=0,fpsTime=0;
const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.04;renderer.domElement.id='world';app.prepend(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#99bdd1');scene.fog=new T.FogExp2('#a2b8bf',.0034);const camera=new T.PerspectiveCamera(48,innerWidth/innerHeight,.08,650);
const pmrem=new T.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;scene.environmentIntensity=.30;pmrem.dispose();
const sky=new T.Mesh(new T.SphereGeometry(490,32,16),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,vertexShader:'varying vec3 vSky; void main(){vSky=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'varying vec3 vSky; float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);} float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+1.0),f.x),f.y);} void main(){vec3 d=normalize(vSky);float elevation=smoothstep(-.1,.7,d.y);vec3 color=mix(vec3(.46,.64,.74),vec3(.10,.34,.58),elevation);vec2 uv=d.xz/(d.y+.3)*2.0;float n=noise(uv)*.5+noise(uv*2.0)*.25+noise(uv*4.0)*.125;float cloud=smoothstep(.48,.7,n)*smoothstep(.06,.3,d.y);color=mix(color,vec3(.88,.91,.91),cloud*.75);gl_FragColor=vec4(color,1.0); #include <colorspace_fragment> }'.replace('#include <colorspace_fragment>','\n#include <colorspace_fragment>\n')}));const sunPos=new T.Vector3(-.55,.8,.15);scene.add(sky);
sunPos.set(-.65,.64,.28);renderer.shadowMap.type=T.PCFSoftShadowMap;
scene.add(new T.HemisphereLight('#c8def4','#4b4335',.78));const sun=new T.DirectionalLight('#ffe3b8',3.2);sun.position.copy(sunPos).multiplyScalar(60);sun.castShadow=true;sun.shadow.mapSize.set(4096,4096);Object.assign(sun.shadow.camera,{left:-32,right:32,top:32,bottom:-32,near:1,far:150});sun.shadow.camera.updateProjectionMatrix();sun.shadow.bias=-.00006;sun.shadow.normalBias=.025;scene.add(sun,sun.target);
const worldRoot=new T.Group();scene.add(worldRoot);
// The connected authored highlands extend beyond the old detached ridge strips.
sky.scale.setScalar(3);camera.far=1800;camera.updateProjectionMatrix();
const minimap=new MiniMap();const assets=new Assets();let character:Character,landscape:Landscape,physics:RAPIER.World,gathering:Gathering,building:Building,combat:Combat,nature:Nature;const input=new Input(renderer.domElement);
const panels=new GamePanels(ui,authority,()=>character.state,()=>building,resume,command);
function command(c:Command){const out=authority.dispatch(c);if(out.ok){if(character.equipped!==character.state.equipped)character.equip(character.state.equipped);saveWorld(authority.state);}toast(out.message);return out;}
function resume(){if(character.state.health<=0){fallen();return;}mode='play';building.setActive(false);input.clear();input.captureCamera=true;input.active=true;hud();}
function setRehearsalPause(paused:boolean){if(!rehearsal)return;input.clear();input.active=!paused;mode=paused?'rehearsal-paused':'play';}
function fallen(){mode='fallen';building.setActive(false);input.clear();input.active=false;saveWorld(authority.state);ui.innerHTML='<section class="menu-card fallen"><div class="eyebrow">THE MARCH REMEMBERS</div><h2>You have fallen</h2><p>Your weapons and provisions are safe. Gathered materials remain where you fell.</p><div class="return-slot"></div></section>';$('.return-slot').append(button(character.state.home?'Return near home':'Return to Alderbrook Road',()=>{const out=authority.dispatch({type:'respawn',playerId:character.state.id});if(out.ok){buildRealm();resume();saveWorld(authority.state);toast(out.message);}},'primary'));}
function journal(){mode='journal';building.setActive(false);input.clear();input.active=false;panels.journal();}
function quickFood(){const p=character.state,item=(['woodland_broth','hearty_stew','grilled_venison','berries'] as ItemId[]).find(id=>p.inventory.some(s=>s.item===id&&s.count>0)&&!p.buffs.some(b=>b.id===id&&b.remaining>60))??(['woodland_broth','hearty_stew','grilled_venison','berries'] as ItemId[]).find(id=>p.inventory.some(s=>s.item===id&&s.count>0));if(item)command({type:'eat',playerId:p.id,item});else toast('No food in your pack. Cook at a campfire · C.');}
function craft(stationId?:string){mode='craft';input.clear();input.active=false;panels.crafting(stationId);}
function startBuild(){mode='build';input.clear();input.captureCamera=false;input.active=true;building.setActive(true);hud();panels.build();}
function interact(){const p=character.state;if(gathering.nearest(p)){toast(gathering.pickup(p).message);return;}const flax=Object.values(authority.state.forage).find(s=>forageAvailable(s,authority.state.tick)&&(!s.id.startsWith('nature-')||nature.plants.get(s.id)?.visible)&&distance(s.position,p.position)<2.2);if(flax){command({type:'forage',playerId:p.id,forageId:flax.id});character.play('interact',true);character.locked=.5;return;}const door=building.nearest(p,'doorway');if(door){command({type:'toggle_door',playerId:p.id,structureId:door.id});return;}const box=Object.values(authority.state.containers).find(s=>distance(s.position,p.position)<2.5);if(box?.id.startsWith('bounty-cache-')){command({type:'bounty',playerId:p.id,action:'claim',bountyId:box.id.slice('bounty-cache-'.length)});return;}if(box?.id.startsWith('expedition-cache-')){command({type:'expedition',playerId:p.id,action:'recover',siteId:box.id.slice('expedition-cache-'.length)});return;}if(box){const out=command({type:'open_container',playerId:p.id,containerId:box.id});if(out.ok){mode='storage';input.clear();input.active=false;panels.storage(box.id);}return;}const station=panels.nearestStation();if(station?.id==='alderbrook-bench'&&expeditionProgress(p).accepted&&!expeditionProgress(p).completed&&expeditionProgress(p).recovered.length===3){journal();return;}if(station){craft(station.id);return;}toast('Move beside a station, chest, door or loose supplies');}
const $=(s:string)=>ui.querySelector<HTMLElement>(s)!;
const button=(label:string,action:()=>void,cls='')=>{const b=document.createElement('button');b.textContent=label;b.className=cls;b.onclick=()=>{sound.start();action();};return b;};
function toast(message:string){let el=ui.querySelector('#toast');if(!el){el=document.createElement('div');el.id='toast';ui.append(el);}el.textContent=message;toastUntil=elapsed+3.5;}
function title(){mode='title';input.active=false;ui.innerHTML='<section class="title-panel"><div class="eyebrow">THE FAR MARCH</div><h1>ALDERWATCH</h1><div class="rule"></div><nav aria-label="Main menu"></nav></section><div class="version">Alderwatch · Frontier realm</div><div class="corner-note">An old road. A new beginning.</div>';const nav=$('nav');nav.append(button('New game',creation,'primary'));const cont=button('Continue',()=>begin(true));cont.disabled=!loadWorld();nav.append(cont,button('Multiplayer / Online',()=>panel('online')),button('Settings',()=>panel('settings')),button('Credits',()=>panel('credits')));}
const ARCHETYPES:Record<Archetype,string>={Warden:'Hold your ground. Build something worth defending.',Hunter:'Travel light. Read the wild. Strike with purpose.',Reaver:'Meet danger head-on. Win your place in the March.',Artisan:'A steady hand turns wilderness into a home.'};
function creation(){mode='creation';character.root.position.set(0,height(0,18),18);character.root.rotation.y=2.9;ui.innerHTML='<section class="creation-panel"><button class="back">← Back</button><div class="eyebrow">A PLACE IN THE MARCH</div><h2>Your story begins here</h2><p class="muted">Choose a starting specialty. Your path remains your own.</p><div class="archetypes"></div><p id="archetype-note"></p><div class="customization"><label>Hair <select id="hair"><option value="#493120">Chestnut</option><option value="#1b1917">Raven</option><option value="#a18754">Flaxen</option><option value="#a5a19a">Silver</option></select></label><label>Skin tone <select id="skin"><option value="#ffffff">Fair</option><option value="#cda783">Warm</option><option value="#9e7355">Deep</option></select></label><label>Headwear <select id="hood"><option value="no">Unhooded</option><option value="yes">Ranger’s hood</option></select></label></div><div class="begin-slot"></div></section><div class="character-caption"><span id="class-name">WARDEN</span><small>Survivor of the old kingdoms</small></div>';
 $('.back').onclick=title;for(const name of Object.keys(ARCHETYPES) as Archetype[]){const b=button(name,()=>{selected=name;for(const el of ui.querySelectorAll('.archetypes button'))el.classList.toggle('selected',el.textContent===name);$('#archetype-note').textContent=ARCHETYPES[name];$('#class-name').textContent=name.toUpperCase();});b.classList.toggle('selected',name===selected);$('.archetypes').append(b);}$('#archetype-note').textContent=ARCHETYPES[selected];$('.begin-slot').append(button('Enter the March',()=>begin(false),'primary'));
 for(const id of ['hair','skin','hood'])$('#'+id).onchange=()=>{character.state.hair=(ui.querySelector('#hair') as HTMLSelectElement).value;character.state.skin=(ui.querySelector('#skin') as HTMLSelectElement).value;character.state.hood=(ui.querySelector('#hood') as HTMLSelectElement).value==='yes';character.customize();};
}
function panel(which:'settings'|'credits'|'online'){mode=which;ui.innerHTML='<section class="menu-card"><button class="back">← Back</button><div id="panel-content"></div></section>';$('.back').onclick=title;const content=$('#panel-content');if(which==='settings'){content.innerHTML='<h2>Settings</h2><label class="setting">Sound volume<input id="volume" type="range" min="0" max="1" step=".05" value="'+sound.volume+'"></label><p class="muted">WASD to move · Shift to sprint · Space to dodge<br>Move mouse to look · Right click to guard · Scroll to change distance<br>1–4 equip · Left click to use · E interact<br>Tab inventory · Esc return to menu</p>';$('#volume').oninput=e=>{sound.setVolume(Number((e.target as HTMLInputElement).value));localStorage.setItem('alderwatch.settings',JSON.stringify({volume:sound.volume}));};}else if(which==='credits')content.innerHTML='<h2>Credits</h2><p>ALDERWATCH — The Far March</p><p>Original environment kit and equipment authored in Blender. Original concept art and surface textures created for Alderwatch.</p><p>Human base, Ranger outfit and source animation library: Quaternius, CC0.</p><p class="muted">Built with Three.js and Rapier.</p>';else content.innerHTML='<h2>Realms are coming online</h2><p>This build is a local, single-player realm.</p><ul><li>Official Realm</li><li>Private Realm</li><li>LAN / Host Game</li><li>Join by Code</li></ul><p class="muted">Online connections are not available yet.</p>';}
function begin(saved:boolean){const look={hair:character.state.hair,skin:character.state.skin,hood:character.state.hood};const prior=saved?loadWorld():null;if(!saved&&loadWorld()){ui.innerHTML='<section class="menu-card"><h2>Begin a new story?</h2><p>Your current realm will be kept as a backup. Continue from the title to keep playing it.</p><div class="new-actions"></div></section>';$('.new-actions').append(button('Keep my realm',title),button('Start a new realm',()=>{localStorage.setItem('alderwatch.realm.backup',localStorage.getItem('alderwatch.realm.v1')!);localStorage.removeItem('alderwatch.realm.v1');begin(false);},'primary'));return;}authority.state=prior??seedState();if(!prior){authority.state.worldSeed=crypto.getRandomValues(new Uint32Array(1))[0];const p=Object.assign(makePlayer(selected),look);p.health=stats(p).health;p.stamina=stats(p).stamina;p.position=[0,height(0,18)+.03,18];authority.state.players[p.id]=p;}buildRealm();cameraYaw=0;mode='play';input.clear();input.active=true;intro=saved?0:3;hud();saveWorld(authority.state);}
function buildRealm(){landscape?.frontier?.dispose();worldRoot.clear();if(physics)physics.free();physics=new RAPIER.World({x:0,y:-9.81,z:0});landscape=new Landscape(worldRoot,assets,physics,authority.state);const p=Object.values(authority.state.players)[0];character=new Character(assets,physics,p,worldRoot);character.getTick=()=>authority.state.tick;character.onActionRequest=action=>authority.dispatch({type:'combat_action',playerId:p.id,action}).ok;gathering=new Gathering(worldRoot,assets,physics,authority,landscape,sound);building=new Building(worldRoot,assets,physics,authority);combat=new Combat(worldRoot,assets,physics,authority,character,sound);nature=new Nature(worldRoot,assets,authority.state,landscape);followCamera.reset();combat.onNotice=toast;character.onImpact=impact;character.onStep=()=>sound.impact('step');character.onAttackStart=()=>{const e=combat.target(2.65),r=authority.state.resources[currentTarget],target=e??r;if(target&&distance(target.position,p.position)<2.5)character.root.rotation.y=Math.atan2(target.position[0]-p.position[0],target.position[2]-p.position[2]);if(e||p.equipped?.includes('sword'))sound.combat('swing');};character.onWindupAim=dt=>{const e=combat.target(2.8);if(!e)return;const angle=Math.atan2(e.position[0]-p.position[0],e.position[2]-p.position[2]),delta=T.MathUtils.euclideanModulo(angle-character.root.rotation.y+Math.PI,Math.PI*2)-Math.PI;character.root.rotation.y+=T.MathUtils.clamp(delta,-dt*8,dt*8);};accumulator=0;}
function hud(){ui.innerHTML='<div class="compass">W <span>· · · · · ·</span> N <span>· · · · · ·</span> E</div><div class="location"><small>THE FAR MARCH</small><span>Alderbrook Road</span></div><div class="quest"><small>A FOOTHOLD</small><p>Gather timber from a mature oak</p></div><div class="vitals"><div class="health"><i></i><span></span></div><div class="stamina"><i></i></div></div><div class="hotbar"></div><div class="interaction" hidden></div><div class="controls">WASD Move <b>·</b> Shift Sprint <b>·</b> Space Dodge <b>·</b> E Interact <b>·</b> Tab Pack</div><output id="performance"></output>';minimap.mount(ui);['axe','pickaxe','sword','hammer'].forEach((name,i)=>{$('.hotbar').append(button(`${i+1}  ${ITEMS[name as ItemId].name}`,()=>equip(name as ItemId)));});}
function equip(item:ItemId){if(item==='sword'&&character.state.inventory.some(s=>s.item==='fine_sword'))item='fine_sword';const r=authority.dispatch({type:'equip',playerId:character.state.id,item});if(r.ok)character.equip(item);toast(r.message);}
function inventory(){mode='inventory';input.clear();input.active=false;panels.inventory();}
let currentTarget='';
function updateHud(){const p=character.state,max=stats(p);const h=$('.health i'),s=$('.stamina i');if(h)h.style.width=p.health/max.health*100+'%';if(s)s.style.width=p.stamina/max.stamina*100+'%';if($('.health span'))$('.health span').textContent=Math.ceil(p.health)+' / '+max.health;for(const [i,b] of Array.from(ui.querySelectorAll('.hotbar button')).entries()){b.classList.toggle('selected',['axe','pickaxe',p.equipped==='fine_sword'?'fine_sword':'sword','hammer'][i]===p.equipped);if(i===2)b.textContent='3  '+ITEMS[p.inventory.some(s=>s.item==='fine_sword')?'fine_sword':'sword'].name;}
 let nearest=Infinity;currentTarget='';for(const [id,r] of Object.entries(authority.state.resources)){if(r.phase!=='standing')continue;const d=distance(r.position,p.position);if(d<nearest&&d<2.6){nearest=d;currentTarget=id;}}
 const prompt=$('.interaction'),pickup=gathering.prompt(p),station=panels.nearestStation(),door=building.nearest(p,'doorway'),flax=Object.values(authority.state.forage).find(s=>forageAvailable(s,authority.state.tick)&&(!s.id.startsWith('nature-')||nature.plants.get(s.id)?.visible)&&distance(s.position,p.position)<2.2),box=Object.values(authority.state.containers).find(s=>distance(s.position,p.position)<2.5);const r=authority.state.resources[currentTarget];if(prompt){const text=pickup||(flax?'E Gather '+ITEMS[flax.kind??'fiber'].name:door?'E '+(door.doorOpen?'Close':'Open')+' oak door':box?'E Open '+box.name:station?'E Use '+station.name:r?`${r.kind==='tree'?'Mature oak':'Iron-bearing rock'} · ${r.health} hits · Left click ${r.kind==='tree'?'axe':'pickaxe'}`:'');prompt.hidden=!text||mode==='build';prompt.textContent=text;}
 const objective=frontierObjective(authority.state,p)??bountyObjective(authority.state,p)??expeditionObjective(authority.state,p);minimap.update(authority.state,p,cameraYaw,objective.position,elapsed);$('.quest small').textContent=objective.title;$('.quest p').textContent=objective.text;let route=$('.quest .route-bearing');if(!route){route=document.createElement('div');route.className='route-bearing';$('.quest').append(route);}route.textContent=(objective.position?bearing(p.position,objective.position)+' · ':'')+'J · Journal';const heading=((cameraYaw*180/Math.PI)%360+360)%360;$('.compass').textContent=['N','NE','E','SE','S','SW','W','NW'][Math.round(heading/45)%8]+' · '+Math.round(heading)+'°';const nearbySite=Object.values(authority.state.expeditionSites??{}).find(site=>distance(site.position,p.position)<13);$('.location span').textContent=building.sheltered(p)?'Home · Sheltered':nearbySite?.name??(Math.abs(p.position[0])<20&&p.position[2]<-24?'Alderbrook':regionAt(p.position[0],p.position[2]));$('.controls').textContent='Hold LMB Attack · Mouse Look · WASD Move · Shift Sprint · Space Dodge · E Interact · Tab Pack · J Journal · Q Food · B Build · F Heavy · RMB Guard';$('#performance').textContent=`${fps} FPS · ${renderer.info.render.calls} draws`;let buffs=$('.buffs');if(!buffs){buffs=document.createElement('div');buffs.className='buffs';ui.append(buffs);}buffs.textContent=p.buffs.map(b=>`${ITEMS[b.id as ItemId]?.name??b.id} ${Math.ceil(b.remaining/60)}m`).join(' · ');
}
function impact(){if(combat.target()||character.state.equipped?.includes('sword')){combat.playerStrike();return;}if(!currentTarget)return;toast(gathering.hit(character.state,currentTarget).message);}
function updateCombatHud(){let bar=$('#combat-target');const e=combat.nearest();if(!bar){bar=document.createElement('div');bar.id='combat-target';ui.append(bar);}bar.hidden=!e;if(e){bar.dataset.phase=e.phase;bar.innerHTML='<strong>'+e.name+'</strong><div><i style="width:'+e.health/e.maxHealth*100+'%"></i></div><small>'+({windup:e.combat?.kind==='heavy'?'HEAVY CUT · dodge, then counter':'Incoming strike · guard or dodge',recover:'An opening',stagger:'Staggered',alert:'You have been seen',approach:'Closing in',circle:'Watching your guard',return:'Returning to camp',patrol:'Camp sentry',dead:''}[e.phase])+'</small>';}}
function startRehearsal(){authority.state=rehearsalKind==='frontier'?frontierFixture():rehearsalKind==='house'?houseFixture():rehearsalKind==='expedition'?expeditionFixture():rehearsalKind==='nature'?natureFixture():combatFixture();buildRealm();mode='play';input.clear();input.active=true;cameraYaw=rehearsalKind==='house'?0:.59;hud();const label=document.createElement('aside');label.id='rehearsal-label';label.innerHTML='<span>'+(rehearsalKind==='house'?'HOUSE':rehearsalKind==='expedition'?'EXPEDITION':rehearsalKind==='nature'?'NATURE':rehearsalKind==='frontier'?'FRONTIER':'COMBAT')+' REHEARSAL · NOT SAVED</span>';label.append(button('Pause / resume',()=>setRehearsalPause(mode!=='rehearsal-paused')),button('Restart rehearsal',startRehearsal),button('Back to saved realm',()=>location.assign('/')));app.querySelector('#rehearsal-label')?.remove();app.append(label);}
registerGameTools([{name:'read_combat',description:'Read real enemy AI, health, animation, hand sockets and the last 30 resolved strikes. No mutations.',annotations:{readOnlyHint:true},inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>({tick:authority.state.tick,player:structuredClone(character.state),enemies:combat.read(),events:structuredClone(combat.events)})},{name:'combat_input',description:'Perform one ordinary attack, held right-mouse guard or Space dodge in the live game, for up to two seconds. Does not move, grant equipment or force hits. Optional yaw rotates the camera as normal camera input.',inputSchema:{type:'object',properties:{action:{type:'string',enum:['attack','heavy','guard','dodge']},durationMs:{type:'number',minimum:1,maximum:2000},yaw:{type:'number',minimum:-6.29,maximum:6.29},pauseAfter:{type:'boolean',description:'Only in the isolated rehearsal: freeze the frame after this input for visual inspection'}},required:['action','durationMs'],additionalProperties:false},execute:async raw=>{const c=raw as {action:string;durationMs:number;yaw?:number;pauseAfter?:boolean};if(mode!=='play'||!['attack','heavy','guard','dodge'].includes(c.action)||!Number.isFinite(c.durationMs)||c.durationMs<1||c.durationMs>2000)throw new Error('Invalid combat control or not in gameplay');input.clear();if(c.yaw!==undefined){if(!Number.isFinite(c.yaw))throw new Error('Invalid camera yaw');cameraYaw=T.MathUtils.clamp(c.yaw,-6.29,6.29);}if(c.action==='guard')input.secondary=true;else input.pressed.add(c.action==='attack'?'Attack':c.action==='heavy'?'KeyF':'Space');try{const start=performance.now();await new Promise<void>(resolve=>{const check=()=>performance.now()-start>=c.durationMs?resolve():requestAnimationFrame(check);requestAnimationFrame(check);});if(c.pauseAfter&&rehearsal)setRehearsalPause(true);return {player:readGame(),enemies:combat.read(),events:structuredClone(combat.events)};}finally{input.clear();}}}]);
async function init(){await RAPIER.init();await assets.load(msg=>document.querySelector('#load-status')!.textContent=msg);const p=makePlayer('Warden');p.position=[0,height(0,18)+.02,18];authority.state.players[p.id]=p;buildRealm();try{const s=JSON.parse(localStorage.getItem('alderwatch.settings')||'null');if(s)sound.setVolume(s.volume);}catch{}document.querySelector('#loading')!.remove();title();requestAnimationFrame(frame);installTools();}
registerGameTools([{name:'read_expedition',description:'Read the Ash Road objective, persistent progress and route. No mutations.',annotations:{readOnlyHint:true},inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>structuredClone({mode,progress:expeditionProgress(character.state),objective:expeditionObjective(authority.state,character.state),sites:authority.state.expeditionSites,stats:stats(character.state)})}]);
function readGame(){const pos=(name:string)=>character.model.getObjectByName(name)?.getWorldPosition(new T.Vector3()).toArray();return {mode,player:structuredClone(character.state),animation:character.current,grounded:character.controller.computedGrounded(),fps,draws:renderer.info.render.calls,triangles:renderer.info.render.triangles,hand:pos('hand_r'),grip:pos('Grip_R'),toolOrigin:character.tool?.getWorldPosition(new T.Vector3()).toArray(),footL:pos('foot_l'),footR:pos('foot_r'),target:currentTarget,nearby:structuredClone(Object.values(authority.state.resources).filter(r=>Math.hypot(r.position[0]-character.state.position[0],r.position[2]-character.state.position[2])<15))};}
function installTools(){registerGameTools([{name:'read_realm',description:'Inspect the current local realm, player, physical grounding, animation, verified hand socket and nearby resources.',annotations:{readOnlyHint:true},inputSchema:{type:'object',properties:{},additionalProperties:false},execute:readGame},{name:'play_input_sequence',description:'Play a bounded sequence of ordinary game inputs through the same character controller as keyboard input. Does not teleport or grant resources. Requires gameplay to be open.',inputSchema:{type:'object',properties:{steps:{type:'array',maxItems:12,items:{type:'object',properties:{keys:{type:'array',items:{type:'string',enum:['KeyW','KeyA','KeyS','KeyD','ShiftLeft','ControlLeft','Space','Attack','KeyE','Digit1','Digit2','Digit3','Digit4']}},durationMs:{type:'number',minimum:1,maximum:4000},yaw:{type:'number',minimum:-6.29,maximum:6.29}},required:['keys','durationMs'],additionalProperties:false}}},required:['steps'],additionalProperties:false},async execute(raw){const steps=(raw as {steps?:{keys:string[];durationMs:number;yaw?:number}[]})?.steps;const allowed=['KeyW','KeyA','KeyS','KeyD','ShiftLeft','ControlLeft','Space','Attack','KeyE','Digit1','Digit2','Digit3','Digit4'];if(mode!=='play')throw new Error('Enter the March before controlling the survivor');if(!steps?.length||steps.length>12||steps.some(s=>!Array.isArray(s.keys)||s.keys.some(k=>!allowed.includes(k))||!Number.isFinite(s.durationMs)||s.durationMs<1||s.durationMs>4000)||steps.reduce((n,s)=>n+s.durationMs,0)>12000)throw new Error('Invalid bounded input sequence');const samples=[];try{for(const s of steps){input.clear();input.primary=s.keys.includes('Attack');for(const k of s.keys){input.keys.add(k);input.pressed.add(k);}if(s.yaw!==undefined&&Number.isFinite(s.yaw))cameraYaw=T.MathUtils.clamp(s.yaw,-6.29,6.29);const start=performance.now();await new Promise<void>(resolve=>{const check=()=>performance.now()-start>=s.durationMs?resolve():requestAnimationFrame(check);requestAnimationFrame(check);});samples.push(readGame());}}finally{input.clear();}return {samples};}}]);}
let last=0;
const frameProfile={cpuUpdateMs:0,cpuRenderMs:0,frameIntervalMs:0,samples:0};
registerGameTools([{name:'read_performance',description:'Read measured frame interval and CPU update/render submission times. Rendering submission time does not measure completed GPU work.',annotations:{readOnlyHint:true},inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>({...frameProfile,fps,visibility:document.visibilityState,focused:document.hasFocus(),pixelRatio:renderer.getPixelRatio(),width:innerWidth,height:innerHeight,draws:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures})}]);
function frame(now:number){const cpuStart=performance.now();const frameDt=last?(now-last)/1000:.016,dt=Math.min(frameDt,.05);last=now;elapsed+=dt;frames++;fpsTime+=frameDt;if(fpsTime>1){fps=Math.round(frames/fpsTime);frames=0;fpsTime=0;}landscape.update(elapsed);
 if(mode==='play'||mode==='build'||mode==='fallen'){
  if(input.take('Escape')){if(mode==='build')resume();else{saveWorld(authority.state);input.clear();title();}}
  else if(input.take('Tab')){building.setActive(false);inventory();}else if(input.take('KeyJ')||input.take('KeyM')){journal();}else if(input.take('KeyC')){building.setActive(false);craft();}else if(input.take('KeyB')){if(mode==='build')resume();else startBuild();}
  if(mode==='play'&&input.take('KeyQ'))quickFood();if(mode==='play'&&input.take('KeyE'))interact();for(const [i,n] of ['axe','pickaxe','sword','hammer'].entries())if(input.take('Digit'+(i+1)))equip(n as ItemId);
  cameraYaw+=input.dx*.003;cameraPitch=T.MathUtils.clamp(cameraPitch+input.dy*.002,ACTION_CAMERA.minPitch,ACTION_CAMERA.maxPitch);cameraDistance=T.MathUtils.clamp(cameraDistance+input.wheel*.85,ACTION_CAMERA.minDistance,ACTION_CAMERA.maxDistance);
  if(mode==='build'){if(input.take('KeyR'))building.yaw+=Math.PI/2;building.update(camera,input.pointer,character.state);if(input.take('Attack')){const out=building.place();toast(out.message);if(out.ok){character.play('build',true);character.locked=.6;sound.impact('wood');saveWorld(authority.state);}}if(input.take('KeyX'))toast(building.dismantle(character.state).message);panels.updateBuild();}
  else building.sync(dt);
  accumulator+=dt;while(accumulator>=1/60){character.preStep(1/60,input,cameraYaw,intro===0&&(mode==='play'||mode==='build'));combat.preStep(1/60);physics.step();character.postStep(1/60);combat.postStep(1/60);gathering.update(1/60);nature.update(1/60);tickVitals(authority.state,1/60);authority.state.tick++;accumulator-=1/60;}intro=Math.max(0,intro-dt);autosave+=dt;if(autosave>15){saveWorld(authority.state);autosave=0;}if(character.state.health<=0&&mode!=='fallen')fallen();if(mode==='play'||mode==='build'){updateHud();updateCombatHud();}
 }else {if(mode!=='rehearsal-paused')character.preview(dt);if(['inventory','craft','storage','journal'].includes(mode)&&(input.take('Escape')||input.take('Tab')||input.take('KeyC')||input.take('KeyJ')||input.take('KeyM')))resume();}
 const gameplayCamera=!['title','creation','online','settings','credits'].includes(mode);const targetFov=gameplayCamera?ACTION_CAMERA.fov:48;if(camera.fov!==targetFov){camera.fov=targetFov;camera.updateProjectionMatrix();}
 const p=character.root.position;const aim=p.clone().add(new T.Vector3(0,1.25,0));let cp:T.Vector3;if(mode==='creation'){cp=p.clone().add(new T.Vector3(3.1,1.8,4.4));aim.x-=.65;}else if(mode==='title'||mode==='online'||mode==='settings'||mode==='credits'){cp=p.clone().add(new T.Vector3(5+Math.sin(elapsed*.06)*1.3,3.1,7));aim.add(new T.Vector3(-1,1,-13));}else cp=p.clone().add(new T.Vector3(-Math.sin(cameraYaw)*Math.cos(cameraPitch)*cameraDistance,1.35+Math.sin(cameraPitch)*cameraDistance,Math.cos(cameraYaw)*Math.cos(cameraPitch)*cameraDistance));
 if(intro>0)cp.add(new T.Vector3(3*intro,2*intro,2*intro));camera.position.lerp(cp,1-Math.exp(-dt*6));
 if(mode==='play'||mode==='build'){const direction=camera.position.clone().sub(aim),length=direction.length();direction.normalize();const hit=physics.castRay(new RAPIER.Ray(aim,direction),length,true,undefined,undefined,character.collider,character.body);if(hit&&hit.timeOfImpact<length)camera.position.copy(aim).addScaledVector(direction,Math.max(.7,hit.timeOfImpact-.25));}
 if(['play','build','inventory','craft','storage','journal','rehearsal-paused'].includes(mode)&&intro===0){const orbit=followCamera.update(p,cameraYaw,cameraPitch,cameraDistance,dt,(from,to)=>{const delta=to.clone().sub(from),length=delta.length();delta.normalize();let nearest:number|undefined;const right=new T.Vector3().crossVectors(delta,new T.Vector3(0,1,0)).normalize();for(const offset of [0,-.16,.16]){const origin=from.clone().addScaledVector(right,offset);const hit=physics.castRay(new RAPIER.Ray(origin,delta),length,true,undefined,undefined,character.collider,character.body);if(hit)nearest=Math.min(nearest??length,hit.timeOfImpact);}return nearest;});camera.position.copy(orbit.position);aim.copy(orbit.aim);}
 if(gathering.shake+combat.shake>0)camera.position.x+=Math.sin(elapsed*77)*(gathering.shake+combat.shake);camera.lookAt(aim);assets.updateSight(camera,p,renderer.getDrawingBufferSize(new T.Vector2()),gameplayCamera);sun.position.copy(p).addScaledVector(sunPos,60);sun.target.position.copy(p);sun.target.updateMatrixWorld();const renderStart=performance.now();renderer.render(scene,camera);frameProfile.cpuUpdateMs=frameProfile.cpuUpdateMs*.95+(renderStart-cpuStart)*.05;frameProfile.cpuRenderMs=frameProfile.cpuRenderMs*.95+(performance.now()-renderStart)*.05;frameProfile.frameIntervalMs=frameProfile.frameIntervalMs*.95+frameDt*1000*.05;frameProfile.samples++;input.endFrame();if(elapsed>toastUntil)ui.querySelector('#toast')?.remove();requestAnimationFrame(frame);}
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
function installEconomyTools(){registerGameTools([{name:'read_settlement',description:'Inspect real station distances, nearby supplies, food effects and the current snapped building proposal. Read-only.',annotations:{readOnlyHint:true},inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{const p=character.state;return structuredClone({mode,stats:stats(p),progress:authority.state.progress,structures:authority.state.structures,stations:Object.values(authority.state.stations).map(s=>({...s,distance:distance(s.position,p.position)})),containers:Object.values(authority.state.containers).map(s=>({...s,distance:distance(s.position,p.position)})),forage:Object.values(authority.state.forage).filter(f=>forageAvailable(f,authority.state.tick)&&distance(f.position,p.position)<25),drops:Object.values(authority.state.drops).filter(d=>distance(d.position,p.position)<15),proposal:building.proposal,error:building.error,sheltered:building.sheltered(p)});}}, {name:'use_realm_interface',description:'Use ordinary gameplay menus and building controls. Placement uses the current visible preview and authoritative material, reach and support checks; it does not teleport or supply items.',inputSchema:{type:'object',properties:{action:{type:'string',enum:['inventory','craft','build','resume','interact','rotate','place','select_piece']},piece:{type:'string',enum:Object.keys(BUILDS)}},required:['action'],additionalProperties:false},execute:raw=>{const c=raw as {action:string;piece?:BuildKind};if(!['play','build','inventory','craft','storage'].includes(mode))throw new Error('Enter the March first');if(c.action==='resume')resume();else if(c.action==='inventory'){building.setActive(false);inventory();}else if(c.action==='craft'){building.setActive(false);craft();}else if(c.action==='build')startBuild();else if(c.action==='interact'&&mode==='play')interact();else if(mode==='build'&&c.action==='rotate')building.yaw+=Math.PI/2;else if(mode==='build'&&c.action==='select_piece'&&c.piece&&BUILDS[c.piece])building.select(c.piece);else if(mode==='build'&&c.action==='place'){const out=building.place();if(out.ok){character.play('build',true);character.locked=.6;saveWorld(authority.state);}return out;}else throw new Error('That control is not available in this mode');return {mode};}}]);}
registerGameTools([{name:'read_environment',description:'Read authored environment bounds, actual terrain material and camera for visual QA. Does not change gameplay.',annotations:{readOnlyHint:true},inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{
 const highland=worldRoot.getObjectByName('highland') as T.Mesh|undefined,materials:T.Material[]=[];
 highland?.traverse(o=>{if(o instanceof T.Mesh)materials.push(...(Array.isArray(o.material)?o.material:[o.material]));});
 return {controls:{active:input.active,captured:document.pointerLockElement===renderer.domElement,captureCamera:input.captureCamera},camera:{position:camera.position.toArray(),yaw:cameraYaw,pitch:cameraPitch,distance:cameraDistance,fov:camera.fov,far:camera.far},frontier:authority.state.frontier,nature:{animals:authority.state.animals,visibleForage:nature?.plants.size},highland:highland?{bounds:new T.Box3().setFromObject(highland),materials:materials.map(m=>{const s=m as T.MeshStandardMaterial;return {name:m.name,type:m.type,color:s.color.toArray(),vertexColors:s.vertexColors,fog:s.fog,emissive:s.emissive?.toArray(),emissiveIntensity:s.emissiveIntensity};})}:null,foliagePatches:landscape.foliageBatches.length};
}}]);
if(import.meta.hot)import.meta.hot.on('vite:beforeFullReload',()=>{if(character&&['play','build','inventory','craft','storage','journal'].includes(mode)){saveWorld(authority.state);sessionStorage.setItem('alderwatch.dev.resume',mode==='build'?'build':'play');}});
window.addEventListener('pagehide',()=>{if(character&&['play','build','inventory','craft','storage','journal'].includes(mode))saveWorld(authority.state);});
init().then(()=>{installEconomyTools();const recover=sessionStorage.getItem('alderwatch.dev.resume');sessionStorage.removeItem('alderwatch.dev.resume');if(rehearsal)startRehearsal();else if(recover&&loadWorld()){begin(true);if(recover==='build')startBuild();}}).catch(error=>{console.error(error);document.querySelector('#load-status')!.textContent='The March could not load: '+(error.message??'an asset failed to load; reload to retry');});
