import {Landscape} from './landscape';
import {Combat} from './combat';
import {WEAPONS} from './combat-rules';
import {expandFrontierWorld,EXPANDED_REGIONS} from './world-expansion';
import {installGiantEncounters,seedGiants,GIANTS} from './giant-encounters';
import {installBackpackUI} from './backpack-ui';
import {affixDamageMultiplier,bestEquippedStack,ensureItemAffixes,itemDisplayName} from './item-affixes';
import {ensureRuntimeWorld} from './runtime-safety';
import {ensureRenown} from './renown';
import {regionAt} from './worldgen';
import type {ItemId,PlayerState,WorldState} from './state';

let active:Landscape|undefined,lastRegion='';
const installed=Symbol.for('alderwatch.mega-overnight.v1');
function persist(w:WorldState){try{localStorage.setItem('alderwatch.realm.v1',JSON.stringify(w));}catch{}}
function banner(kicker:string,title:string,text:string,cls='mega-world-banner'){if(typeof document==='undefined')return;const old=document.querySelector('.'+cls);old?.remove();const el=document.createElement('section');el.className=cls;el.innerHTML='<small></small><h1></h1><p></p>';el.querySelector('small')!.textContent=kicker;el.querySelector('h1')!.textContent=title;el.querySelector('p')!.textContent=text;document.body.append(el);requestAnimationFrame(()=>el.classList.add('show'));setTimeout(()=>el.classList.remove('show'),4300);setTimeout(()=>el.remove(),5200);}
function installWorldExpansion(){const proto=Landscape.prototype as any;if(proto.__awMegaWorld)return;const terrain=proto.terrain;proto.terrain=function(...args:any[]){const w=ensureRuntimeWorld(this.state as WorldState);expandFrontierWorld(w);seedGiants(w);active=this;const out=terrain.apply(this,args);if(typeof document!=='undefined'&&!w.progress.includes('mega-world-welcome-v1')){w.progress.push('mega-world-welcome-v1');setTimeout(()=>banner('THE MARCH HAS GROWN','BEYOND THE OLD MAP','Greymoor · Wolfpine · Blackfen · Giant’s Step · Stonewake · named giants now walk the outer country'),1400);persist(w);}return out;};proto.__awMegaWorld=true;}
function installAffixCombat(){const proto=Combat.prototype as any;if(proto.__awAffixCombat)return;const strike=proto.playerStrike;proto.playerStrike=function(...args:any[]){const p=this.player.state as PlayerState,item=p.equipped as ItemId|null,weapon=item?WEAPONS[item]:undefined,base=weapon?.damage,stack=bestEquippedStack(p.inventory,item);if(weapon&&base!==undefined&&stack){ensureItemAffixes(stack);weapon.damage=Math.max(1,Math.round(base*affixDamageMultiplier(stack)));}try{return strike.apply(this,args);}finally{if(weapon&&base!==undefined)weapon.damage=base;}};proto.__awAffixCombat=true;}
function regionTick(){const land=active;if(!land)return;const w=ensureRuntimeWorld(land.state),p=Object.values(w.players)[0];if(!p)return;const region=regionAt(p.position[0],p.position[2]);if(region===lastRegion)return;lastRegion=region;const expanded=EXPANDED_REGIONS.find(r=>r.name===region);if(!expanded)return;const key='region-discovered-'+region.toLowerCase().replace(/[^a-z]+/g,'-');if(w.progress.includes(key))return;w.progress.push(key);const renown=ensureRenown(p);renown.fame=Math.round((renown.fame+1)*10)/10;renown.gold+=5;banner('NEW REGION DISCOVERED',region.toUpperCase(),`${expanded.mood} · Fame +1 · 5 crowns found in the very official exploration budget`,'region-entry');persist(w);}
function profileTick(){if(typeof document==='undefined'||!active)return;const panel=document.querySelector<HTMLElement>('.fun-profile');if(!panel||panel.querySelector('.mega-world-profile'))return;const w=ensureRuntimeWorld(active.state),p=Object.values(w.players)[0];if(!p)return;const alive=GIANTS.filter(g=>(w.enemies[g.id]?.health??0)>0),rare=p.inventory.filter(s=>(s.quality??1)>=1.12);const section=document.createElement('section');section.className='overdrive-profile mega-world-profile';section.innerHTML='<div><small>THE OUTER MARCH</small><strong></strong><span></span></div><div><small>GIANTS STILL WALKING</small><strong></strong><span></span></div>';section.querySelector('div:first-child strong')!.textContent=`${EXPANDED_REGIONS.length} outer regions`;section.querySelector('div:first-child span')!.textContent=`${rare.length} uncommon+ equipment stacks · best names now gain deterministic affixes`;section.querySelector('div:last-child strong')!.textContent=`${alive.length} / ${GIANTS.length}`;section.querySelector('div:last-child span')!.textContent=alive.length?alive.slice(0,3).map(g=>g.name).join(' · '):'You have somehow solved the giant problem.';panel.insertBefore(section,panel.querySelector('.fun-note'));}
function inventoryTick(){if(!active)return;const p=Object.values(active.state.players)[0];if(!p)return;for(const stack of p.inventory)if((stack.quality??1)>1)ensureItemAffixes(stack);const hud=document.querySelector<HTMLElement>('.gear-quality-hud');const best=bestEquippedStack(p.inventory,p.equipped);if(hud&&best&&(best.quality??1)>1)hud.title=`${itemDisplayName(best)} · affixes included in weapon power`;}

export function installMegaOvernight(){const g=globalThis as any;if(g[installed])return;g[installed]=true;installWorldExpansion();installGiantEncounters();installAffixCombat();installBackpackUI();if(typeof window!=='undefined'){window.setInterval(regionTick,550);window.setInterval(profileTick,450);window.setInterval(inventoryTick,600);}}
installMegaOvernight();
