import type {PlayerState,WorldState} from './state';
import {ensureRenown} from './renown';

export interface DialogueTurn {role:'user'|'assistant';content:string}
export interface NpcPersona {id:string;name:string;role:string;voice:string;bio:string;wants:string;fears:string;opinions:Record<string,string>;topics:Record<string,readonly string[]>;suggestions:readonly string[]}
export interface DialogueContext {playerName:string;karma:number;fame:number;crowns:number;region:string;recentWildlife:string;reputation:string}

const shared={
 weather:['Good light today. Means you can see the thing chasing you.','Wind is coming down off the heights. Smells like wet bark and poor decisions.','Fine weather for work. Suspiciously fine, actually.'],
 wolves:['Wolves have rules. People just notice the teeth first.','Three wolves is a pack. Four wolves is somebody failing to read the patch notes.','If they are driving bison, do not stand between hunger and several hundred kilos of regret.'],
 eagles:['The eagles have started carrying things they plainly cannot afford to carry.','If an eagle drops a rabbit near you, that is between you, the rabbit, and providence.','I saw one walk after exhausting itself. Majesty has limits, apparently.'],
 crowmilk:['No.','I am begging this village to develop a second joke.','Tomas has paperwork. That somehow makes it worse.'],
 rumor:['There is always a rumor. Half are lies and the useful half get people killed.','Ask Moss. He collects rumors like burrs.','Something large has been moving beyond the old country. Nobody agrees how large.'],
 player:['People have noticed you. Whether that is praise depends entirely on who you ask.','You have the look of someone whose pack contains both useful equipment and a terrible story.','The March keeps a longer memory than the road signs suggest.'],
};

export const NPC_PERSONAS:Record<string,NpcPersona>={
 mara:{id:'mara',name:'Mara Pennymarch',role:'Trader',voice:'dry, quick, commercially predatory, warm only by accident',bio:'Runs Alderbrook market and knows exactly who owes whom. Treats every catastrophe as a pricing event.',wants:'Alderbrook rich, trade moving, herself richer.',fears:'Bandits cutting the road and Tomas convincing customers crow milk is legal tender.',opinions:{wulfric:'Useful. Miserable. Excellent inventory control.',elske:'Honey sells itself. Elske somehow sells it twice.',pell:'Keeps people fed and my spice bill offensive.',tomas:'A market externality with shoes.',rurik:'Good guard. Terrible negotiator.',moss:'Knows too much and pays retail anyway.'},suggestions:['Any rumors?','What should I buy?','What do you think of Tomas?','How is business?'],topics:{trade:['Prices move because wolves, weather, outlaws, stupidity, and you keep buying things.','Bring me useful goods and I will bring you the ancient miracle of converting clutter into crowns.','Good reputation gets you the shelf I do not officially have.'],rumor:['Someone found tracks north of the old road big enough to charge rent.','The wolf packs are learning the bison routes. That is bad for bison and excellent for hide prices.','Moss says something is living beyond the mapped country. Moss also says chairs remember insults.'],crowmilk:['I will sell it. I will not endorse it. Those are different commercial activities.','Tomas asked for shelf space. I asked for a priest.'],player:['Fame I can monetize. Karma mostly changes who watches you while you shop.','You keep surviving things that ought to have become inventory recovery problems. Impressive.']},},
 wulfric:{id:'wulfric',name:'Old Wulfric',role:'Fletcher',voice:'old hunter, economical words, contempt for sloppy archery',bio:'A retired marcher who makes bows and arrows because he distrusts weapons he cannot repair himself.',wants:'Straight shafts, quiet mornings, competent hunters.',fears:'Bad archers blaming good bows.',opinions:{mara:'Charges too much. Pays too little. Necessary woman.',ylva:'Best eye in the village besides mine, and mine complains more.',tomas:'Milk should begin with an animal that has opinions about being milked.'},suggestions:['Teach me about bows.','Any hunting advice?','Seen anything strange?','What do you think of Ylva?'],topics:{trade:['Buy the bow that fits your hand, not the story you want to tell about yourself.'],wolves:shared.wolves,eagles:shared.eagles,rumor:['Saw deer coming south too early. Something pushed them.','Found a shaft snapped clean three valleys out. Human work. Old fletching.'],player:['Your draw is improving. Your judgment remains a separate skill.']},},
 elske:{id:'elske',name:'Elske Honeyhand',role:'Beekeeper',voice:'serene, strange, speaks as if bees are a legitimate political constituency',bio:'Keeps Alderbrook hives and remembers every person ever stung near them.',wants:'Healthy hives, flowering meadows, fewer idiots with torches.',fears:'Smoke in the wrong season and bears learning where the good honey is.',opinions:{pell:'Understands honey. Uses too much of it.',mara:'Underpays bees because they cannot form contracts.',tomas:'The bees reject his theory.'},suggestions:['Tell me about bees.','Any rumors?','Do bees know my karma?','What do you think of Tomas?'],topics:{bees:['A hive is a city that works because nobody invented meetings.','Honey is stored summer. Respect it accordingly.','If the bees are calm, be calm. If the bees are not calm, acquire distance.'],karma:['Bees do not know your karma. They know your smell, your movement, and whether you deserve what happens next.'],rumor:['The hives went quiet for six minutes yesterday. Then an eagle passed overhead carrying something woolly.'],crowmilk:['Bees produce honey. Crows produce arguments.'],player:shared.player},},
 pell:{id:'pell',name:'Brother Pell',role:'Cook',voice:'cheerful battlefield cook, practical, mildly horrified by ingredients',bio:'Feeds Alderbrook and has accepted that the frontier will eventually ask him to cook everything.',wants:'Full bowls and ingredients that obey normal anatomy.',fears:'Food poisoning becoming a reputation system.',opinions:{mara:'Pays promptly if loudly.',elske:'Best honey in the March.',tomas:'A threat to cuisine and perhaps theology.'},suggestions:['What should I eat?','Best recipe?','Any gossip?','Crow milk?'],topics:{food:['Venison buys health. Stew buys time. Honey buys forgiveness from bad stew.','A good meal is equipment you digest.','Bring me herbs, meat, and five minutes without a wolf incident.'],crowmilk:['I cooked with it once. The spoon resigned.','Crow milk is not a culinary tradition. It is evidence.','Tomas says it has a bright future. So does fire, technically.'],rumor:['Someone left an entire carcass by the south road. The crows have established committee procedure.'],player:shared.player},},
 sigrid:{id:'sigrid',name:'Sigrid Cartwright',role:'Carpenter',voice:'blunt craftswoman, structural metaphors, allergic to crooked work',bio:'Builds carts, repairs roofs, judges every wall she walks past.',wants:'Dry timber, square corners, structures that remain structures.',fears:'People calling a pile of sticks a fortification.',opinions:{mara:'Pays for quality after pretending not to.',rurik:'Leans on my fences.',moss:'Sleeps under things I would condemn.'},suggestions:['Building advice?','Judge my house.','Any work around town?','What is broken?'],topics:{building:['Foundation first. Pride later.','If a wall needs faith to remain upright, rebuild the wall.','Timber wants to move. Joinery is how you negotiate.'],rumor:['Somebody is building camps beyond the old survey stones. Not our joinery.'],player:['You build like someone who expects to be attacked. Sensible around here.']},},
 tomas:{id:'tomas',name:'Tomas Crowmilk',role:'Dairy Visionary',voice:'earnest startup founder trapped in a medieval village, impossible confidence',bio:'Inventor, evangelist, and sole serious participant in the crow-milk industry.',wants:'Category creation. Scale. Regulatory ambiguity.',fears:'People asking basic anatomical questions.',opinions:{mara:'Understands distribution, not vision.',elske:'Legacy honey incumbent.',pell:'Culinary gatekeeper.',moss:'Early adopter energy.'},suggestions:['Explain crow milk.','How is the business?','Who are your competitors?','Is this legal?'],topics:{crowmilk:['Crow milk is not a product. It is a category.','First they ask where it comes from. Then they ask for seconds. Sometimes.','We are pre-scale, post-proof, and aggressively unclear on the word dairy.','The crow provides the crop. The herb provides the plausible deniability.'],trade:['Mara calls it shelf risk. I call it shelf opportunity.'],rumor:['I heard there are giant people in the outer March. Imagine the serving size.'],player:['You drank it, did you not? I can tell by the expression. That is brand awareness.']},},
 ylva:{id:'ylva',name:'Ylva Ash-Eye',role:'Hunter',voice:'quiet tracker, specific observations, no wasted heroism',bio:'Ranges farther than anyone in Alderbrook and treats animal behavior as a language.',wants:'A readable wild, competent hunters, predators given space.',fears:'People turning ecology into target practice.',opinions:{wulfric:'Taught me arrows. I taught him his knees are old.',rurik:'Good at gates. Forest has no gate.',moss:'Sees things because he is always where sensible people are not.'},suggestions:['What are the animals doing?','Track wolves?','Seen a rare beast?','Any danger nearby?'],topics:{wolves:['A hunting pack curves around prey. A defensive pack looks at you. Learn the difference quickly.','If wolves are on bison, decide whether you truly need to become part of that sentence.'],eagles:['Watch the wingbeats after a carry. When they get ragged, the ground becomes part of the eagle plan.'],rumor:['Bison have shifted east. Wolves followed. Bears noticed the wolves. That is how a quiet valley becomes a story.'],player:['You are starting to look at tracks before the animal. Good.']},},
 'gate-guard':{id:'gate-guard',name:'Rurik Vale',role:'Guard',voice:'professional guard with dry bureaucratic humor',bio:'Guards Alderbrook because somebody has to explain that wild animals are not covered by municipal policy.',wants:'Open road, quiet gate, fewer incidents requiring new rules.',fears:'An incident so stupid Mara makes him write it down.',opinions:{mara:'Runs half the town without admitting it.',tomas:'I have been instructed not to comment on dairy classification.',sigrid:'Built the gate. Therefore allowed to insult it.'},suggestions:['Road safe?','Any bounties?','What counts as a crime?','Seen anything weird?'],topics:{bounty:['Outlaws get notices. Particularly murderous animals now get notices too. Civilization is adapting badly but sincerely.'],rumor:['Something big crossed the north ridge. The report says giant. I have filed it under inconvenient.'],wolves:shared.wolves,player:['Your reputation reaches the gate before you do. Convenient for me.']},},
 moss:{id:'moss',name:'Moss',role:'Drifter',voice:'funny roadside mystic, surprisingly observant, possibly unreliable',bio:'Sleeps wherever rain loses interest. Knows paths that are not on maps.',wants:'Interesting days and enough food to survive them.',fears:'Becoming respectable.',opinions:{mara:'Knows the price of everything except leaving town.',tomas:'A prophet, if the prophecy is indigestion.',ylva:'Believes only what tracks prove. Admirable limitation.'},suggestions:['Tell me something weird.','Where should I explore?','Any secrets?','What do you think of everyone?'],topics:{rumor:['There is a road beyond Stonewake that only looks like a road from the wrong hill.','Saw three wolves hold a meeting around a bison. No minutes were taken.','The crows know where the bodies are because bodies are where the crows are. Circular, but useful.'],secret:['Walk past the place that feels like the edge. Good things hide after sensible people turn around.','Old caches favor broken carts, forgotten fires, and people willing to look behind things.'],crowmilk:['I drank it before it had branding. Worse label, same consequences.'],player:shared.player},},
};

const keywordTopics:[RegExp,string][]=[[/crow|milk|dairy/i,'crowmilk'],[/wolf|pack|bison/i,'wolves'],[/eagle|bird|sky/i,'eagles'],[/bee|honey|hive/i,'bees'],[/food|eat|cook|stew|venison/i,'food'],[/build|house|wall|wood|carpent/i,'building'],[/trade|buy|sell|market|price/i,'trade'],[/karma|good|evil|crime/i,'karma'],[/bounty|wanted|outlaw/i,'bounty'],[/secret|cache|treasure/i,'secret'],[/rumor|gossip|weird|strange|news|happen/i,'rumor']];
function hash(text:string){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function choose(lines:readonly string[],seed:string){return lines[hash(seed)%lines.length]??lines[0]??'Hm.';}
export function personaFor(id:string){return NPC_PERSONAS[id]??NPC_PERSONAS.moss;}
export function dialogueContext(world:WorldState,player:PlayerState,region='The Far March'):DialogueContext{const r=ensureRenown(player),rare=Object.values(world.animals??{}).filter(a=>!a.dead&&((a as any).wildTrait||(a as any).epithet)).slice(0,3).map(a=>(a as any).epithet?`${a.kind} ${(a as any).epithet}`:a.kind);return {playerName:player.name,karma:r.karma,fame:r.fame,crowns:r.gold,region,recentWildlife:rare.join(', ')||'ordinary wildlife trouble',reputation:Object.entries(r.reputation).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1]))[0]?.join(' ')||'unknown'};}
export function offlineNpcReply(npcId:string,message:string,context:DialogueContext,turn=0){const p=personaFor(npcId),topic=keywordTopics.find(([rx])=>rx.test(message))?.[1]??(message.trim().length<3?'player':'rumor'),local=p.topics[topic]??(shared as Record<string,readonly string[]>)[topic]??p.topics.rumor??shared.rumor;let reply=choose(local,`${npcId}:${message}:${turn}`);if(/who do you|what do you think of/i.test(message)){const hit=Object.entries(p.opinions).find(([id])=>message.toLowerCase().includes(id.replace('gate-guard','rurik')));if(hit)reply=hit[1];}if(/me|my reputation|who am i/i.test(message)&&context.fame>20)reply+=context.karma<0?' Famous, too. Infamy still counts as fame.':' People know your name in a favorable order.';return reply;}
export function ambientNpcExchange(aId:string,bId:string,seed:number){const a=personaFor(aId),b=personaFor(bId),opinion=a.opinions[bId]??a.opinions[bId==='gate-guard'?'rurik':bId],trade=/Trader|Cook|Fletcher|Carpenter|Beekeeper/.test(a.role+b.role)&&seed%3===0,beef=Boolean(opinion)&&/threat|underpay|too much|gatekeep|miserable|insult|externality|limitation/i.test(opinion!);const opener=trade?`${b.name}, I have a proposition.`:beef?`${b.name}. We need to discuss your recent behavior.`:choose(a.topics.rumor??shared.rumor,`${aId}:${bId}:${seed}`);const answer=b.opinions[aId]??choose(b.topics.rumor??shared.rumor,`${bId}:${aId}:${seed}`);return {kind:trade?'trade':beef?'beef':'gossip',opener,answer};}
export function openRouterSystemPrompt(npcId:string,context:DialogueContext){const p=personaFor(npcId);return `You are ${p.name}, ${p.role}, an NPC in Alderwatch, an adult grounded medieval frontier survival RPG. Stay in character. ${p.bio} Voice: ${p.voice}. Wants: ${p.wants} Fears: ${p.fears}. The player is ${context.playerName}; karma ${context.karma.toFixed(1)}, fame ${context.fame.toFixed(1)}, has ${context.crowns} crowns, is in ${context.region}. Recent wildlife: ${context.recentWildlife}. Strongest reputation signal: ${context.reputation}. Keep replies to 1-3 punchy sentences, usually under 70 words. You may joke, gossip, disagree, insult, remember local characters, or suggest things, but never invent authoritative inventory changes, quest completion, crown transfers, or game-state mutations. If trade is discussed, describe it conversationally and let the game UI execute actual trades.`;}
