import './npc-conversation.css';
import type {NpcRuntime,NpcPopulation} from './npcs';
import {personaFor,type DialogueTurn} from './npc-dialogue';
import {talkToNpc} from './npc-chat-client';
import {regionAt} from './worldgen';

const histories=new Map<string,DialogueTurn[]>();
let activePanel:HTMLElement|undefined;
function history(id:string){let h=histories.get(id);if(!h){try{h=JSON.parse(localStorage.getItem('alderwatch.npc.chat.'+id)||'[]') as DialogueTurn[];}catch{h=[];}histories.set(id,h);}return h;}
function remember(id:string,turn:DialogueTurn){const h=history(id);h.push(turn);while(h.length>12)h.shift();try{localStorage.setItem('alderwatch.npc.chat.'+id,JSON.stringify(h));}catch{}}
function line(host:HTMLElement,who:string,text:string,player=false){const el=document.createElement('div');el.className='npc-line'+(player?' player':'');el.innerHTML='<b></b><span></span>';el.querySelector('b')!.textContent=who;el.querySelector('span')!.textContent=text;host.append(el);host.scrollTop=host.scrollHeight;}
export function closeNpcConversation(){activePanel?.remove();activePanel=undefined;}
export function openNpcConversation(npc:NpcRuntime,pop:NpcPopulation){closeNpcConversation();const persona=personaFor(npc.definition.id),p=Object.values(pop.state.players)[0];if(!p)return;const panel=document.createElement('section');panel.className='npc-conversation';panel.innerHTML='<header><small></small><strong></strong><button class="npc-close" aria-label="Close">×</button></header><div class="npc-transcript"></div><div class="npc-suggestions"></div><form class="npc-chat-form"><input maxlength="400" autocomplete="off" aria-label="Say something" placeholder="Say something…"><button>Speak</button></form><div class="npc-ai-status">AUTHORED MEMORY · OPENROUTER READY WHEN THE SERVER KEY EXISTS</div>';panel.querySelector('header small')!.textContent=npc.definition.role;panel.querySelector('header strong')!.textContent=npc.definition.name;panel.querySelector<HTMLButtonElement>('.npc-close')!.onclick=closeNpcConversation;const transcript=panel.querySelector<HTMLElement>('.npc-transcript')!,input=panel.querySelector<HTMLInputElement>('input')!,form=panel.querySelector<HTMLFormElement>('form')!,status=panel.querySelector<HTMLElement>('.npc-ai-status')!;const h=history(npc.definition.id);if(h.length)for(const turn of h.slice(-6))line(transcript,turn.role==='user'?p.name:npc.definition.name,turn.content,turn.role==='user');else line(transcript,npc.definition.name,npc.definition.lines[0]);
 const submit=async(raw:string)=>{const message=raw.trim();if(!message)return;input.value='';input.disabled=true;line(transcript,p.name,message,true);const before=[...history(npc.definition.id)];remember(npc.definition.id,{role:'user',content:message});status.textContent='LISTENING…';const result=await talkToNpc(npc.definition.id,message,pop.state,p,before,regionAt(p.position[0],p.position[2]));remember(npc.definition.id,{role:'assistant',content:result.reply});line(transcript,npc.definition.name,result.reply);status.textContent=result.source==='openrouter'?`OPENROUTER · ${result.model??'configured model'}`:'AUTHORED MEMORY · OPENROUTER OFFLINE/UNCONFIGURED';input.disabled=false;input.focus();};form.onsubmit=e=>{e.preventDefault();void submit(input.value);};const suggestions=panel.querySelector('.npc-suggestions')!;for(const suggestion of persona.suggestions){const b=document.createElement('button');b.type='button';b.textContent=suggestion;b.onclick=()=>void submit(suggestion);suggestions.append(b);}document.body.append(panel);activePanel=panel;input.focus();}

/** Mara's real market stays authoritative; this just adds a doorway into conversation. */
export function installMarketConversationHook(getPopulation:()=>NpcPopulation|undefined){if(typeof window==='undefined')return;window.setInterval(()=>{const market=document.querySelector<HTMLElement>('.fun-market');if(!market||market.querySelector('.npc-market-talk'))return;const pop=getPopulation(),mara=pop?.runtimes.find(n=>n.definition.id==='mara');if(!pop||!mara)return;const button=document.createElement('button');button.className='npc-market-talk';button.textContent='Talk to Mara · ask rumors, prices, gossip, or why crow milk is still on the shelf';button.onclick=()=>openNpcConversation(mara,pop);market.querySelector('h2')?.after(button);},650);}

window.addEventListener('keydown',e=>{if(!activePanel)return;if(e.code==='Escape'){e.preventDefault();e.stopImmediatePropagation();closeNpcConversation();}else if(e.code==='KeyE'&&(e.target as HTMLElement)?.matches('input')===false){e.preventDefault();e.stopImmediatePropagation();closeNpcConversation();}},true);
