import {Landscape} from './landscape';
import {Combat} from './combat';
import {NpcPopulation,type NpcRuntime} from './npcs';
import {ensureRenown} from './renown';
import type {EnemyState,PlayerState,WorldState} from './state';

let activeState:WorldState|undefined;
const installed=Symbol.for('alderwatch.outlaw-legends.v1');
const titles=['the Ash-Fed','Iron Teeth','the Toll Collector','Two-Coats','the Unlicensed Hero','the Bad Receipt','the Extremely Local Problem'];
function hash(text:string){let h=2166136261;for(let i=0;i<text.length;i++)h=Math.imul(h^text.charCodeAt(i),16777619);return h>>>0;}
type EliteEnemy=EnemyState&{odElite?:boolean;odEliteApplied?:boolean;odOriginalName?:string};
export function ensureOutlawLegend(enemy:EnemyState){const e=enemy as EliteEnemy;if(e.odElite===undefined){const h=hash(e.id),captain=e.role==='captain'||/captain/i.test(e.name);e.odElite=captain||h%9===0;}if(!e.odElite||e.odEliteApplied)return e.odElite;const oldMax=e.maxHealth||1,ratio=Math.max(0,Math.min(1,e.health/oldMax));e.odOriginalName=e.name;e.maxHealth=Math.round(oldMax*(e.role==='captain'||/captain/i.test(e.name)?1.45:1.3));e.health=Math.max(e.health<=0?0:1,Math.round(e.maxHealth*ratio));e.role='captain';e.name=`${e.odOriginalName}, ${titles[hash(e.id+'title')%titles.length]}`;e.odEliteApplied=true;return true;}
function apply(w:WorldState){activeState=w;for(const e of Object.values(w.enemies))ensureOutlawLegend(e);}
function popup(title:string,text:string){if(typeof document==='undefined')return;let host=document.querySelector<HTMLElement>('.overdrive-feed');if(!host){host=document.createElement('div');host.className='overdrive-feed';document.body.append(host);}const card=document.createElement('div');card.className='overdrive-card';card.innerHTML='<small>OUTLAW LEGEND</small><strong></strong><span></span>';card.querySelector('strong')!.textContent=title;card.querySelector('span')!.textContent=text;host.prepend(card);setTimeout(()=>card.remove(),7600);}
function inspect(){const w=activeState,p=w?Object.values(w.players)[0]:undefined;if(!w||!p)return;for(const e of Object.values(w.enemies) as EliteEnemy[]){if(!e.odElite||e.health<=0||Math.hypot(e.position[0]-p.position[0],e.position[2]-p.position[2])>34)continue;const key='od-outlaw-sighted-'+e.id;if(!w.progress.includes(key)){w.progress.push(key);popup(e.name.toUpperCase(),'Named champion · heavier health pool · captain attacks · guaranteed serious loot.');try{localStorage.setItem('alderwatch.realm.v1',JSON.stringify(w));}catch{}}}}
function installWorld(){const proto=Landscape.prototype as any;if(proto.__awOutlawLegends)return;const terrain=proto.terrain;proto.terrain=function(...args:any[]){apply(this.state);return terrain.apply(this,args);};proto.__awOutlawLegends=true;const combat=Combat.prototype as any,pre=combat.preStep;if(!combat.__awOutlawPre){combat.preStep=function(dt:number){apply(this.authority.state);const out=pre.call(this,dt);inspect();return out;};combat.__awOutlawPre=true;}}
function reaction(p:PlayerState,npc:NpcRuntime){const r=ensureRenown(p);if(r.karma<=-20){if(npc.definition.role==='Guard')return 'I know your face. I also know where my whistle is.';if(npc.definition.role==='Trader')return 'Crowns first. Hands where I can see them. Reputation is a price modifier now.';return 'People have been saying things about you. Mostly with doors locked.';}if(r.fame>=30){if(npc.definition.role==='Trader')return 'Oh good, the famous one. Please buy something expensive where everyone can see.';return 'That is actually you, then. Huh. The stories made you taller.';}if(r.karma>=20){if(npc.definition.role==='Guard')return 'Road is easier when somebody decent keeps walking it.';return 'Alderbrook has noticed what you do when nobody is paying you.';}return undefined;}
function installNpcReactions(){const proto=NpcPopulation.prototype as any;if(proto.__awReputationLines)return;const original=proto.line;proto.line=function(npc:NpcRuntime,tick:number){const p=activeState?Object.values(activeState.players)[0]:undefined,react=p?reaction(p,npc):undefined;return react??original.call(this,npc,tick);};proto.__awReputationLines=true;}
function decorateProfile(){const panel=document.querySelector<HTMLElement>('.fun-profile');if(!panel||panel.querySelector('.outlaw-legend-profile')||!activeState)return;const all=Object.values(activeState.enemies) as EliteEnemy[],elite=all.filter(e=>e.odElite),dead=elite.filter(e=>e.health<=0),section=document.createElement('section');section.className='overdrive-profile outlaw-legend-profile';section.innerHTML=`<div><small>OUTLAW LEGENDS</small><strong>${elite.length} named champions</strong><span>${dead.length} defeated · the rest remain professionally irritating</span></div><div><small>HARDEST LOCAL EMPLOYMENT</small><strong>${elite.find(e=>e.health>0)?.name??'No champion currently standing'}</strong><span>Champion outlaws use captain attack logic and carry better gear.</span></div>`;panel.insertBefore(section,panel.querySelector('.fun-note'));}
function install(){const g=globalThis as any;if(g[installed])return;g[installed]=true;installWorld();installNpcReactions();const observer=new MutationObserver(()=>queueMicrotask(decorateProfile));observer.observe(document.body,{childList:true,subtree:true});setInterval(decorateProfile,400);}
if(typeof window!=='undefined'&&typeof document!=='undefined')install();
