import './overnight-overdrive.css';
import * as T from 'three';
import {Landscape} from './landscape';
import {Nature} from './nature';
import {Combat} from './combat';
import {LocalAuthority,ITEMS,addItem,type Command,type ItemId,type PlayerState,type WorldState} from './state';
import {RECIPES} from './definitions';
import {WEAPONS} from './combat-rules';
import {ACHIEVEMENTS,ensureRenown,recordRenownEvent,type AchievementDefinition} from './renown';
import {EQUIPMENT_ITEMS,bestItemQuality,craftedQuality,enemyDropQuality,qualityBonusText,qualityDamageMultiplier,qualityLabel,qualityTier} from './loot';
import {animalBountyCrowns,animalDisplayName,ensureAnimalNotoriety,ensureWildTrait,isWantedAnimal} from './wildlife-notoriety';
import {species,type AnimalState} from './wildlife-species';

let activeState:WorldState|undefined;
const installed=Symbol.for('alderwatch.overnight-overdrive.v1');
const traitApplied=new Set<string>();
const rareGearSeen=new Set<string>();
const OVERDRIVE_ACHIEVEMENTS:AchievementDefinition[]=[
 {id:'od_elite_sighted',title:'THAT ONE HAS A BOSS BAR',description:'You found a rare beast that appears to have read the patch notes.',test:r=>(r.counters.od_elite_sighted??0)>=1},
 {id:'od_elite_killed',title:'NATURE HAD A MINI-BOSS',description:'You defeated a rare beast and made ecology feel suspiciously like Diablo.',test:r=>(r.counters.od_elite_killed??0)>=1},
 {id:'od_masterwork',title:'PURPLE TEXT ENERGY',description:'Acquire Masterwork equipment. Your inventory has begun making decisions for you.',test:r=>(r.counters.od_masterwork??0)>=1},
 {id:'od_legendary',title:'ORANGE TEXT HAS ENTERED THE MARCH',description:'Acquire Legendary equipment. This is how perfectly normal evenings disappear.',test:r=>(r.counters.od_legendary??0)>=1},
 {id:'od_wanted_elite',title:'THE BOSS HAS A CRIMINAL RECORD',description:'Encounter a rare beast that is also wanted by civilization. Tremendous résumé.',test:r=>(r.counters.od_wanted_elite??0)>=1},
];

function installAchievements(){for(const a of OVERDRIVE_ACHIEVEMENTS)if(!ACHIEVEMENTS.some(existing=>existing.id===a.id))(ACHIEVEMENTS as AchievementDefinition[]).push(a);}
function player(){return activeState?Object.values(activeState.players)[0]:undefined;}
function persist(){if(activeState)try{localStorage.setItem('alderwatch.realm.v1',JSON.stringify(activeState));}catch{}}
function distance(a:number[],b:number[]){return Math.hypot(a[0]-b[0],a[2]-b[2]);}
function feed(cls:string){let host=document.querySelector<HTMLElement>('.'+cls);if(!host){host=document.createElement('div');host.className=cls;document.body.append(host);}return host;}
function card(kicker:string,title:string,text:string,cls='overdrive-feed',life=7600){if(typeof document==='undefined')return;const el=document.createElement('div');el.className='overdrive-card';el.innerHTML='<small></small><strong></strong><span></span>';el.querySelector('small')!.textContent=kicker;el.querySelector('strong')!.textContent=title;el.querySelector('span')!.textContent=text;feed(cls).prepend(el);while(feed(cls).children.length>3)feed(cls).lastElementChild?.remove();window.setTimeout(()=>el.remove(),life);}
function unlockCounter(p:PlayerState,key:string,amount=1){const r=ensureRenown(p);r.counters[key]=(r.counters[key]??0)+amount;for(const a of OVERDRIVE_ACHIEVEMENTS)if(!r.achievements[a.id]&&a.test(r)){r.achievements[a.id]=activeState?.tick||Date.now();card('ACHIEVEMENT UNLOCKED',a.title,a.description,'overdrive-achievement-feed',9200);}persist();}
function registerQuality(p:PlayerState,stack:{id:string;item:ItemId;quality:number}){if(rareGearSeen.has(stack.id))return;rareGearSeen.add(stack.id);const tier=qualityTier(stack.quality);if(tier==='common')return;card('LOOT ACQUIRED',`${qualityLabel(stack.quality).toUpperCase()} · ${ITEMS[stack.item].name}`,qualityBonusText(stack.quality));if(tier==='masterwork'||tier==='legendary')unlockCounter(p,'od_masterwork');if(tier==='legendary')unlockCounter(p,'od_legendary');}
function addQualityItem(w:WorldState,p:PlayerState,item:ItemId,quality:number){const ids=new Set(p.inventory.map(s=>s.id));addItem(w,p,item,1);const stack=p.inventory.find(s=>!ids.has(s.id)&&s.item===item)??p.inventory.filter(s=>s.item===item).at(-1);if(stack){stack.quality=quality;registerQuality(p,stack);}return stack;}

function applyRareBeast(a:AnimalState){ensureAnimalNotoriety(a);const trait=ensureWildTrait(a),x=a as AnimalState&{eliteApplied?:boolean};if(!trait||x.eliteApplied)return trait;
 const base=a.maxHealth??species(a.kind).maxHealth,health=a.health??base,ratio=base>0?health/base:1;a.maxHealth=Math.round(base*trait.health);a.health=Math.max(a.dead?0:1,Math.round(a.maxHealth*ratio));x.eliteApplied=true;return trait;
}
function decorateRareBeast(nature:any,a:AnimalState){const trait=ensureWildTrait(a),visual=nature.animals?.get(a.id);if(!trait||!visual?.group||traitApplied.has(a.id))return;traitApplied.add(a.id);visual.group.scale.multiplyScalar(trait.scale);const ring=new T.Mesh(new T.RingGeometry(.62,.72,32),new T.MeshBasicMaterial({color:trait.id==='albino'?'#d9e8df':trait.id==='ancient'?'#d6b96d':'#9c6947',transparent:true,opacity:.48,depthWrite:false,side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.035;ring.name='Rare beast ring';visual.group.add(ring);visual.group.userData.awRareTrait=trait.id;}
function inspectRareBeasts(nature:any){const w=nature.w as WorldState|undefined,p=w?Object.values(w.players)[0]:undefined;if(!w?.animals||!p)return;activeState=w;for(const a of Object.values(w.animals)){const trait=applyRareBeast(a);decorateRareBeast(nature,a);if(!trait||a.dead||distance(a.position,p.position)>44)continue;const key='od-sighted-'+a.id;if(!w.progress.includes(key)){w.progress.push(key);card('RARE WILDLIFE · OPTIONAL',animalDisplayName(a).toUpperCase(),trait.description+' No quest was started.');unlockCounter(p,'od_elite_sighted');if(isWantedAnimal(a))unlockCounter(p,'od_wanted_elite');persist();}}
}
function installNature(){const proto=Nature.prototype as any;if(proto.__awOverdriveNature)return;const original=proto.update;proto.update=function(dt:number){const animals=(this.w as WorldState).animals??{};for(const a of Object.values(animals))applyRareBeast(a);const out=original.call(this,dt);inspectRareBeasts(this);return out;};proto.__awOverdriveNature=true;}

function installAuthority(){const proto=LocalAuthority.prototype as any;if(proto.__awOverdriveDispatch)return;const original=proto.dispatch;proto.dispatch=function(c:Command){activeState=this.state;const p=this.state.players[(c as any).playerId] as PlayerState|undefined,before=p?new Set(p.inventory.map(s=>s.id)):new Set<string>();const out=original.call(this,c);if(out.ok&&p&&c.type==='craft'){const recipe=RECIPES.find(r=>r.id===c.recipeId);if(recipe&&EQUIPMENT_ITEMS.has(recipe.output)){const stack=p.inventory.find(s=>!before.has(s.id)&&s.item===recipe.output);if(stack){stack.quality=craftedQuality(p,recipe.output);registerQuality(p,stack);}}}return out;};proto.__awOverdriveDispatch=true;}

function installCombatLoot(){const proto=Combat.prototype as any;if(proto.__awOverdriveStrike)return;const original=proto.playerStrike;proto.playerStrike=function(...args:any[]){const w=this.authority.state as WorldState,p=this.player.state as PlayerState;activeState=w;const item=p.equipped,weapon=item?WEAPONS[item]:undefined,baseDamage=weapon?.damage;if(weapon&&item)weapon.damage=Math.max(1,Math.round(weapon.damage*qualityDamageMultiplier(bestItemQuality(p,item))));let out:any;try{out=original.apply(this,args);}finally{if(weapon&&baseDamage!==undefined)weapon.damage=baseDamage;}
 if(out?.outcome==='killed'&&out.targetId){const marker='od-kill-reward-'+out.targetId;if(!w.progress.includes(marker)){w.progress.push(marker);const enemy=w.enemies[out.targetId],animal=w.animals?.[out.targetId];if(enemy){const q=enemyDropQuality(enemy);if(q>=1.08&&EQUIPMENT_ITEMS.has(enemy.equipped)){addQualityItem(w,p,enemy.equipped,q);card('RAIDER DROPPED GEAR',`${qualityLabel(q).toUpperCase()} ${ITEMS[enemy.equipped].name}`,enemy.role==='captain'?'Captain loot. Extremely employable violence.':'The March has decided this corpse was a treasure chest.');}}
  if(animal){const trait=ensureWildTrait(animal);if(trait){const r=ensureRenown(p);r.fame=Math.round((r.fame+2.5)*10)/10;r.gold+=4+Math.floor(trait.bounty/4);unlockCounter(p,'od_elite_killed');card('RARE BEAST DOWN',animalDisplayName(animal).toUpperCase(),`+${4+Math.floor(trait.bounty/4)} crowns · Fame +2.5 · check the carcass`);const corpse=w.containers['corpse-'+animal.id];if(corpse)for(const stack of corpse.inventory){stack.quality=Math.max(stack.quality??1,trait.lootQuality);stack.count=Math.max(stack.count,Math.ceil(stack.count*1.5));}}}persist();}}
 return out;};proto.__awOverdriveStrike=true;}

const ODDITIES:readonly {item:ItemId;quality:number;price:number;rep:number;name:string;note:string}[]=[
 {item:'axe',quality:1.14,price:48,rep:0,name:'Pennymarch Field Axe',note:'Fine edge. No paperwork.'},
 {item:'bow',quality:1.26,price:92,rep:10,name:'Southwood Longbow',note:'Exceptional draw. Wildkeepers pretend not to notice.'},
 {item:'sword',quality:1.4,price:155,rep:25,name:'Ironward Masterwork',note:'The shelf behind Mara, not the shelf Mara admits exists.'},
 {item:'fine_sword',quality:1.52,price:285,rep:45,name:'The Very Expensive Bad Decision',note:'Legendary quality. Absolutely no refunds after heroics.'},
];
function oddityPrice(base:number,rep:number){return Math.max(1,Math.round(base*(1-Math.max(0,Math.min(60,rep))*.003)));}
function decorateMarket(){const panel=document.querySelector<HTMLElement>('.fun-market');if(!panel||panel.dataset.overdrive==='1')return;const p=player();if(!p)return;panel.dataset.overdrive='1';const r=ensureRenown(p),rep=r.reputation['Free Traders']??0,title=document.createElement('div');title.className='overdrive-shelf-title';title.textContent='MARA’S LOCKED SHELF · QUALITY GEAR';const shelf=document.createElement('div');shelf.className='overdrive-shelf';for(const g of ODDITIES){const price=oddityPrice(g.price,rep),locked=rep<g.rep,cardEl=document.createElement('article');cardEl.className=`overdrive-oddity tier-${qualityTier(g.quality)}`;cardEl.innerHTML='<strong></strong><small></small><button type="button"></button>';cardEl.querySelector('strong')!.textContent=`${qualityLabel(g.quality)} · ${g.name}`;cardEl.querySelector('small')!.textContent=`${qualityBonusText(g.quality)} · ${g.note}`;const button=cardEl.querySelector('button')!;button.textContent=locked?`Free Traders ${g.rep} required`:`Buy · ${price} crowns`;button.disabled=locked||r.gold<price;button.onclick=()=>{if(r.gold<price)return;r.gold-=price;addQualityItem(activeState!,p,g.item,g.quality);recordRenownEvent(p,'trade_buy',1,activeState?.tick??0);panel.querySelector('.market-gold')!.textContent=`Your purse · ${r.gold} crowns`;persist();button.disabled=true;button.textContent='Purchased';};shelf.append(cardEl);}panel.append(title,shelf);}
function decorateInventory(){const p=player();if(!p)return;document.querySelectorAll<HTMLElement>('.pack-item').forEach((cardEl,i)=>{const stack=p.inventory[i];if(!stack||cardEl.dataset.overdriveQuality===String(stack.quality))return;cardEl.dataset.overdriveQuality=String(stack.quality);cardEl.querySelector('.loot-quality')?.remove();if(!EQUIPMENT_ITEMS.has(stack.item)||qualityTier(stack.quality)==='common')return;cardEl.classList.add('quality-item','tier-'+qualityTier(stack.quality));const badge=document.createElement('em');badge.className='loot-quality';badge.textContent=`${qualityLabel(stack.quality)} · ${qualityBonusText(stack.quality)}`;cardEl.append(badge);});}
function gearHud(){const p=player();if(!p||!document.querySelector('.hotbar'))return;let el=document.querySelector<HTMLElement>('.gear-quality-hud');if(!el){el=document.createElement('div');el.className='gear-quality-hud';document.body.append(el);}const q=bestItemQuality(p,p.equipped),name=p.equipped?ITEMS[p.equipped].name:'Empty hands',nextClass='gear-quality-hud tier-'+qualityTier(q),nextText=qualityTier(q)==='common'?name:`${qualityLabel(q)} ${name} · ${qualityBonusText(q)}`;if(el.className!==nextClass)el.className=nextClass;if(el.textContent!==nextText)el.textContent=nextText;}
function decorateProfile(){const panel=document.querySelector<HTMLElement>('.fun-profile');if(!panel||panel.querySelector('.overdrive-profile'))return;const p=player();if(!p)return;const r=ensureRenown(p),q=bestItemQuality(p,p.equipped),section=document.createElement('section');section.className='overdrive-profile';const rare=Object.values(activeState?.animals??{}).filter(a=>!!ensureWildTrait(a)),alive=rare.filter(a=>!a.dead),wanted=rare.filter(a=>!a.dead&&isWantedAnimal(a));section.innerHTML=`<div><small>GEAR POWER</small><strong>${p.equipped?qualityLabel(q)+' '+ITEMS[p.equipped].name:'Empty hands'}</strong><span>${qualityBonusText(q)}</span></div><div><small>RARE BEASTS</small><strong>${alive.length} alive · ${wanted.length} wanted</strong><span>${r.counters.od_elite_killed??0} defeated by you</span></div>`;const note=panel.querySelector('.fun-note');panel.insertBefore(section,note);}
function scanNewGear(){const p=player();if(!p)return;for(const stack of p.inventory)if(EQUIPMENT_ITEMS.has(stack.item)&&qualityTier(stack.quality)!=='common')registerQuality(p,stack);}
function uiTick(){decorateMarket();decorateInventory();decorateProfile();gearHud();scanNewGear();}
function installWorldCapture(){const proto=Landscape.prototype as any;if(proto.__awOverdriveCapture)return;const original=proto.terrain;proto.terrain=function(...args:any[]){activeState=this.state;const out=original.apply(this,args);for(const a of Object.values((this.state as WorldState).animals??{}))applyRareBeast(a);return out;};proto.__awOverdriveCapture=true;}
const UI_SURFACE='.fun-market,.pack-item,.fun-profile,.hotbar';
function mutationTouchesUi(records:MutationRecord[]){return records.some(record=>Array.from(record.addedNodes).some(node=>node instanceof Element&&(node.matches(UI_SURFACE)||Boolean(node.querySelector(UI_SURFACE)))));}
function install(){const g=globalThis as any;if(g[installed])return;g[installed]=true;installAchievements();installWorldCapture();installNature();installAuthority();installCombatLoot();let queued=false;const observer=new MutationObserver(records=>{if(!mutationTouchesUi(records)||queued)return;queued=true;queueMicrotask(()=>{queued=false;uiTick();});});observer.observe(document.body,{childList:true,subtree:true});window.setInterval(uiTick,240);}
if(typeof window!=='undefined'&&typeof document!=='undefined')install();
