import './realm-chat-network.css';
import {SimulatedPlayerPopulation} from './simulated-players';
import {NPC_ROSTER} from './npcs';
import {talkToNpc} from './npc-chat-client';
import type {DialogueTurn} from './npc-dialogue';
import type {PlayerState,WorldState} from './state';
import {guardedNegotiationRefusal,mayNegotiate,negotiationIntent,npcRoleplayRegister,relayRoleplayContext,relayTrustDelta,standingForPlayer,standingLabel,witnessLine,type NpcStanding} from './npc-outsider-standing';
import {contractLedger,contractRoleplayContext,processContractMessage,sweepContracts} from './npc-contract-game';

type Channel='world'|'npc'|'deals';
type NpcSignal='trade'|'danger'|'build'|'food'|'weird'|'beef'|'gossip';
type NpcMessage={speakerId:string;name:string;text:string;at:number;kind:NpcSignal|'player'|'system';sourceNpcId?:string;human?:boolean};
type BotRuntimeLike={definition:{id:string;name:string};player:PlayerState;memory:{mode:string;target?:[number,number];affinity:number};group:{visible:boolean};index:number};
type NetworkSave={messages:NpcMessage[];history:Record<string,DialogueTurn[]>;trust:Record<string,number>;interactions:Record<string,number>;counter:number};
type RuntimeNetwork={save:NetworkSave;tab:Channel;wired?:HTMLElement;observer?:MutationObserver;nextGlobal:number;nextChaos:number;nextContract:number;lastBridge:Record<string,number>;lastNpcId?:string};

const BOT_PREFIX='player-bot-';
const marker=Symbol.for('alderwatch.realm-chat-network.v3');
const networks=new WeakMap<SimulatedPlayerPopulation,RuntimeNetwork>();

function hash(text:string){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function choose<T>(xs:readonly T[],seed:string){return xs[hash(seed)%xs.length]!;}
function clamp(v:number,a:number,b:number){return Math.max(a,Math.min(b,v));}
function human(world:WorldState){return Object.values(world.players).find(p=>!p.id.startsWith(BOT_PREFIX));}
function key(world:WorldState){return `alderwatch.chat.npc.${world.worldSeed??'preview'}.v1`;}
function load(world:WorldState):NetworkSave{try{const raw=localStorage.getItem(key(world));if(raw){const parsed=JSON.parse(raw) as Partial<NetworkSave>;return {messages:(parsed.messages??[]).slice(-120),history:parsed.history??{},trust:parsed.trust??{},interactions:parsed.interactions??{},counter:parsed.counter??0};}}catch{}return {messages:[],history:{},trust:{},interactions:{},counter:0};}
function persist(pop:SimulatedPlayerPopulation,n:RuntimeNetwork){try{localStorage.setItem(key(pop.state),JSON.stringify({...n.save,messages:n.save.messages.slice(-120)}));}catch{}}
function botRuntimes(pop:SimulatedPlayerPopulation){return pop.runtimes as unknown as BotRuntimeLike[];}
function baseAppend(pop:SimulatedPlayerPopulation,message:{speakerId:string;name:string;text:string;at:number;human?:boolean}){(pop as any).append(message);}

export function playerChatNoise(name:string,text:string,seed:number){
 const id=name.toLowerCase();const rate=id.includes('laggoblin')?46:id.includes('kestrel')?24:id.includes('toast')?17:id.includes('vex')?7:id.includes('niko')?9:id.includes('mira')?6:id.includes('oldman')?4:2;if(seed%100>=rate)return text;
 const rules:[RegExp,string][]=[[/\bactually\b/i,'acutally'],[/\bprobably\b/i,'prolly'],[/\bsomething\b/i,'smth'],[/\beveryone\b/i,'every1'],[/\bpeople\b/i,'ppl'],[/\bbecause\b/i,'bc'],[/\binventory\b/i,'inv'],[/\bcoming\b/i,'comin'],[/\bright\b/i,'rite'],[/\bwhat\b/i,'wat']];let out=text;for(let i=0;i<rules.length;i++){const [rx,to]=rules[(i+seed)%rules.length]!;if(rx.test(out)){out=out.replace(rx,to);break;}}if(seed%13===0&&out.length>8)out=out.replace(/\bthe\b/i,'teh');return out;
}

export function npcSignalKind(text:string,kind=''):NpcSignal{const s=(kind+' '+text).toLowerCase();if(/\bbeef\b|argument|fight|insult|behavior|default|broke the deal/.test(s))return 'beef';if(/wolf|bear|outlaw|danger|attack|tracks|road|giant|predator|bounty/.test(s))return 'danger';if(/trade|buy|sell|market|price|crowns|inventory|wood|stone|hide|contract|terms|payment/.test(s))return 'trade';if(/build|roof|beam|house|wall|timber|foundation|cart/.test(s))return 'build';if(/food|stew|honey|cook|meat|hungry|berries|herbs/.test(s))return 'food';if(/crow.?milk|weird|strange|secret|fog|chair|dream/.test(s))return 'weird';return 'gossip';}

export function pickNpcChannelTarget(message:string,seed=0){const m=message.toLowerCase();for(const npc of NPC_ROSTER){const aliases=[npc.id,npc.name.toLowerCase(),npc.name.toLowerCase().split(' ')[0]!,npc.name.toLowerCase().replace(/[^a-z0-9]/g,'')];if(aliases.some(a=>m.includes('@'+a)||m.startsWith(a+' ')))return npc.id;}if(/build|roof|wall|house|timber/.test(m))return 'sigrid';if(/trade|buy|sell|price|market/.test(m))return 'mara';if(/wolf|bear|danger|track|hunt/.test(m))return 'ylva';if(/food|cook|stew|eat/.test(m))return 'pell';if(/bow|arrow|fletch/.test(m))return 'wulfric';if(/bee|honey|hive/.test(m))return 'elske';if(/crow|milk|startup|vision/.test(m))return 'tomas';if(/road|gate|crime|bounty/.test(m))return 'gate-guard';if(/weird|secret|rumor|strange/.test(m))return 'moss';return NPC_ROSTER[seed%NPC_ROSTER.length]!.id;}

function npcLine(host:HTMLElement,m:NpcMessage){const line=document.createElement('div');line.className='player-realm-line npc-network-line '+m.kind+(m.human?' human outsider-voice':'');line.innerHTML='<b></b><span></span>';line.querySelector('b')!.textContent=m.name;line.querySelector('span')!.textContent=m.text;host.append(line);while(host.children.length>120)host.firstElementChild?.remove();host.scrollTop=host.scrollHeight;}
function addNpc(pop:SimulatedPlayerPopulation,n:RuntimeNetwork,m:NpcMessage){if(!m.human&&m.kind!=='system')m={...m,text:npcRoleplayRegister(m.text)};n.save.messages.push(m);while(n.save.messages.length>120)n.save.messages.shift();const host=n.wired?.querySelector<HTMLElement>('.realm-channel-npc');if(host)npcLine(host,m);if(n.tab!=='npc'){const tab=n.wired?.querySelector<HTMLButtonElement>('[data-realm-tab="npc"]');if(tab){const unread=Number(tab.dataset.unread??'0')+1;tab.dataset.unread=String(unread);tab.textContent=`NPC · ${Math.min(unread,99)}`;}}persist(pop,n);bridgeNpcSignal(pop,n,m);}
function sourceNpc(text:string){const lower=text.toLowerCase();return NPC_ROSTER.find(n=>lower.includes(n.name.toLowerCase())||lower.includes(n.id));}

function reaction(signal:NpcSignal,botId:string,npcName:string){const lines:Record<NpcSignal,readonly string[]>={trade:[`mara said prices moved?? omw`,`wait ${npcName} is trading rn?`,`hold up im checking that market`],danger:[`heard ${npcName}. checking it`,`uhhh ${npcName} just posted danger`,`fine im going to look`],build:[`${npcName} is talking construction im going`,`someone tell ${npcName} im bringing wood`,`ok builder meeting apparently`],food:[`${npcName} mentioned food. important`,`going to see what ${npcName} needs`,`if theres stew involved im in`],weird:[`${npcName} posted. unfortunately i need answers`,`nope im investigating that`,`what the hell is ${npcName} talking about`],beef:[`NPC beef lmao`,`ohhh ${npcName} is MAD`,`town chat is cooked today`],gossip:[`${npcName} knows something`,`wait read npc chat`,`ok thats suspicious`]};return choose(lines[signal],`${botId}:${npcName}:${signal}`);}
function preferredBots(signal:NpcSignal){if(signal==='trade')return ['toast','mira','river'];if(signal==='danger')return ['quietfox','kestrel','vex'];if(signal==='build')return ['river','mira','niko77'];if(signal==='food')return ['mira','toast','niko77'];if(signal==='weird')return ['laggoblin','kestrel','toast'];if(signal==='beef')return ['kestrel','vex','laggoblin'];return ['quietfox','mira','laggoblin'];}
function bridgeNpcSignal(pop:SimulatedPlayerPopulation,n:RuntimeNetwork,m:NpcMessage){if(m.human||m.kind==='system')return;const signal=npcSignalKind(m.text,m.kind),now=Date.now();if(now-(n.lastBridge[signal]??0)<24_000)return;const npc=NPC_ROSTER.find(x=>x.id===m.sourceNpcId)??sourceNpc(m.name+' '+m.text);if(!npc)return;const preferred=preferredBots(signal),runtime=preferred.map(id=>botRuntimes(pop).find(r=>r.definition.id===id&&r.group.visible)).find(Boolean);if(!runtime)return;n.lastBridge[signal]=now;if(runtime.memory.mode==='wander'||runtime.memory.mode==='stay'){runtime.memory.mode='come';runtime.memory.target=[npc.x,npc.z];}window.setTimeout(()=>{if(runtime.group.visible)baseAppend(pop,{speakerId:runtime.player.id,name:runtime.definition.name,text:reaction(signal,runtime.definition.id,npc.name),at:Date.now()});},700+hash(m.text)%1700);}

function worldContractReaction(pop:SimulatedPlayerPopulation,n:RuntimeNetwork,text:string){const candidates=botRuntimes(pop).filter(r=>r.group.visible&&['kestrel','toast','laggoblin','vex','mira'].includes(r.definition.id));if(!candidates.length)return;const r=candidates[hash(`${text}:${n.save.counter}:contract`)%candidates.length]!;window.setTimeout(()=>{if(r.group.visible)baseAppend(pop,{speakerId:r.player.id,name:r.definition.name,text,at:Date.now()});},900+hash(text)%1300);}
function npcName(id:string){return NPC_ROSTER.find(n=>n.id===id)?.name??id;}
function dealCard(host:HTMLElement,title:string,body:string,meta:string,kind:string){const card=document.createElement('article');card.className='realm-deal-card '+kind;card.innerHTML='<small></small><strong></strong><span></span>';card.querySelector('small')!.textContent=meta;card.querySelector('strong')!.textContent=title;card.querySelector('span')!.textContent=body;host.append(card);}
function renderDeals(pop:SimulatedPlayerPopulation,n:RuntimeNetwork){const host=n.wired?.querySelector<HTMLElement>('.realm-channel-deals'),p=human(pop.state);if(!host||!p)return;const ledger=contractLedger(pop.state,p);host.innerHTML='';const head=document.createElement('div');head.className='realm-deal-head';head.innerHTML='<strong>WRITTEN OBLIGATIONS</strong><small></small>';head.querySelector('small')!.textContent=`${ledger.active.length}/3 active · ${ledger.offers.length} open offer${ledger.offers.length===1?'':'s'}`;host.append(head);for(const c of ledger.active)dealCard(host,`${npcName(c.npcId)} · ${c.title}`,`${c.progress}/${c.objective.amount} ${c.objective.label} · ${c.remaining} remaining`,`${c.reward} crowns · ${c.repFaction} +${c.repReward.toFixed(1)} · ${c.state==='ready'?'READY TO SETTLE':'BOUND'}`,'active');for(const o of ledger.offers)dealCard(host,`${npcName(o.npcId)} · ${o.title}`,`${o.objective.amount} ${o.objective.label} · ${o.reward} crowns offered`,`OPEN OFFER · haggle room depends on trust, standing & reliability`,'offer');if(!ledger.active.length&&!ledger.offers.length){const empty=document.createElement('p');empty.className='realm-deal-empty';empty.textContent='No written obligations. Reach Negotiator standing, then ask an NPC for work on the Relay.';host.append(empty);}if(ledger.history.length){const label=document.createElement('div');label.className='realm-deal-history-title';label.textContent='RECENT WORD KEPT / BROKEN';host.append(label);for(const h of ledger.history.slice(0,4))dealCard(host,`${npcName(h.npcId)} · ${h.title}`,h.outcome==='completed'?`${h.reward} crowns paid.`:h.outcome==='defaulted'?'Deadline missed. Standing damaged.':'Agreement abandoned. Memory retained.',h.outcome.toUpperCase(),'history '+h.outcome);}const help=document.createElement('p');help.className='realm-deal-help';help.textContent='Negotiate on NPC Relay: “Any work?” · “Make it 40 crowns.” · “I accept.” · “contract status” · “pay me” · “back out”.';host.append(help);}

function standingForNetwork(pop:SimulatedPlayerPopulation,n:RuntimeNetwork,npcId=n.lastNpcId??'mara'){const p=human(pop.state);return p?standingForPlayer(p,npcId,n.save.trust[npcId]??0):'outsider';}
function setTab(pop:SimulatedPlayerPopulation,n:RuntimeNetwork,tab:Channel){n.tab=tab;const panel=n.wired;if(!panel)return;const world=panel.querySelector<HTMLElement>('.realm-channel-world'),npc=panel.querySelector<HTMLElement>('.realm-channel-npc'),deals=panel.querySelector<HTMLElement>('.realm-channel-deals'),input=panel.querySelector<HTMLInputElement>('form input'),footer=panel.querySelector<HTMLElement>('footer'),title=panel.querySelector<HTMLElement>('header small'),status=panel.querySelector<HTMLElement>('header strong');for(const b of panel.querySelectorAll<HTMLButtonElement>('.realm-chat-tabs button'))b.classList.toggle('active',b.dataset.realmTab===tab);if(world)world.hidden=tab!=='world';if(npc)npc.hidden=tab!=='npc';if(deals)deals.hidden=tab!=='deals';if(input)input.placeholder=tab==='world'?'Message realm…  @kestrel':tab==='npc'?'Speak on the Alderbrook Relay…  @Mara':'Type a contract command; it will be spoken on the NPC Relay…';if(footer)footer.textContent=tab==='world'?'The Far March · realm channel':tab==='npc'?`Alderbrook Relay · ${standingLabel(standingForNetwork(pop,n)).toLowerCase()}`:'Alderbrook Compact · promises have consequences';if(title)title.textContent=tab==='world'?'WORLD CHAT':tab==='npc'?'NPC RELAY':'DEALS';if(status){if(tab==='npc')status.textContent=`${NPC_ROSTER.length} known`;else if(tab==='deals'){const p=human(pop.state),l=p?contractLedger(pop.state,p):undefined;status.textContent=l?`${l.active.length}/3 bound`:'0/3 bound';}else{const online=botRuntimes(pop).filter(r=>r.group.visible).length+1;status.textContent=`${online} online`;}}const button=panel.querySelector<HTMLButtonElement>('[data-realm-tab="npc"]');if(tab==='npc'&&button){button.dataset.unread='0';button.textContent='NPC';}if(tab==='npc')npc?.scrollTo({top:npc.scrollHeight});if(tab==='deals'){renderDeals(pop,n);deals?.scrollTo({top:0});}}

function wire(pop:SimulatedPlayerPopulation,n:RuntimeNetwork){const panel=document.querySelector<HTMLElement>('.player-realm-chat');if(!panel||panel.dataset.networkWired==='1')return;panel.dataset.networkWired='1';n.wired=panel;const header=panel.querySelector('header'),world=panel.querySelector<HTMLElement>('.player-realm-log');if(!header||!world)return;world.classList.add('realm-channel-world');const tabs=document.createElement('nav');tabs.className='realm-chat-tabs';tabs.innerHTML='<button type="button" data-realm-tab="world" class="active">WORLD</button><button type="button" data-realm-tab="npc">NPC</button><button type="button" data-realm-tab="deals">DEALS</button>';header.after(tabs);const npc=document.createElement('div');npc.className='player-realm-log realm-channel-npc';npc.hidden=true;world.after(npc);const deals=document.createElement('div');deals.className='player-realm-log realm-channel-deals';deals.hidden=true;npc.after(deals);for(const m of n.save.messages)npcLine(npc,m);for(const b of tabs.querySelectorAll<HTMLButtonElement>('button'))b.onclick=()=>setTab(pop,n,b.dataset.realmTab as Channel);const form=panel.querySelector<HTMLFormElement>('form'),input=form?.querySelector<HTMLInputElement>('input');form?.addEventListener('submit',e=>{if(n.tab==='world')return;e.preventDefault();e.stopImmediatePropagation();const text=input?.value.trim();if(!text)return;if(input)input.value='';void sendNpcChat(pop,n,text);},true);setTab(pop,n,'world');observeNpcFeed(pop,n);}

function observeNpcFeed(pop:SimulatedPlayerPopulation,n:RuntimeNetwork){if(n.observer)return;const seen=new Set<string>();const read=(card:Element)=>{const label=card.querySelector('small')?.textContent?.trim()??'',name=card.querySelector('strong')?.textContent?.trim()??'Alderbrook',text=card.querySelector('span')?.textContent?.trim()??'';if(!text)return;const sig=label+'|'+name+'|'+text;if(seen.has(sig))return;seen.add(sig);if(seen.size>80)seen.delete(seen.values().next().value as string);const src=sourceNpc(name+' '+text);addNpc(pop,n,{speakerId:'npc-social-'+hash(sig),name,text,at:Date.now(),kind:npcSignalKind(text,label),sourceNpcId:src?.id});};n.observer=new MutationObserver(records=>{for(const record of records)for(const node of Array.from(record.addedNodes)){if(!(node instanceof Element))continue;if(node.matches('.npc-social-card'))read(node);for(const card of node.querySelectorAll('.npc-social-card'))read(card);}});n.observer.observe(document.body,{childList:true,subtree:true});for(const card of document.querySelectorAll('.npc-social-card'))read(card);}

function witnessHuman(pop:SimulatedPlayerPopulation,n:RuntimeNetwork,targetId:string,standing:NpcStanding,interaction:number){if(interaction>2&&hash(`${targetId}:${interaction}:witness`)%3!==0)return;const target=NPC_ROSTER.find(x=>x.id===targetId),others=NPC_ROSTER.filter(x=>x.id!==targetId);if(!target||!others.length)return;const witness=others[hash(`${targetId}:${interaction}:who`)%others.length]!;const raw=witnessLine(standing,target.name,witness.name,hash(`${targetId}:${interaction}:line`));const text=raw.replace(`${witness.name}: `,'');window.setTimeout(()=>addNpc(pop,n,{speakerId:'npc-'+witness.id,name:witness.name,text,at:Date.now(),kind:'gossip',sourceNpcId:witness.id}),900+hash(raw)%1200);}
function worldMocksRefusal(pop:SimulatedPlayerPopulation,n:RuntimeNetwork,npcName:string){const candidates=botRuntimes(pop).filter(r=>r.group.visible&&['kestrel','toast','laggoblin','vex'].includes(r.definition.id));if(!candidates.length)return;const r=candidates[hash(`${npcName}:${n.save.counter}:mock`)%candidates.length]!;const lines=[`bro got denied by ${npcName} lmao`,`npc credit score diff is crazy`,`medieval linkedin said no 😭`,`you gotta grind reputation apparently lol`];window.setTimeout(()=>{if(r.group.visible)baseAppend(pop,{speakerId:r.player.id,name:r.definition.name,text:choose(lines,`${r.definition.id}:${npcName}:${n.save.counter}`),at:Date.now()});},1300+hash(npcName)%1200);}

async function sendNpcChat(pop:SimulatedPlayerPopulation,n:RuntimeNetwork,text:string){
 const p=human(pop.state);if(!p)return;const fromDeals=n.tab==='deals',id=fromDeals&&n.lastNpcId&&!/@\w+/.test(text)?n.lastNpcId:pickNpcChannelTarget(text,n.save.counter++),npc=NPC_ROSTER.find(x=>x.id===id)??NPC_ROSTER[0]!;n.lastNpcId=id;
 let trust=clamp((n.save.trust[id]??0)+relayTrustDelta(text),-5,5);n.save.trust[id]=Math.round(trust*100)/100;n.save.interactions[id]=(n.save.interactions[id]??0)+1;const interaction=n.save.interactions[id]!,standing=standingForPlayer(p,id,trust);
 addNpc(pop,n,{speakerId:p.id,name:`${p.name} · ${standingLabel(standing)}`,text:text.slice(0,400),at:Date.now(),kind:'player',sourceNpcId:id,human:true});witnessHuman(pop,n,id,standing,interaction);setTab(pop,n,'npc');persist(pop,n);
 const history=n.save.history[id]??=[];
 const contract=processContractMessage(pop.state,p,id,npc.name,text,standing,trust);if(contract.handled){const reply=npcRoleplayRegister(contract.reply??'There are no further terms to record.');if(contract.trustDelta){trust=clamp(trust+contract.trustDelta,-5,5);n.save.trust[id]=Math.round(trust*100)/100;}history.push({role:'user',content:text.slice(0,400)},{role:'assistant',content:reply});n.save.history[id]=history.slice(-8);addNpc(pop,n,{speakerId:'npc-'+id,name:npc.name,text:reply,at:Date.now(),kind:(contract.kind??npcSignalKind(reply)) as NpcSignal,sourceNpcId:id});if(contract.worldReaction)worldContractReaction(pop,n,contract.worldReaction);renderDeals(pop,n);persist(pop,n);return;}
 if(negotiationIntent(text)&&!mayNegotiate(standing)){const refusal=guardedNegotiationRefusal(p.name,standing);history.push({role:'user',content:text.slice(0,400)},{role:'assistant',content:refusal});n.save.history[id]=history.slice(-8);window.setTimeout(()=>addNpc(pop,n,{speakerId:'npc-'+id,name:npc.name,text:refusal,at:Date.now(),kind:'trade',sourceNpcId:id}),550+hash(text)%650);worldMocksRefusal(pop,n,npc.name);persist(pop,n);return;}
 const before=history.slice(-6);history.push({role:'user',content:text.slice(0,400)});n.save.history[id]=history.slice(-8);persist(pop,n);const systemContext=`${relayRoleplayContext(standing,trust)} ${contractRoleplayContext(pop.state,p,id)}`;const out=await talkToNpc(id,text,pop.state,p,before,'The Far March',systemContext);const reply=npcRoleplayRegister(out.reply);history.push({role:'assistant',content:reply});n.save.history[id]=history.slice(-8);addNpc(pop,n,{speakerId:'npc-'+id,name:npc.name,text:reply,at:Date.now(),kind:npcSignalKind(reply),sourceNpcId:id});setTab(pop,n,'npc');renderDeals(pop,n);persist(pop,n);
}

const GLOBAL_LINES:Record<string,readonly string[]>={
 mara:['Road prices are up again. Blame the wolves.','Whoever keeps selling me wet timber: stop.'],
 sigrid:['If your roof moves when the wind stops, that is not a roof.','I need dry timber. I am not optimistic.'],
 ylva:['Tracks north of the road changed overnight.','If you hear wolves and then do not, move.'],
 tomas:['The crow-milk beta cohort remains extremely promising.','I seek one brave early adopter and, perhaps, a bucket.'],
 moss:['I saw a road today that was not there yesterday. Rude.','Chairs remember insults. I am still testing this.'],
};
function globalNpcPulse(pop:SimulatedPlayerPopulation,n:RuntimeNetwork,time:number){if(time<n.nextGlobal)return;n.nextGlobal=time+42+hash(`${n.save.counter}:global`)%43;const ids=Object.keys(GLOBAL_LINES),id=ids[n.save.counter++%ids.length]!,npc=NPC_ROSTER.find(x=>x.id===id)!;addNpc(pop,n,{speakerId:'npc-'+id,name:npc.name,text:choose(GLOBAL_LINES[id]!,`${pop.state.worldSeed}:${n.save.counter}`),at:Date.now(),kind:'gossip',sourceNpcId:id});}
const CHAOS:Record<string,readonly string[]>={laggoblin:['does anyone elses left boot sound louder or am i cooked','BRO why did the fog just load in like that','i have been arguing with a shrub for 3 mins'],kestrel:['who left EXACTLY one stone in the chest lmao','bro i just got pathfinding diffed by a sheep','nah whoever built that angle explain yourself'],toast:['i have cornered the berry market (there are 11 berries)','hide prices are manipulated by Big Wolf','buying one suspicious object no questions'],vex:['whoever just whiffed at that sheep log off','im watching three people lose to geometry rn','this server has negative building iq']};
function chaosPulse(pop:SimulatedPlayerPopulation,n:RuntimeNetwork,time:number){if(time<n.nextChaos)return;n.nextChaos=time+56+hash(`${n.save.counter}:chaos`)%62;const candidates=botRuntimes(pop).filter(r=>r.group.visible&&CHAOS[r.definition.id]);if(!candidates.length)return;const r=candidates[hash(`${n.save.counter}:who`)%candidates.length]!,lines=CHAOS[r.definition.id]!;baseAppend(pop,{speakerId:r.player.id,name:r.definition.name,text:choose(lines,`${pop.state.worldSeed}:${n.save.counter}:chaos`),at:Date.now()});if(hash(r.definition.id+String(n.save.counter))%4===0)window.setTimeout(()=>{if(r.group.visible)baseAppend(pop,{speakerId:r.player.id,name:r.definition.name,text:choose(['wait','nvm','???','LMAO','ok no'],r.definition.id+':double:'+n.save.counter),at:Date.now()});},650+hash(r.definition.id)%900);}
function contractPulse(pop:SimulatedPlayerPopulation,n:RuntimeNetwork,time:number){if(time<n.nextContract)return;n.nextContract=time+2.5;const p=human(pop.state);if(!p)return;const events=sweepContracts(pop.state,p);for(const e of events){const npc=NPC_ROSTER.find(x=>x.id===e.npcId)??NPC_ROSTER[0]!;if(e.trustDelta)n.save.trust[e.npcId]=Math.round(clamp((n.save.trust[e.npcId]??0)+e.trustDelta,-5,5)*100)/100;addNpc(pop,n,{speakerId:'npc-'+e.npcId,name:npc.name,text:e.text,at:Date.now(),kind:e.type==='defaulted'?'beef':'trade',sourceNpcId:e.npcId});worldContractReaction(pop,n,e.worldReaction);}if(events.length){renderDeals(pop,n);persist(pop,n);}}

function networkFor(pop:SimulatedPlayerPopulation,time=0){let n=networks.get(pop);if(!n){n={save:load(pop.state),tab:'world',nextGlobal:time+18,nextChaos:time+28,nextContract:time+2,lastBridge:{}};networks.set(pop,n);}return n;}
function install(){const g=globalThis as any;if(g[marker])return;g[marker]=true;const proto=SimulatedPlayerPopulation.prototype as any,originalEnsure=proto.ensureChat,originalUpdate=proto.update,originalAppend=proto.append,originalDispose=proto.dispose;proto.ensureChat=function(this:SimulatedPlayerPopulation){const out=originalEnsure.call(this);wire(this,networkFor(this));return out;};proto.update=function(this:SimulatedPlayerPopulation,time:number){const out=originalUpdate.call(this,time),n=networkFor(this,time);wire(this,n);globalNpcPulse(this,n,time);chaosPulse(this,n,time);contractPulse(this,n,time);return out;};proto.append=function(this:SimulatedPlayerPopulation,message:{speakerId:string;name:string;text:string;at:number;human?:boolean}){if(message.speakerId?.startsWith(BOT_PREFIX))message={...message,text:playerChatNoise(message.name,message.text,hash(`${message.speakerId}:${message.text}:${Math.floor(message.at/7000)}`))};return originalAppend.call(this,message);};proto.dispose=function(this:SimulatedPlayerPopulation){networks.get(this)?.observer?.disconnect();networks.delete(this);return originalDispose.call(this);};}

if(typeof window!=='undefined'&&typeof document!=='undefined')install();
