import {GamePanels} from './game-panels';
import {RECIPES,type Recipe} from './definitions';
import {ITEMS,type ItemId} from './state';
import {EXPANDED_RECIPE_IDS} from './crafting-expansion';
import {CATEGORY_LABELS,RARITY_LABELS,RECIPE_COLLECTIONS,collectionProgress,masteryRank,prerequisiteRecipe,recipeBookStats,recipeCategory,recipeHint,recipeKnown,recipeMastered,recipeOwned,recipeRarity,recipeReady,type RecipeCategory} from './recipe-compendium';

const installed=Symbol.for('alderwatch.recipe-book.v1');
const categoryOrder:RecipeCategory[]=['hearth','cookhouse','provisioning','processing','tools','trophy','banquet'];

function icon(item:ItemId){const span=document.createElement('span');span.className='aw-item-icon';span.dataset.item=item;span.setAttribute('aria-hidden','true');return span;}
function recipeForHeading(text:string){const clean=text.replace(/\s+/g,' ').trim();return RECIPES.find(r=>r.name===clean);}
function addHeadingIcon(heading:HTMLElement,recipe:Recipe){if(heading.querySelector('.aw-item-icon'))return;heading.prepend(icon(recipe.output));}
function prerequisiteName(recipe:Recipe){return prerequisiteRecipe(recipe)?.name??'the prerequisite recipe';}

function installStyle(){if(document.querySelector('style[data-alderwatch-recipe-book]'))return;const style=document.createElement('style');style.dataset.alderwatchRecipeBook='v1';style.textContent=`
.recipe-toolbar{display:flex;gap:.45rem;flex-wrap:wrap;align-items:center;margin:.8rem 0 1rem;padding:.7rem;border:1px solid #8c744b55;background:#17140fbb;border-radius:.45rem}.recipe-toolbar button{font-size:.72rem;padding:.48rem .68rem}.recipe-toolbar .recipe-book-open{margin-right:auto;border-color:#c9a866;color:#f2ddb0}.recipe-toolbar button.active{background:#70572e;color:#fff4d7;border-color:#d9b96f}.recipe[data-book-rarity="rare"]{border-color:#b78b3e99}.recipe[data-book-rarity="masterwork"]{border-color:#d3ae57;box-shadow:inset 0 0 18px #b2812817}.recipe[data-book-mastered="1"]::after{content:'✓ MASTERED';display:block;font-size:.62rem;letter-spacing:.12em;color:#9fca88;margin-top:.4rem}.recipe[data-book-known="0"]{opacity:.68}.recipe[data-book-known="0"] h3::after{content:' · LOCKED';font-size:.58rem;color:#c99c65;letter-spacing:.08em;margin-left:.35rem}
.recipe-book-panel{position:absolute;inset:4.5vh 4vw;z-index:50;overflow:auto;padding:1.2rem 1.35rem 2rem;border:1px solid #a88952;background:linear-gradient(155deg,#17130e 0%,#241b11 55%,#100d09 100%);box-shadow:0 22px 80px #000d;color:#eadfc8}.recipe-book-panel .book-close{position:sticky;top:0;float:right;z-index:4}.book-eyebrow{font-size:.68rem;letter-spacing:.18em;color:#bfa26b}.book-head{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(16rem,.6fr);gap:1rem;align-items:end}.book-head h2{font-size:2rem;margin:.25rem 0}.book-rank{color:#d9bd82;font-weight:700}.book-progress{height:.55rem;background:#090806;border:1px solid #725e3c;margin:.55rem 0}.book-progress i{display:block;height:100%;background:linear-gradient(90deg,#7c6437,#d0ae64)}.book-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:.45rem}.book-stat{padding:.55rem;background:#0f0d0a;border:1px solid #79623f55}.book-stat small{display:block;color:#9e8a67;font-size:.58rem;letter-spacing:.1em}.book-stat strong{font-size:1.15rem}.book-collections{display:grid;grid-template-columns:repeat(auto-fit,minmax(13rem,1fr));gap:.55rem;margin:1rem 0}.book-collection{padding:.7rem;border:1px solid #6c5a3d;background:#15110d}.book-collection.complete{border-color:#94a968;box-shadow:inset 0 0 16px #6f8e3520}.book-collection strong{display:block}.book-collection small{display:block;color:#ad9d82;margin:.2rem 0 .45rem}.book-collection meter{width:100%}.book-filters{display:flex;gap:.4rem;flex-wrap:wrap;position:sticky;top:0;z-index:3;padding:.65rem 0;background:#17130ef2;border-bottom:1px solid #6c5738}.book-filters button.active{background:#7c6235;color:white}.book-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(18rem,1fr));gap:.65rem;margin-top:.8rem}.book-card{padding:.8rem;border:1px solid #66543b;background:#110f0c;min-height:11rem}.book-card.rare{border-color:#b58c44}.book-card.masterwork{border-color:#dfbd6d;box-shadow:inset 0 0 24px #d4a54416}.book-card.locked{opacity:.62}.book-card.mastered{background:linear-gradient(145deg,#11100c,#172012)}.book-card h3{display:flex;align-items:center;gap:.45rem;margin:.15rem 0 .25rem}.book-card h3 .aw-item-icon{width:2.25rem;height:2.25rem}.book-meta{display:flex;gap:.35rem;flex-wrap:wrap;font-size:.59rem;letter-spacing:.08em;text-transform:uppercase;color:#c0aa80}.book-meta b{padding:.18rem .3rem;border:1px solid #6b583a}.book-desc{font-size:.78rem;color:#cbbca1;min-height:2.8rem}.book-cost{font-size:.68rem;line-height:1.55;color:#a9987b}.book-cost .enough{color:#a7c584}.book-cost .missing{color:#d58e77}.book-status{font-size:.69rem;margin-top:.55rem;color:#d2b779}.book-card.mastered .book-status{color:#9fc184}.book-card[data-ready="1"]{outline:1px solid #7fa65b88}.inventory-recipe-button{margin:.4rem 0 .85rem!important;border-color:#b3925e!important;color:#efd9ab!important}
@media(max-width:760px){.recipe-book-panel{inset:2vh 2vw;padding:.8rem}.book-head{grid-template-columns:1fr}.book-stats{grid-template-columns:repeat(2,1fr)}.book-grid{grid-template-columns:1fr}}
`;document.head.append(style);}

function decorateCrafting(panel:any,stationId?:string){
 const content=panel.ui.querySelector('.panel-content') as HTMLElement|null;if(!content||content.querySelector('.recipe-toolbar'))return;const p=panel.player(),w=panel.authority.state;
 const cards=[...content.querySelectorAll('.recipe')] as HTMLElement[];for(const card of cards){const h=card.querySelector('h3') as HTMLElement|null;if(!h)continue;const recipe=recipeForHeading(h.textContent??'');if(!recipe)continue;addHeadingIcon(h,recipe);const category=recipeCategory(recipe),rarity=recipeRarity(recipe),known=recipeKnown(w,recipe),mastered=recipeMastered(w,recipe),ready=recipeReady(w,p,recipe);card.dataset.recipeId=recipe.id;card.dataset.bookCategory=category;card.dataset.bookRarity=rarity;card.dataset.bookKnown=known?'1':'0';card.dataset.bookMastered=mastered?'1':'0';card.dataset.bookReady=ready?'1':'0';if(!known){const button=card.querySelector('button') as HTMLButtonElement|null;if(button)button.textContent=`Master ${prerequisiteName(recipe)} first`;}}
 const toolbar=document.createElement('div');toolbar.className='recipe-toolbar';const open=document.createElement('button');open.className='recipe-book-open';open.textContent='📖 Recipe Book';open.onclick=()=>openBook(panel,()=>panel.crafting(stationId));toolbar.append(open);
 const filters:[string,string][]=[['all','All'],['ready','Ready now'],['cook','Cooking'],['provisioning','Provisioning'],['processing','Materials'],['tools','Tools'],['trophy','Trophy'],['banquet','Banquets']];let active='all';const apply=()=>{for(const card of cards){const cat=card.dataset.bookCategory,show=active==='all'||active==='ready'&&card.dataset.bookReady==='1'||active==='cook'&&(cat==='hearth'||cat==='cookhouse')||active===cat;card.hidden=!show;}for(const b of toolbar.querySelectorAll('button[data-filter]'))b.classList.toggle('active',(b as HTMLElement).dataset.filter===active);};for(const [id,label] of filters){const b=document.createElement('button');b.dataset.filter=id;b.textContent=label;b.onclick=()=>{active=id;apply();};toolbar.append(b);}content.insertBefore(toolbar,content.firstChild);apply();
}

function decorateInventory(panel:any){const content=panel.ui.querySelector('.panel-content') as HTMLElement|null;if(!content||content.querySelector('.inventory-recipe-button'))return;const b=document.createElement('button');b.className='inventory-recipe-button';b.textContent='📖 Open Recipe Book';b.onclick=()=>openBook(panel,()=>panel.inventory());content.insertBefore(b,content.firstChild);}

function openBook(panel:any,back:()=>void){
 const w=panel.authority.state,p=panel.player(),stats=recipeBookStats(w,p);panel.ui.innerHTML='';const root=document.createElement('section');root.className='recipe-book-panel';root.innerHTML='<button class="book-close">← Back</button><div class="book-eyebrow">THE ALDERWATCH RECIPE COMPENDIUM</div><div class="book-head"><div><h2>Hearth, Hunt & Handwork</h2><div class="book-rank"></div><div class="book-progress"><i></i></div></div><div class="book-stats"></div></div><div class="book-collections"></div><div class="book-filters"></div><div class="book-grid"></div>';root.querySelector<HTMLButtonElement>('.book-close')!.onclick=back;root.querySelector<HTMLElement>('.book-rank')!.textContent=`${masteryRank(stats.mastered)} · ${stats.mastered}/${stats.total} recipes mastered · ${stats.percent}% complete`;(root.querySelector('.book-progress i') as HTMLElement).style.width=stats.percent+'%';
 const statWrap=root.querySelector('.book-stats')!;for(const [label,value] of [['MASTERED',stats.mastered],['KNOWN',stats.known],['READY NOW',stats.ready],['MASTERWORK',stats.masterwork]] as const){const s=document.createElement('div');s.className='book-stat';s.innerHTML='<small></small><strong></strong>';s.querySelector('small')!.textContent=label;s.querySelector('strong')!.textContent=String(value);statWrap.append(s);}
 const shelves=root.querySelector('.book-collections')!;for(const collection of RECIPE_COLLECTIONS){const progress=collectionProgress(w,collection),card=document.createElement('article');card.className='book-collection'+(progress.complete?' complete':'');card.innerHTML='<strong></strong><small></small><meter min="0"></meter><div></div>';card.querySelector('strong')!.textContent=(progress.complete?'✓ ':'')+collection.name;card.querySelector('small')!.textContent=collection.description;const meter=card.querySelector('meter')!;meter.max=progress.total;meter.value=progress.mastered;card.querySelector('div')!.textContent=`${progress.mastered}/${progress.total}`;shelves.append(card);}
 const filters=root.querySelector('.book-filters')!,grid=root.querySelector('.book-grid')!;let active='all';const filterButtons:[string,string][]=[['all','All recipes'],['ready','Ready now'],['mastered','Mastered'],['locked','Locked'],...categoryOrder.map(c=>[c,CATEGORY_LABELS[c]] as [string,string])];const cards:HTMLElement[]=[];
 const sorted=[...RECIPES].sort((a,b)=>categoryOrder.indexOf(recipeCategory(a))-categoryOrder.indexOf(recipeCategory(b))||recipeRarity(a).localeCompare(recipeRarity(b))||a.name.localeCompare(b.name));for(const recipe of sorted){const known=recipeKnown(w,recipe),mastered=recipeMastered(w,recipe),ready=recipeReady(w,p,recipe),category=recipeCategory(recipe),rarity=recipeRarity(recipe),card=document.createElement('article');card.className=`book-card ${rarity}${known?'':' locked'}${mastered?' mastered':''}`;card.dataset.category=category;card.dataset.ready=ready?'1':'0';card.dataset.mastered=mastered?'1':'0';card.dataset.known=known?'1':'0';const heading=document.createElement('h3');heading.append(icon(recipe.output),document.createTextNode(recipe.name));const meta=document.createElement('div');meta.className='book-meta';for(const text of [RARITY_LABELS[rarity],CATEGORY_LABELS[category],recipe.station==='campfire'?'Campfire':'Workbench',EXPANDED_RECIPE_IDS.has(recipe.id)?'Master Method':'Base Recipe']){const b=document.createElement('b');b.textContent=text;meta.append(b);}const desc=document.createElement('p');desc.className='book-desc';desc.textContent=recipe.description;const cost=document.createElement('div');cost.className='book-cost';for(const [item,count] of Object.entries(recipe.cost)){const have=recipeOwned(p,item),line=document.createElement('div');line.className=have>=count?'enough':'missing';line.textContent=`${ITEMS[item as ItemId].name} · ${have}/${count}`;cost.append(line);}const status=document.createElement('div');status.className='book-status';status.textContent=mastered?'✓ Mastered in this save':!known?`🔒 ${recipeHint(recipe)}`:ready?`Ready to craft · makes ${recipe.count} × ${ITEMS[recipe.output].name}`:`Known · gather the missing ingredients`;card.append(heading,meta,desc,cost,status);cards.push(card);grid.append(card);}
 const apply=()=>{for(const card of cards){const show=active==='all'||active==='ready'&&card.dataset.ready==='1'||active==='mastered'&&card.dataset.mastered==='1'||active==='locked'&&card.dataset.known==='0'||active===card.dataset.category;card.hidden=!show;}for(const b of filters.querySelectorAll('button'))b.classList.toggle('active',(b as HTMLElement).dataset.filter===active);};for(const [id,label] of filterButtons){const b=document.createElement('button');b.dataset.filter=id;b.textContent=label;b.onclick=()=>{active=id;apply();};filters.append(b);}apply();panel.ui.append(root);
}

function install(){const g=globalThis as any;if(g[installed])return;g[installed]=true;installStyle();const proto=GamePanels.prototype as any,crafting=proto.crafting,inventory=proto.inventory;proto.crafting=function(stationId?:string){const out=crafting.call(this,stationId);decorateCrafting(this,stationId);return out;};proto.inventory=function(){const out=inventory.call(this);decorateInventory(this);return out;};}

if(typeof document!=='undefined')install();
