import * as T from 'three';
import './simulated-players.css';
import {Landscape} from './landscape';
import type {Assets} from './assets';
import {height} from './terrain';
import {LocalAuthority,makePlayer,type Archetype,type PlayerState,type Vec3,type WorldState} from './state';
import {prepareNpcMaterials,type NpcLook} from './npcs';

export type PlayerBotAction='none'|'follow'|'come'|'stay'|'wander'|'build'|'build_here';
type BotMode='wander'|'follow'|'come'|'stay'|'build'|'build-move';
type ChatTurn={role:'user'|'assistant';content:string};
type RealmMessage={speakerId:string;name:string;text:string;at:number;human?:boolean};
interface BotMemory {mode:BotMode;affinity:number;readyToBuild:boolean;target?:[number,number];history:ChatTurn[]}
interface SavedBotMemory {bots:Record<string,BotMemory>}
interface PlayerBotDefinition {id:string;name:string;archetype:Archetype;spawn:[number,number];tint:string;look:NpcLook;voice:string;bio:string;ambient:readonly string[];cadence:number}
interface BotRuntime {definition:PlayerBotDefinition;player:PlayerState;memory:BotMemory;group:T.Group;mixer:T.AnimationMixer;idle?:T.AnimationAction;walk?:T.AnimationAction;home:[number,number];wanderTarget:[number,number];wanderAt:number;buildTarget?:[number,number];buildAttempted:boolean;index:number}

const BOT_PREFIX='player-bot-';
const ACTION_RX=/\[\[AW_ACTION:(FOLLOW|COME|STAY|WANDER|BUILD_HERE|BUILD|NONE)\]\]/ig;
let providerUnavailableUntil=0;
let activePopulation:SimulatedPlayerPopulation|undefined;

export const PLAYER_BOTS:readonly PlayerBotDefinition[]=[
 {id:'kestrel',name:'Kestrel',archetype:'Reaver',spawn:[7,-19],tint:'#61423b',look:{hair:'#211b18',skin:'#c99b78',hood:false},cadence:.84,bio:'A cracked-but-not-quite-elite PvP-minded player who trash talks constantly and then helps anyway.',voice:'lowercase gamer chat, cocky, funny, mild profanity, roasts gameplay choices, never writes paragraphs',ambient:['bro who built that fence lmao','wolves are actually cracked today wtf','if i die to a goat im deleting this game','who needs wood. dont make this emotional','that road is bait btw','nahhh i just watched a deer juke somebody']},
 {id:'mira',name:'mira.exe',archetype:'Artisan',spawn:[-8,-24],tint:'#485b48',look:{hair:'#5d3f2b',skin:'#d0a27e',hood:true},cadence:1.08,bio:'A genuinely kind co-op player who likes gathering and helping strangers, but still sounds like a normal gamer.',voice:'mostly lowercase, warm, short messages, occasional lol, never customer-service polite',ambient:['anyone need timber? ive got too much','wait dont start without me lol','this spot by the road is kinda nice actually','i left food by alderbrook if anyone is dying','whoever fixed that roof ty','bear north side btw be careful']},
 {id:'vex',name:'VEXED',archetype:'Warden',spawn:[13,-34],tint:'#4b3c3a',look:{hair:'#171515',skin:'#ae7d60',hood:true},cadence:.72,bio:'A brutally competitive sweat who is genuinely mean about bad play, but has a code and never attacks real-world identity.',voice:'very terse, cutting, sarcastic, gamer trash talk, sometimes refuses requests, no slurs and no real-world threats',ambient:['that wall placement is criminal','move. youre bodyblocking the only good angle','skill issue. enormous one.','who pulled the bear into town you absolute genius','fine ill fix it once','your base has the structural integrity of soup']},
 {id:'laggoblin',name:'LagGoblin',archetype:'Hunter',spawn:[-14,-39],tint:'#3e5146',look:{hair:'#7a6549',skin:'#c29370',hood:true},cadence:1.22,bio:'A chaotic weird player who notices bugs, invents conspiracies, and says things nobody else would think to type.',voice:'fragments, odd observations, typos sometimes, playful nonsense, no polished setup-punchline writing',ambient:['tree just looked at me wrong','i swear that deer teleported','who put soup in my chest','the fog knows my password','ok hear me out. goat cavalry','my character made a noise i dont trust']},
 {id:'river',name:'oldmanriver',archetype:'Artisan',spawn:[-10,-49],tint:'#5e5540',look:{hair:'#9b9384',skin:'#b98c6c',hood:false},cadence:1.34,bio:'An older practical builder-dad type who has played survival games forever and quietly knows how everything fits together.',voice:'plainspoken, dry, helpful without cheerleading, punctuation optional, occasional dad-level roast',ambient:['mark the corners first or were rebuilding this at midnight','ive got stone if somebody has wood','roof before weather. learned that one the expensive way','dont put the door facing the wolves','somebody left a perfectly good axe in the road','nice little camp honestly']},
 {id:'niko77',name:'niko_77',archetype:'Artisan',spawn:[9,-54],tint:'#455065',look:{hair:'#2d2722',skin:'#b98766',hood:false},cadence:1.12,bio:'A friendly experienced player who uses English as a second language. The English is clear and natural, just simpler and occasionally missing an article.',voice:'short simple English, no fake phonetic accent, no nationality stereotype, practical and warm',ambient:['i have wood. where we make base?','wait me 20 sec inventory full','this place good maybe less near road','wolf here. two maybe three','i bring stone','very nice camp actually lol']},
 {id:'toast',name:'ToastMerchant',archetype:'Reaver',spawn:[15,-63],tint:'#6a5031',look:{hair:'#3f2b1f',skin:'#c89570',hood:false},cadence:.96,bio:'An economy goblin who treats every item as a trade opportunity and every disaster as market information.',voice:'fast lowercase marketplace brain, absurd offers, short gamer messages, occasionally suspicious',ambient:['buying wood paying in extremely good vibes','hide prices are fake news','who keeps dumping berries i can monetize this','bear attack bullish for meat unfortunately','i will trade 3 stone for something interesting','do NOT ask what my crow inventory looks like']},
 {id:'quietfox',name:'quietfox',archetype:'Hunter',spawn:[-5,-64],tint:'#36453c',look:{hair:'#33251d',skin:'#d0a07b',hood:true},cadence:1.55,bio:'A mostly silent competent solo player who only speaks when there is something useful or unexpectedly funny to say.',voice:'one fragment or sentence, often 2-8 words, dry, never explains itself',ambient:['bear west','nice shot','wrong road','need arrows','that was loud','im not going in there']},
];

function hash(text:string){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function choose<T>(items:readonly T[],seed:string){return items[hash(seed)%items.length]!;}
function clamp(v:number,a:number,b:number){return Math.max(a,Math.min(b,v));}
function safeJson<T>(raw:string|null,fallback:T):T{try{return raw?JSON.parse(raw) as T:fallback;}catch{return fallback;}}
function keyFor(world:WorldState,part:string){return `alderwatch.playerbots.${world.worldSeed??'preview'}.${part}`;}
function humanPlayer(world:WorldState){return Object.values(world.players).find(p=>!p.id.startsWith(BOT_PREFIX));}
function botId(id:string){return BOT_PREFIX+id;}
function validGround(x:number,z:number){const y=height(x,z);return Number.isFinite(y)&&y>-1.05&&Math.abs(x)<68&&z>-88&&z<66;}

export function inferPlayerBotIntent(message:string):PlayerBotAction{
 const m=message.toLowerCase();
 if(/\b(build|put|make|start)\b.{0,18}\b(here|right here|this spot)\b|\b(this spot|right here)\b.{0,18}\b(build|base|house|camp)\b/.test(m))return 'build_here';
 if(/\b(help|wanna|want to|can you|lets|let's)\b.{0,24}\b(build|base|house|camp)\b|\bhelp me build\b/.test(m))return 'build';
 if(/\b(stay|wait|hold)\b.{0,10}\b(here|there|up)?\b/.test(m))return 'stay';
 if(/\b(come here|over here|come to me|get over here)\b/.test(m))return 'come';
 if(/\b(follow me|come with me|roll with me|come along|stick with me)\b/.test(m))return 'follow';
 if(/\b(wander|go away|do your thing|go do your thing|stop following)\b/.test(m))return 'wander';
 return 'none';
}

export function parsePlayerBotReply(raw:string):{text:string;action:PlayerBotAction}{
 let action:PlayerBotAction='none';
 for(const match of raw.matchAll(new RegExp(ACTION_RX.source,'ig'))){const token=(match[1]??'NONE').toLowerCase();if(token==='follow'||token==='come'||token==='stay'||token==='wander'||token==='build'||token==='build_here')action=token;}
 return {text:raw.replace(new RegExp(ACTION_RX.source,'ig'),'').replace(/\n{3,}/g,'\n\n').trim().slice(0,420),action};
}

function defaultMemory():BotMemory{return {mode:'wander',affinity:0,readyToBuild:false,history:[]};}
function ensureStack(p:PlayerState,item:'wood'|'stone'|'fiber',count:number){if(!p.inventory.some(s=>s.item===item))p.inventory.push({id:`${p.id}-${item}-kit`,item,count,quality:1});}
function ensureBotPlayer(world:WorldState,def:PlayerBotDefinition){
 const id=botId(def.id);let p=world.players[id];
 if(!p){p=makePlayer(def.archetype);p.id=id;p.name=def.name;p.position=[def.spawn[0],height(def.spawn[0],def.spawn[1])+.02,def.spawn[1]];p.hair=def.look.hair;p.skin=def.look.skin;p.hood=def.look.hood;p.yaw=hash(def.id)%628/100;for(const s of p.inventory)s.id=id+'-'+s.id;world.players[id]=p;}
 const kitFlag='sim-player-kit-'+def.id;if(!world.progress.includes(kitFlag)){ensureStack(p,'wood',34);ensureStack(p,'stone',18);ensureStack(p,'fiber',12);world.progress.push(kitFlag);}
 return p;
}

function playerLabel(name:string){
 if(typeof document==='undefined')return undefined;const canvas=document.createElement('canvas');canvas.width=384;canvas.height=84;const c=canvas.getContext('2d');if(!c)return undefined;c.fillStyle='rgba(8,13,12,.72)';c.fillRect(36,8,312,60);c.strokeStyle='rgba(155,189,173,.58)';c.strokeRect(36.5,8.5,311,59);c.fillStyle='#edf1e8';c.font='600 22px Inter,Arial';c.textAlign='center';c.fillText(name,192,38);c.fillStyle='#9fc1b1';c.font='12px Inter,Arial';c.fillText('PLAYER',192,57);const texture=new T.CanvasTexture(canvas);texture.colorSpace=T.SRGBColorSpace;const sprite=new T.Sprite(new T.SpriteMaterial({map:texture,transparent:true,depthTest:false}));sprite.scale.set(3.25,.72,1);sprite.position.set(0,2.3,0);sprite.renderOrder=21;return sprite;
}

function offlineReply(def:PlayerBotDefinition,message:string,action:PlayerBotAction){
 const byAction:Record<Exclude<PlayerBotAction,'none'>,readonly string[]>={follow:def.id==='vex'?['fine. keep up','yeah. dont make me regret it']:def.id==='niko77'?['ok i follow you','yes go, i come']:['yeah im with you','bet. lead','sure dude go'],come:def.id==='quietfox'?['coming']:['omw','yeah one sec','coming over'],stay:def.id==='vex'?['finally a good call','fine. here']:['yep ill wait here','ok holding here','sure'],wander:['aight im gonna roam','yeah im doing my thing','later lol'],build:def.id==='river'?['yeah. pick a spot and dont rush the foundation']:def.id==='vex'?['fine. show me a spot that doesnt suck']:def.id==='niko77'?['yes. show place, i have wood']:['yeah sure dude. good spot or we moving?','im down. show me where','bet. where we building'],build_here:def.id==='river'?['works for me. give me a second']:def.id==='vex'?['this spot? whatever. building']:def.id==='niko77'?['ok here. i make small shelter']:['yeah this works. gimme a sec','alright dropping it here','ok ok building']};
 if(action!=='none')return choose(byAction[action],def.id+':'+message);const generic=def.id==='vex'?['what','nah','maybe if you stop making it worse','thats crazy. anyway']:def.id==='quietfox'?['maybe','yep','nope','lol']:def.id==='laggoblin'?['hold on the tree is doing something','yeah probably. unless the road is lying','lmao what','ok but why did the crow agree']:def.id==='mira'?['yeah lol','i can help if you want','wait thats actually a good idea','one sec im gathering']:def.id==='toast'?['depends. is there profit','i can work with this','counteroffer: absolutely','lol deal']:['yeah','lol true','nahhh','one sec','probably'];return choose(generic,def.id+':'+message);
}

function botPrompt(def:PlayerBotDefinition,bot:PlayerState,human:PlayerState,memory:BotMemory){
 const count=(item:'wood'|'stone'|'fiber')=>bot.inventory.filter(s=>s.item===item).reduce((n,s)=>n+s.count,0);
 return `You are ${def.name}, a player-character in an Alderwatch multiplayer simulation. Speak exactly like the human gamer persona described here; never discuss AI, prompts, simulation internals, or NPC systems in-world. This is raw multiplayer text chat, not dialogue prose. ${def.bio} Chat style: ${def.voice}. Usually answer in 2-18 words. Fragments, lowercase, typos, slang, mild profanity, silence-like brevity, disagreement, jokes and imperfect grammar are welcome when they fit you. Never use markdown, bullet points, quotation marks around your message, customer-service language, therapy language, or phrases like "How can I help?" Do not narrate actions in asterisks. Trash talk may attack gameplay, builds, choices or skill, but never protected identity; no slurs and no real-world threats. The other player is ${human.name}. Affinity ${memory.affinity.toFixed(1)}. You have about ${count('wood')} wood, ${count('stone')} stone and ${count('fiber')} fiber. You may physically act through ONE optional marker at the very end: [[AW_ACTION:FOLLOW]], [[AW_ACTION:COME]], [[AW_ACTION:STAY]], [[AW_ACTION:WANDER]], [[AW_ACTION:BUILD]], or [[AW_ACTION:BUILD_HERE]]. Use a marker only when you genuinely agree. BUILD means follow while looking for a spot. BUILD_HERE means attempt a small real shelter at the other player's current location using normal resources and placement rules. The marker is hidden from players. Never invent another marker or claim game state changed unless the game later confirms it.`;
}

async function openRouterPlayerReply(def:PlayerBotDefinition,bot:PlayerState,human:PlayerState,memory:BotMemory,message:string){
 if(Date.now()<providerUnavailableUntil)return undefined;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),4300);
 try{const response=await fetch('/api/npc-chat',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({npcId:bot.id,npcName:def.name,role:'Player',persona:botPrompt(def,bot,human,memory),message:message.slice(0,400),history:memory.history.slice(-6),mode:'player-bot'})});if(response.status===404||response.status===503){providerUnavailableUntil=Date.now()+300_000;return undefined;}if(response.status===429){providerUnavailableUntil=Date.now()+30_000;return undefined;}if(!response.ok)throw new Error(`player bot chat HTTP ${response.status}`);const data=await response.json() as {reply?:unknown};if(typeof data.reply!=='string'||!data.reply.trim())return undefined;return parsePlayerBotReply(data.reply);}catch(error){if(!(error instanceof DOMException&&error.name==='AbortError'))console.warn('Simulated player chat fell back to local personality.',error);providerUnavailableUntil=Date.now()+45_000;return undefined;}finally{clearTimeout(timer);}
}

function addRealmLine(host:HTMLElement,message:RealmMessage){const line=document.createElement('div');line.className='player-realm-line'+(message.human?' human':'');line.innerHTML='<b></b><span></span>';line.querySelector('b')!.textContent=message.name;line.querySelector('span')!.textContent=message.text;host.append(line);while(host.children.length>70)host.firstElementChild?.remove();host.scrollTop=host.scrollHeight;}

export class SimulatedPlayerPopulation {
 root=new T.Group();runtimes:BotRuntime[]=[];private lastTime=0;private nextAmbientAt=9;private ambientCursor=0;private chat?:HTMLElement;private log?:HTMLElement;private messages:RealmMessage[]=[];private memories:SavedBotMemory;private authority:LocalAuthority;private pendingBuildReplies=new Set<string>();
 constructor(private scene:T.Scene|T.Group,private assets:Assets,public state:WorldState){
  this.root.name='Alderwatch simulated players';scene.add(this.root);this.authority=new LocalAuthority(state);this.memories=safeJson(localStorage.getItem(keyFor(state,'memory')),{bots:{}} as SavedBotMemory);this.messages=safeJson(localStorage.getItem(keyFor(state,'chat')),[] as RealmMessage[]).slice(-70);const idleClip=assets.survivor.animations.find(a=>/idle/i.test(a.name)),walkClip=assets.survivor.animations.find(a=>/walk/i.test(a.name));
  PLAYER_BOTS.forEach((def,index)=>{const player=ensureBotPlayer(state,def),memory=this.memories.bots[def.id]??=defaultMemory(),visual=prepareNpcMaterials(assets.human(),def.tint,def.look),group=new T.Group();group.name=`Simulated player ${def.name}`;group.add(visual);const tag=playerLabel(def.name);if(tag)group.add(tag);group.position.fromArray(player.position);this.root.add(group);const mixer=new T.AnimationMixer(visual),idle=idleClip?mixer.clipAction(idleClip):undefined,walk=walkClip?mixer.clipAction(walkClip):undefined;(idle??walk)?.play();this.runtimes.push({definition:def,player,memory,group,mixer,idle,walk,home:[def.spawn[0],def.spawn[1]],wanderTarget:[player.position[0],player.position[2]],wanderAt:index*1.7+2,buildAttempted:false,index});});this.persistMemory();activePopulation=this;
 }
 private persistMemory(){try{localStorage.setItem(keyFor(this.state,'memory'),JSON.stringify(this.memories));}catch{}}
 private persistChat(){try{localStorage.setItem(keyFor(this.state,'chat'),JSON.stringify(this.messages.slice(-70)));}catch{}}
 private append(message:RealmMessage){this.messages.push(message);while(this.messages.length>70)this.messages.shift();if(this.log)addRealmLine(this.log,message);this.persistChat();}
 private ensureChat(){
  const playing=Boolean(document.querySelector('.hotbar'));if(!playing){if(this.chat)this.chat.hidden=true;return;}if(this.chat){this.chat.hidden=false;return;}const panel=document.createElement('section');panel.className='player-realm-chat';panel.innerHTML='<header><div><small>REALM CHAT</small><strong></strong></div><button type="button" class="player-chat-collapse" aria-label="Collapse realm chat">−</button></header><div class="player-realm-log"></div><form><input maxlength="400" autocomplete="off" spellcheck="false" placeholder="Message realm…  @kestrel"><button>Send</button></form><footer>persistent realm chat · simulated players</footer>';panel.querySelector('header strong')!.textContent=`${this.runtimes.length+1} online`;const log=panel.querySelector<HTMLElement>('.player-realm-log')!,form=panel.querySelector<HTMLFormElement>('form')!,input=panel.querySelector<HTMLInputElement>('input')!,collapse=panel.querySelector<HTMLButtonElement>('.player-chat-collapse')!;for(const message of this.messages)addRealmLine(log,message);form.onsubmit=e=>{e.preventDefault();const text=input.value.trim();if(!text)return;input.value='';this.sendPlayerChat(text);};collapse.onclick=()=>{panel.classList.toggle('collapsed');collapse.textContent=panel.classList.contains('collapsed')?'+':'−';};document.body.append(panel);this.chat=panel;this.log=log;
 }
 private pickBot(message:string){const normalized=message.toLowerCase().replace(/[^a-z0-9_@.]+/g,' ');const direct=this.runtimes.find(r=>{const aliases=[r.definition.id,r.definition.name.toLowerCase(),r.definition.name.toLowerCase().replace(/[^a-z0-9_]/g,'')];return aliases.some(a=>normalized.includes('@'+a)||normalized.startsWith(a+' '));});return direct??this.runtimes[hash(message+':'+this.messages.length)%this.runtimes.length]!;}
 sendPlayerChat(text:string){const human=humanPlayer(this.state);if(!human)return;this.append({speakerId:human.id,name:human.name,text:text.slice(0,400),at:Date.now(),human:true});const primary=this.pickBot(text);void this.respond(primary,text,human);if(/\b(anyone|everybody|guys|chat|yall|y'all)\b/i.test(text)&&this.runtimes.length>1&&hash(text)%3!==0){const second=this.runtimes[(primary.index+1+hash(text+'second')%(this.runtimes.length-1))%this.runtimes.length]!;const action=inferPlayerBotIntent(text);window.setTimeout(()=>{if(activePopulation===this)this.append({speakerId:second.player.id,name:second.definition.name,text:offlineReply(second.definition,text,action),at:Date.now()});},2400+hash(text+'delay')%3300);}}
 private async respond(runtime:BotRuntime,message:string,human:PlayerState){
  const inferred=inferPlayerBotIntent(message),before=[...runtime.memory.history];runtime.memory.history.push({role:'user',content:message.slice(0,400)});runtime.memory.history=runtime.memory.history.slice(-10);this.persistMemory();const model=await openRouterPlayerReply(runtime.definition,runtime.player,human,{...runtime.memory,history:before},message);let action=model?.action??inferred;let text=model?.text||offlineReply(runtime.definition,message,action);if(model&&action==='none'&&inferred!=='none'&&/\b(yeah|yep|sure|ok|okay|fine|bet|omw|coming|down|works|alright|lets|let's)\b/i.test(text))action=inferred;if(!text)text=offlineReply(runtime.definition,message,action);const delay=clamp(520+text.length*runtime.definition.cadence*18+hash(message+runtime.definition.id+Date.now())%1400,650,3600);
  window.setTimeout(()=>{if(activePopulation!==this)return;runtime.memory.history.push({role:'assistant',content:text});runtime.memory.history=runtime.memory.history.slice(-10);const cooperative=action==='build'||action==='build_here'||action==='follow';runtime.memory.affinity=clamp(runtime.memory.affinity+(cooperative?.3:.08),-10,10);this.append({speakerId:runtime.player.id,name:runtime.definition.name,text,at:Date.now()});this.applyAction(runtime,action,human);this.persistMemory();},delay);
 }
 private applyAction(runtime:BotRuntime,action:PlayerBotAction,human:PlayerState){if(action==='none')return;if(action==='follow'){runtime.memory.mode='follow';runtime.memory.readyToBuild=false;}else if(action==='come'){runtime.memory.mode='come';runtime.memory.target=[human.position[0],human.position[2]];}else if(action==='stay'){runtime.memory.mode='stay';runtime.memory.readyToBuild=false;}else if(action==='wander'){runtime.memory.mode='wander';runtime.memory.readyToBuild=false;runtime.wanderAt=0;}else if(action==='build'){runtime.memory.mode='build';runtime.memory.readyToBuild=true;}else{runtime.memory.mode='build-move';runtime.memory.readyToBuild=true;runtime.buildTarget=this.findBuildTarget(human);runtime.buildAttempted=false;}this.persistMemory();}
 private findBuildTarget(human:PlayerState):[number,number]{const x=human.position[0]+Math.sin(human.yaw)*4.2,z=human.position[2]+Math.cos(human.yaw)*4.2;return [Math.round(x/3)*3,Math.round(z/3)*3];}
 private buildWorkPoint(target:[number,number],runtime:BotRuntime):[number,number]{const candidates:[[number,number],...Array<[number,number]>]=[[target[0]+3.2,target[1]],[target[0]-3.2,target[1]],[target[0],target[1]+3.2],[target[0],target[1]-3.2]];return candidates.find(([x,z])=>validGround(x,z))??runtime.home;}
 private tryBuild(runtime:BotRuntime){
  if(runtime.buildAttempted||!runtime.buildTarget)return;runtime.buildAttempted=true;const p=runtime.player,[baseX,baseZ]=runtime.buildTarget;const candidates:[[number,number],...Array<[number,number]>]=[[baseX,baseZ],[baseX+3,baseZ],[baseX-3,baseZ],[baseX,baseZ+3],[baseX,baseZ-3]];let floorId:string|undefined,last='couldnt place it';for(const [x,z] of candidates){if(!validGround(x,z)||Math.hypot(x-p.position[0],z-p.position[2])>7.9)continue;const before=new Set(Object.keys(this.state.structures)),out=this.authority.dispatch({type:'place',playerId:p.id,kind:'foundation',position:[x,height(x,z),z],yaw:0});last=out.message;if(out.ok){floorId=Object.keys(this.state.structures).find(id=>!before.has(id));runtime.buildTarget=[x,z];break;}}
  if(!floorId){this.buildResult(runtime,false,last);runtime.memory.mode='stay';return;}const floor=this.state.structures[floorId];if(!floor){this.buildResult(runtime,false,'foundation vanished somehow');runtime.memory.mode='stay';return;}const [x,y,z]=floor.position;const pieces=[{kind:'wall' as const,position:[x-1.5,y+.44,z] as Vec3,yaw:Math.PI/2},{kind:'doorway' as const,position:[x+1.5,y+.44,z] as Vec3,yaw:Math.PI/2},{kind:'roof' as const,position:[x,y+3.14,z] as Vec3,yaw:0}];let built=1;for(const piece of pieces){const out=this.authority.dispatch({type:'place',playerId:p.id,kind:piece.kind,position:piece.position,yaw:piece.yaw,supportId:floorId});last=out.message;if(out.ok)built++;}this.buildResult(runtime,built>=4,last,built>=4?'':`got ${built} pieces down but ${last.toLowerCase()}`);runtime.memory.mode='stay';runtime.memory.readyToBuild=false;this.persistMemory();
 }
 private buildResult(runtime:BotRuntime,complete:boolean,message:string,partial=''){if(this.pendingBuildReplies.has(runtime.definition.id))return;this.pendingBuildReplies.add(runtime.definition.id);const text=complete?(runtime.definition.id==='vex'?'there. an actual roof. youre welcome':runtime.definition.id==='river'?'little shelter is up. thatll hold':'ok shelter is actually up lol'):(partial||`nah game says ${message.toLowerCase()}`);window.setTimeout(()=>{this.pendingBuildReplies.delete(runtime.definition.id);if(activePopulation===this)this.append({speakerId:runtime.player.id,name:runtime.definition.name,text,at:Date.now()});},1100+hash(text)%1500);}
 private ambient(time:number){if(time<this.nextAmbientAt||document.visibilityState==='hidden'||!document.querySelector('.hotbar'))return;const runtime=this.runtimes[this.ambientCursor++%this.runtimes.length]!,text=choose(runtime.definition.ambient,`${this.state.worldSeed}:${runtime.definition.id}:${Math.floor(time/11)}`);this.append({speakerId:runtime.player.id,name:runtime.definition.name,text,at:Date.now()});this.nextAmbientAt=time+14+hash(text+Math.floor(time))%3900/100;}
 private desired(runtime:BotRuntime,human:PlayerState,time:number):[number,number]{const mode=runtime.memory.mode;if(mode==='follow'||mode==='build'){const angle=human.yaw+Math.PI+(runtime.index-(this.runtimes.length-1)/2)*.14,radius=2.4+(runtime.index%3)*.42;return [human.position[0]+Math.sin(angle)*radius,human.position[2]+Math.cos(angle)*radius];}if(mode==='come'&&runtime.memory.target)return runtime.memory.target;if(mode==='stay')return [runtime.player.position[0],runtime.player.position[2]];if(mode==='build-move'&&runtime.buildTarget)return this.buildWorkPoint(runtime.buildTarget,runtime);const d=Math.hypot(runtime.player.position[0]-runtime.wanderTarget[0],runtime.player.position[2]-runtime.wanderTarget[1]);if(time>=runtime.wanderAt||d<.45){const seed=`${this.state.worldSeed}:${runtime.definition.id}:${Math.floor(time/9)}`,a=hash(seed)%628/100,r=2.5+hash(seed+'r')%720/100;let x=runtime.home[0]+Math.sin(a)*r,z=runtime.home[1]+Math.cos(a)*r;if(!validGround(x,z)){x=runtime.home[0];z=runtime.home[1];}runtime.wanderTarget=[x,z];runtime.wanderAt=time+6+hash(seed+'t')%1100/100;}return runtime.wanderTarget;}
 update(time:number){
  this.ensureChat();const human=humanPlayer(this.state);if(!human)return;const dt=this.lastTime?Math.min(.08,Math.max(.001,time-this.lastTime)):.016;this.lastTime=time;for(const runtime of this.runtimes){const target=this.desired(runtime,human,time),p=runtime.player,dx=target[0]-p.position[0],dz=target[1]-p.position[2],distance=Math.hypot(dx,dz),moving=distance>.16;let speed=distance>9?3.8:2.25;if(runtime.memory.mode==='wander')speed=1.45;if(moving){const step=Math.min(distance,speed*dt);p.position[0]+=dx/distance*step;p.position[2]+=dz/distance*step;p.yaw=Math.atan2(dx,dz);}p.position[1]=height(p.position[0],p.position[2])+.02;runtime.group.position.fromArray(p.position);runtime.group.rotation.y=p.yaw;runtime.mixer.update(dt);if(runtime.walk&&runtime.idle){if(moving&&!runtime.walk.isRunning()){runtime.idle.fadeOut(.18);runtime.walk.reset().fadeIn(.18).play();}else if(!moving&&!runtime.idle.isRunning()){runtime.walk.fadeOut(.2);runtime.idle.reset().fadeIn(.2).play();}}if(runtime.walk)runtime.walk.timeScale=clamp(speed/2.1,.72,1.7);if(runtime.memory.mode==='come'&&runtime.memory.target&&distance<.5){runtime.memory.mode='stay';runtime.memory.target=undefined;this.persistMemory();}if(runtime.memory.mode==='build-move'&&runtime.buildTarget){const work=this.buildWorkPoint(runtime.buildTarget,runtime);if(Math.hypot(p.position[0]-work[0],p.position[2]-work[1])<.65)this.tryBuild(runtime);}}
  this.ambient(time);
 }
 dispose(){this.root.removeFromParent();for(const runtime of this.runtimes)runtime.mixer.stopAllAction();this.runtimes=[];this.chat?.remove();this.chat=undefined;this.log=undefined;if(activePopulation===this)activePopulation=undefined;}
}

function install(){
 const global=globalThis as typeof globalThis&{[key:symbol]:boolean};const marker=Symbol.for('alderwatch.simulated-players.v1');if(global[marker])return;global[marker]=true;const proto=Landscape.prototype as Landscape&{__awPlayerBots?:boolean};if(proto.__awPlayerBots)return;const terrain=proto.terrain,update=proto.update;const populations=new WeakMap<Landscape,SimulatedPlayerPopulation>();
 proto.terrain=function(this:Landscape,...args:Parameters<Landscape['terrain']>){const out=terrain.apply(this,args);activePopulation?.dispose();const pop=new SimulatedPlayerPopulation(this.scene,this.assets,this.state);populations.set(this,pop);activePopulation=pop;return out;};
 proto.update=function(this:Landscape,...args:Parameters<Landscape['update']>){const out=update.apply(this,args);const pop=populations.get(this);if(pop){activePopulation=pop;pop.update(args[0]);}return out;};proto.__awPlayerBots=true;
}
if(typeof window!=='undefined'&&typeof document!=='undefined')install();
