import {trackFrontier,type Frontier} from './worldgen';
import {bountyCommand,type BountySite,type BountyProgress} from './bounties';
export type Vec3 = [number,number,number];
import {applyEconomyCommand,type EconomyCommand} from './economy';
import {stats,STATIC_STATIONS,type BuildKind,type StationKind} from './definitions';
import {beginAction,resolveStrike,respawn,actionBusy,type Fighter} from './combat-rules';
import type {AnimalState} from './wildlife-species';
import {expeditionCommand,type ExpeditionProgress,type ExpeditionSite} from './expedition';
import {migrateLegacySkills} from './skills';
export type ItemId='mushroom'|'herb'|'woodland_broth'|'axe'|'pickaxe'|'hammer'|'sword'|'fine_sword'|'bow'|'wood'|'stone'|'iron'|'fiber'|'venison'|'berries'|'grilled_venison'|'hearty_stew'|'hide'|'crow_crop'|'crow_milk'|'wild_honey';
export type Archetype='Warden'|'Hunter'|'Reaver'|'Artisan';
export interface Stack {id:string;item:ItemId;count:number;quality:number}
export interface CombatState {guardSince?:number;kind:'idle'|'attack'|'heavy'|'dodge'|'hit'|'death';started:number;until:number;consumed:boolean;blocking:boolean;weapon:ItemId|null}
export interface PlayerState {frontierTarget?:string;bounties?:BountyProgress;expedition?:ExpeditionProgress;nextMealAt?:number;id:string;name:string;archetype:Archetype;position:Vec3;yaw:number;health:number;stamina:number;inventory:Stack[];equipped:ItemId|null;hair:string;skin:string;hood:boolean;skills:Record<string,number>;buffs:{id:string;remaining:number}[];home?:Vec3;combat?:CombatState}
export interface ResourceState {id:string;kind:'tree'|'rock';position:Vec3;variant:number;health:number;phase:'standing'|'falling'|'fallen';rotation:number;scale?:number}
export interface DropState {id:string;item:ItemId;count:number;position:Vec3;rotation:Vec3}
export interface StructureState {id:string;kind:BuildKind;position:Vec3;yaw:number;ownerId:string;supportId?:string;doorOpen?:boolean}
export interface StationState {id:string;name:string;kind:StationKind;position:Vec3}
export interface ContainerState {id:string;name:string;position:Vec3;inventory:Stack[];ownerId?:string;looted:boolean}
export interface EnemyState {bountyId?:string;role?:'scout'|'raider'|'captain';encounter?:string;id:string;name:string;position:Vec3;yaw:number;home:Vec3;health:number;maxHealth:number;stamina:number;equipped:ItemId;phase:'patrol'|'alert'|'approach'|'circle'|'windup'|'recover'|'return'|'stagger'|'dead';decisionAt:number;targetId?:string;rewarded:boolean;combat?:CombatState}
export interface ForageState {kind?:'fiber'|'berries'|'mushroom'|'herb'|'wood'|'wild_honey';readyAt?:number;id:string;position:Vec3;harvested:boolean}
export interface WorldState {worldSeed?:number;frontier?:Frontier;bountySites?:Record<string,BountySite>;animals?:Record<string,AnimalState>;expeditionSites?:Record<string,ExpeditionSite>;version:1;tick:number;players:Record<string,PlayerState>;resources:Record<string,ResourceState>;forage:Record<string,ForageState>;drops:Record<string,DropState>;structures:Record<string,StructureState>;stations:Record<string,StationState>;containers:Record<string,ContainerState>;enemies:Record<string,EnemyState>;opened:string[];progress:string[];nextId:number}
export const ITEMS:Record<ItemId,{name:string;symbol:string;description:string;stack:number}>={
 mushroom:{name:'Woodland mushrooms',symbol:'♧',description:'Cook these chestnut mushrooms in a woodland broth.',stack:30},herb:{name:'Wild herbs',symbol:'❧',description:'Aromatic greens for restorative broth.',stack:30},woodland_broth:{name:'Woodland broth',symbol:'◉',description:'+40 stamina for eight minutes. Cooked from gathered mushrooms and herbs.',stack:20},
 axe:{name:'Iron axe',symbol:'⚒',description:'A well-balanced tool for felling mature timber.',stack:1},pickaxe:{name:'Mining pick',symbol:'⛏',description:'Break stone and uncover iron ore.',stack:1},hammer:{name:'Builder’s hammer',symbol:'⚒',description:'Raise a home from the wilderness.',stack:1},sword:{name:'Marcher’s sword',symbol:'⚔',description:'Forged iron. 24 damage. Hold right mouse to guard.',stack:1},fine_sword:{name:'Tempered sword',symbol:'⚔',description:'Fine quality. 34 damage. Hardened steel and an iron guard.',stack:1},bow:{name:'Hunter’s bow',symbol:'➶',description:'32 damage at range. Press 5 to equip; right mouse steadies your aim.',stack:1},wood:{name:'Oak timber',symbol:'▰',description:'Seasoned wood for construction and crafting.',stack:99},stone:{name:'Fieldstone',symbol:'◆',description:'Strong foundations begin with good stone.',stack:99},iron:{name:'Iron ore',symbol:'✦',description:'Iron-bearing stone, ready for the forge.',stack:99},fiber:{name:'Wild flax',symbol:'❧',description:'Long fibers for cord and cloth.',stack:99},venison:{name:'Raw venison',symbol:'◒',description:'Cook over a campfire before eating.',stack:20},berries:{name:'Wild berries',symbol:'●',description:'A small restorative meal.',stack:20},grilled_venison:{name:'Grilled venison',symbol:'◒',description:'+35 maximum health for 8 minutes.',stack:20},hearty_stew:{name:'Marcher’s stew',symbol:'◉',description:'+25 health and stamina for 8 minutes.',stack:20},hide:{name:'Cured hide',symbol:'▱',description:'Supple leather for equipment.',stack:99},
 crow_crop:{name:'Crow crop',symbol:'◈',description:'A tough little crop sac from a crow. Someone in Alderbrook insists this can be rendered into milk.',stack:20},crow_milk:{name:'Crow milk',symbol:'◌',description:'A suspicious frontier tonic. +15 maximum health and +25 stamina for six minutes.',stack:20},wild_honey:{name:'Wild honey',symbol:'⬡',description:'Dark woodland honey gathered from a wild skep. Restores 15 health.',stack:20}};
export function seedState():WorldState {return {version:1,tick:0,nextId:1,players:{},resources:{},forage:{},drops:{},structures:{},stations:Object.fromEntries(STATIC_STATIONS.map(s=>[s.id,structuredClone(s)])),containers:{},enemies:{},opened:[],progress:[]};}
export function makePlayer(archetype:Archetype):PlayerState{return {id:'player-local',name:'The Wanderer',archetype,position:[0,5,18],yaw:Math.PI,health:100,stamina:100,inventory:[{id:'starter-axe',item:'axe',count:1,quality:1},{id:'starter-pick',item:'pickaxe',count:1,quality:1},{id:'starter-hammer',item:'hammer',count:1,quality:1},{id:'starter-bow',item:'bow',count:1,quality:1},{id:'starter-food',item:'venison',count:2,quality:1},{id:'starter-berries',item:'berries',count:3,quality:1}],equipped:'axe',hair:'#493120',skin:'#ffffff',hood:false,skills:{},buffs:[]};}
export function quantity(p:PlayerState,item:string){return p.inventory.filter(s=>s.item===item).reduce((n,s)=>n+s.count,0);}
export function canAfford(p:PlayerState,cost:Record<string,number>){return Object.entries(cost).every(([k,v])=>quantity(p,k)>=v);}
export function addItem(state:WorldState,p:PlayerState,item:ItemId,count:number){for(const s of p.inventory){if(s.item===item&&s.count<ITEMS[item].stack){const n=Math.min(count,ITEMS[item].stack-s.count);s.count+=n;count-=n;}}while(count>0){const n=Math.min(count,ITEMS[item].stack);p.inventory.push({id:'item-'+state.nextId++,item,count:n,quality:1});count-=n;}}
export function spend(p:PlayerState,cost:Record<string,number>){if(!canAfford(p,cost))return false;for(const [key,total] of Object.entries(cost)){let n=total;for(const s of p.inventory)if(s.item===key){const take=Math.min(n,s.count);s.count-=take;n-=take;}}p.inventory=p.inventory.filter(s=>s.count>0);return true;}
export function saveWorld(s:WorldState){localStorage.setItem('alderwatch.realm.v1',JSON.stringify(s));}
export function loadWorld():WorldState|null{try{const s=JSON.parse(localStorage.getItem('alderwatch.realm.v1')||'null') as WorldState|null;if(s?.version!==1||!s.players||!s.resources)return null;s.stations??=seedState().stations;s.containers??={};s.forage??={};s.enemies??={};s.progress??=[];s.nextId??=1;if(!s.progress.includes('release-bow-v1')){for(const p of Object.values(s.players))if(!p.inventory.some(stack=>stack.item==='bow'))p.inventory.push({id:'release-bow-'+s.nextId++,item:'bow',count:1,quality:1});s.progress.push('release-bow-v1');}if(!s.progress.includes('skills-use-v2')){for(const p of Object.values(s.players))migrateLegacySkills(p);s.progress.push('skills-use-v2');}else for(const p of Object.values(s.players))migrateLegacySkills(p);return s;}catch{return null;}}
export function tickVitals(state:WorldState,dt:number){for(const p of Object.values(state.players)){for(const b of p.buffs)b.remaining-=dt;p.buffs=p.buffs.filter(b=>b.remaining>0);const max=stats(p);if(p.health>0)p.health=Math.min(max.health,p.health+(p.buffs.length?dt*.65:0));p.stamina=Math.min(max.stamina,p.stamina);}}

// Presentation submits commands to an authority, never mutates inventory or resource ownership.
export type Command={type:'track_frontier';playerId:string;siteId:string}|{type:'bounty';playerId:string;action:'accept'|'claim';bountyId:string}|{type:'expedition';playerId:string;action:'accept'|'recover'|'report';siteId?:string}|{type:'equip';playerId:string;item:ItemId|null}|{type:'pickup';playerId:string;dropId:string}|{type:'harvest';playerId:string;resourceId:string}|{type:'forage';playerId:string;forageId:string}|{type:'combat_action';playerId:string;action:'attack'|'heavy'|'dodge'}|{type:'strike';playerId:string;enemyId?:string}|{type:'respawn';playerId:string}|EconomyCommand;
export interface Authority {state:WorldState;dispatch(command:Command):{ok:boolean;message:string}}
export class LocalAuthority implements Authority{
 lineOfSight?:(attacker:Fighter,target:Fighter)=>boolean;
 constructor(public state=seedState()){}
 dispatch(c:Command){const p=this.state.players[c.playerId];if(!p)return {ok:false,message:'Unknown survivor'};
  if(c.type==='respawn')return respawn(this.state,p);
  if(p.health<=0)return {ok:false,message:'Return to the March before acting'};
  if(c.type==='track_frontier')return trackFrontier(this.state,p,c.siteId);
  if(c.type==='bounty')return bountyCommand(this.state,p,c.action,c.bountyId);
  if(c.type==='expedition')return expeditionCommand(this.state,p,c.action,c.siteId);
  if(c.type==='combat_action')return beginAction(p,this.state.tick,c.action);
  if(c.type==='strike'){const e=c.enemyId?this.state.enemies[c.enemyId]:undefined;return resolveStrike(this.state,p,e,e?this.lineOfSight?.(p,e)??true:true);}
  if(c.type==='equip'){if(actionBusy(p,this.state.tick))return {ok:false,message:'Finish your action before changing equipment'};if(c.item&&(!['axe','pickaxe','hammer','sword','fine_sword','bow'].includes(c.item)||!quantity(p,c.item)))return {ok:false,message:'You do not own an equippable weapon or tool of that kind'};p.equipped=c.item;return {ok:true,message:c.item?ITEMS[c.item].name:'Empty hands'};}
  if(c.type==='forage'){const f=this.state.forage[c.forageId];if(!f||(f.harvested&&(f.readyAt??Infinity)>this.state.tick)||Math.hypot(f.position[0]-p.position[0],f.position[2]-p.position[2])>2.2)return {ok:false,message:'Move closer to ripe forage'};const item=f.kind??'fiber',count=item==='fiber'?4:item==='berries'?3:item==='wild_honey'?1:2;f.harvested=true;f.readyAt=item==='fiber'?undefined:this.state.tick+60*(item==='wild_honey'?600:300);addItem(this.state,p,item,count);return {ok:true,message:item==='wild_honey'?'Gathered wild honey':`Gathered ${count} ${ITEMS[item].name}`};}
  if(c.type==='pickup'){const d=this.state.drops[c.dropId];if(!d||Math.hypot(d.position[0]-p.position[0],d.position[2]-p.position[2])>2.5)return {ok:false,message:'Move closer'};addItem(this.state,p,d.item,d.count);delete this.state.drops[d.id];return {ok:true,message:`${d.count} × ${ITEMS[d.item].name}`};}
  if(c.type==='harvest'){const r=this.state.resources[c.resourceId];if(!r||r.phase!=='standing'||r.health<=0)return {ok:false,message:'Nothing left to harvest here'};if(Math.hypot(r.position[0]-p.position[0],r.position[2]-p.position[2])>2.35)return {ok:false,message:'Move closer to make contact'};if(p.equipped!==(r.kind==='tree'?'axe':'pickaxe'))return {ok:false,message:'Equip your '+(r.kind==='tree'?'axe':'mining pick')};r.health--;if(r.health===0){r.phase=r.kind==='tree'?'falling':'fallen';if(!this.state.progress.includes('harvest-'+r.kind))this.state.progress.push('harvest-'+r.kind);}return {ok:true,message:r.health?`${r.kind==='tree'?'Oak':'Stone'} · ${r.health} hits remaining`:r.kind==='tree'?'Timber! Stand clear.':'Stone fractured — collect the pieces'};}
  return applyEconomyCommand(this,p,c);
 }
}
