import * as T from 'three';
import RAPIER from '@dimforge/rapier3d-compat';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {Assets} from './assets';
import {Character} from './character';
import {Input} from './input';
import {LocalAuthority,loadWorld,saveWorld,tickVitals,type Vec3} from './state';
import {stats} from './definitions';
import {ACTION_CAMERA} from './follow-camera';
import {CellWindow,type CellCoord} from './area-cell-stream';
import {cellId,worldRandom} from './world-address';
import {CROWNROAD_VALE,rememberCurrentArea,requestAreaTravel,WOLFPINE} from './realm-save';
import {AreaGameplayShell,type AreaMapLandmark} from './area-gameplay-shell';
import {createStreamedAreaFarField} from './streamed-area-far-field';
import {StreamedAreaSurfaceSet} from './streamed-area-surface';
import {CHARCOAL_CAMP_PLAN} from './charcoal-camp-plan';
import {settlementClearanceAt} from './settlement-compiler';
import {renderSettlementCell} from './settlement-runtime';
import {WOLFPINE_ACTIVE_RADIUS,WOLFPINE_AREA,WOLFPINE_CELL,WOLFPINE_HALF,WOLFPINE_MOOD,WOLFPINE_POIS,wolfpineCellInBounds,wolfpineLocationName} from './wolfpine-world';
import './style.css';import './loading-experience.css';import './realm-travel.css';

const SUN_OFFSET=new T.Vector3(-46,76,38),westGate=new T.Vector3(-246,0,0),charcoalCamp=new T.Vector3(0,0,-48),bentSpear=new T.Vector3(96,0,48),northRoad=new T.Vector3(0,0,246);
const app=document.querySelector<HTMLDivElement>('#app')!;app.innerHTML='<div id="loading"><div class="sigil">A</div><h1>WOLFPINE</h1><p id="load-status">Following the King’s road beneath the dark timber…</p><div class="load-line"></div></div><div id="ui"></div>';
const ui=document.querySelector<HTMLDivElement>('#ui')!,renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.98;renderer.domElement.id='world';app.prepend(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#80939a');scene.fog=new T.FogExp2('#899a96',.0057);const camera=new T.PerspectiveCamera(ACTION_CAMERA.fov,innerWidth/innerHeight,.08,680),pmrem=new T.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;scene.environmentIntensity=.22;pmrem.dispose();scene.add(new T.HemisphereLight('#cbdad8','#394036',.82));const sun=new T.DirectionalLight('#f4d9ad',2.7);sun.position.copy(SUN_OFFSET);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-44,right:44,top:44,bottom:-44,near:1,far:175});sun.shadow.camera.updateProjectionMatrix();scene.add(sun,sun.target);
const worldRoot=new T.Group();scene.add(worldRoot);const assets=new Assets(),input=new Input(renderer.domElement),saved=loadWorld();if(!saved)throw new Error('Wolfpine requires an existing Alderwatch realm');const authority=new LocalAuthority(saved),player=Object.values(authority.state.players)[0];if(!player)throw new Error('Wolfpine requires a survivor');player.areaId=WOLFPINE;
let physics:RAPIER.World,character:Character,stream:CellWindow<WolfpineCell>,shell:AreaGameplayShell,surfaces:StreamedAreaSurfaceSet;let yaw=player.yaw,pitch=ACTION_CAMERA.pitch,distance=ACTION_CAMERA.distance,last=0,acc=0,autosave=0,frames=0,fps=0,fpsClock=0,notice='',noticeUntil=0;
const forestMaterials=new Map<T.Material,T.Material>();
interface WolfpineCell{group:T.Group;ownedGeometries:T.BufferGeometry[];colliders:RAPIER.Collider[]}
function addr(coord:CellCoord,slot:number,tag:string){return{realmSeed:authority.state.worldSeed??197709,areaId:WOLFPINE_AREA,cellX:coord.x,cellZ:coord.z,slot,tag};}
function authored(name:string,parent:T.Group,x:number,z:number,yaw=0,scale=1){const source=assets.medieval[name];if(!source)return;const o=source.clone(true);o.position.set(x,0,z);o.rotation.y=yaw;o.scale.setScalar(scale);parent.add(o);return o;}
function obstacle(cell:WolfpineCell,x:number,z:number,hx:number,hz:number,hy=2){cell.colliders.push(physics.createCollider(RAPIER.ColliderDesc.cuboid(hx,hy,hz).setTranslation(x,hy,z)));}
function plane(cell:WolfpineCell,parent:T.Group,w:number,h:number,material:T.Material,y=0){const geometry=new T.PlaneGeometry(w,h);cell.ownedGeometries.push(geometry);const mesh=new T.Mesh(geometry,material);mesh.rotation.x=-Math.PI/2;mesh.position.y=y;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
function darkForestMaterial(source:T.Material){const cached=forestMaterials.get(source);if(cached)return cached;const material=source.clone();if(material instanceof T.MeshStandardMaterial){const name=material.name.toLowerCase();if(/leaf|foliage/.test(name))material.color.multiply(new T.Color('#536c55'));else if(/bark|wood/.test(name))material.color.multiply(new T.Color('#6e675a'));material.roughness=Math.max(.92,material.roughness??.8);material.metalness=0;}forestMaterials.set(source,material);return material;}
const TREE_GRID=[[-18,-18],[-6,-18],[6,-18],[18,-18],[-18,-6],[-6,-6],[6,-6],[18,-6],[-18,6],[-6,6],[6,6],[18,6],[-18,18],[-6,18],[6,18],[18,18]] as const;
function roadClear(wx:number,wz:number){return Math.abs(wz)<7||(Math.abs(wx)<5&&wz>-110)||(Math.abs(wz-48)<5&&wx>-5&&wx<108)||(Math.abs(wx-96)<5&&wz>-5&&wz<55);}
function siteClear(wx:number,wz:number){return settlementClearanceAt(CHARCOAL_CAMP_PLAN,wx,wz,2.8)||Math.hypot(wx-bentSpear.x,wz-bentSpear.z)<25||Math.hypot(wx-westGate.x,wz-westGate.z)<17||Math.hypot(wx-northRoad.x,wz-northRoad.z)<14;}
function forestBatch(coord:CellCoord,group:T.Group,cell:WolfpineCell){const placements:{x:number;z:number;scale:number;yaw:number}[]=[];let slot=0;for(const [bx,bz] of TREE_GRID){const x=bx+(worldRandom(addr(coord,100+slot,'tree-jx'))-.5)*3.2,z=bz+(worldRandom(addr(coord,100+slot,'tree-jz'))-.5)*3.2,wx=coord.x*WOLFPINE_CELL+x,wz=coord.z*WOLFPINE_CELL+z,keep=worldRandom(addr(coord,100+slot,'tree-keep'));slot++;if(roadClear(wx,wz)||siteClear(wx,wz)||keep<.14)continue;placements.push({x,z,scale:.76+worldRandom(addr(coord,200+slot,'tree-scale'))*.46,yaw:worldRandom(addr(coord,300+slot,'tree-yaw'))*Math.PI*2});}if(!placements.length)return;const source=assets.prop('oak_distant');source.updateMatrixWorld(true);const dummy=new T.Object3D();source.traverse(o=>{if(!(o instanceof T.Mesh))return;const material=Array.isArray(o.material)?o.material.map(darkForestMaterial):darkForestMaterial(o.material),mesh=new T.InstancedMesh(o.geometry,material,placements.length);for(let i=0;i<placements.length;i++){const p=placements[i];dummy.position.set(p.x,0,p.z);dummy.rotation.set(0,p.yaw,0);dummy.scale.setScalar(p.scale);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix.clone().multiply(o.matrixWorld));}mesh.instanceMatrix.needsUpdate=true;mesh.name='wolfpine-forest-batch';mesh.castShadow=false;mesh.receiveShadow=false;mesh.computeBoundingSphere();group.add(mesh);});for(const p of placements)cell.colliders.push(physics.createCollider(RAPIER.ColliderDesc.cylinder(1.7,.28).setTranslation(coord.x*WOLFPINE_CELL+p.x,1.7,coord.z*WOLFPINE_CELL+p.z)));}
function resolveSettlementAsset(name:string){if(name==='camp-shelter')return assets.authoredCampShelter();return assets.medieval[name];}
function buildSite(coord:CellCoord,group:T.Group,cell:WolfpineCell){const gx=coord.x*WOLFPINE_CELL,gz=coord.z*WOLFPINE_CELL;renderSettlementCell({plan:CHARCOAL_CAMP_PLAN,coord,cellSize:WOLFPINE_CELL,group,physics,surfaces,resolveAsset:resolveSettlementAsset,colliders:cell.colliders});if(coord.x===-5&&coord.z===0){const gate=assets.authoredFortification();gate.position.set(-13,0,0);gate.rotation.y=Math.PI/2;gate.scale.setScalar(1.55);group.add(gate);authored('watchtower',group,-7,11,.08,.84);authored('fence_wood_ext1',group,-10,-9,.2,.88);obstacle(cell,gx-7,gz+11,1.7,1.7,3);}if(coord.x===2&&coord.z===1){authored('barracks',group,-7,-5,.1,.82);authored('watchtower',group,12,9,-.15,.9);authored('storage',group,9,-10,.25,.78);for(const [x,z,yaw] of [[-14,-14,0],[0,-14,0],[14,-14,0],[-14,14,Math.PI],[0,14,Math.PI],[14,14,Math.PI]] as const){const fort=assets.authoredFortification();fort.position.set(x,0,z);fort.rotation.y=yaw;fort.scale.setScalar(1.2);group.add(fort);}authored('fence_wood_ext1',group,-16,0,Math.PI/2,.95);authored('fence_wood_ext1',group,16,0,-Math.PI/2,.95);obstacle(cell,gx-7,gz-5,3.3,3);obstacle(cell,gx+12,gz+9,1.7,1.7,3);obstacle(cell,gx+9,gz-10,2.8,2.8);}if(coord.x===0&&coord.z===5){authored('watchtower',group,-10,-3,.1,.82);authored('fence_wood_ext1',group,0,12,0,.9);obstacle(cell,gx-10,gz-3,1.6,1.6,3);}}
function buildCell(coord:CellCoord):WolfpineCell{const group=new T.Group();group.name='wolfpine-cell-'+cellId(WOLFPINE_AREA,coord.x,coord.z);group.position.set(coord.x*WOLFPINE_CELL,0,coord.z*WOLFPINE_CELL);worldRoot.add(group);const cell:WolfpineCell={group,ownedGeometries:[],colliders:[]};if(!wolfpineCellInBounds(coord))return cell;plane(cell,group,WOLFPINE_CELL+.3,WOLFPINE_CELL+.3,surfaces.ground);if(coord.z===0)plane(cell,group,WOLFPINE_CELL+.5,6.5,surfaces.road,.018);if(coord.x===0&&coord.z>=-2&&coord.z<=5)plane(cell,group,4.5,WOLFPINE_CELL+.5,surfaces.road,.019);if(coord.z===1&&coord.x>=0&&coord.x<=2)plane(cell,group,WOLFPINE_CELL+.5,4.5,surfaces.road,.02);if(coord.x===2&&coord.z>=0&&coord.z<=1)plane(cell,group,4.5,WOLFPINE_CELL+.5,surfaces.road,.021);forestBatch(coord,group,cell);buildSite(coord,group,cell);return cell;}
function disposeCell(handle:{value:WolfpineCell}){for(const collider of handle.value.colliders)physics.removeCollider(collider,true);for(const geometry of handle.value.ownedGeometries)geometry.dispose();handle.value.group.removeFromParent();}
function buildWolfpine(){physics=new RAPIER.World({x:0,y:-9.81,z:0});physics.createCollider(RAPIER.ColliderDesc.cuboid(WOLFPINE_HALF,.12,WOLFPINE_HALF).setTranslation(0,-.12,0));for(const [x,z,hx,hz] of [[-WOLFPINE_HALF,0,.35,WOLFPINE_HALF],[WOLFPINE_HALF,0,.35,WOLFPINE_HALF],[0,-WOLFPINE_HALF,WOLFPINE_HALF,.35],[0,WOLFPINE_HALF,WOLFPINE_HALF,.35]] as const)physics.createCollider(RAPIER.ColliderDesc.cuboid(hx,3,hz).setTranslation(x,3,z));surfaces=new StreamedAreaSurfaceSet(assets,{ground:'#748064',road:'#85755f',groundRepeat:9,roadRepeat:11});worldRoot.add(createStreamedAreaFarField({width:WOLFPINE_HALF*2,depth:WOLFPINE_HALF*2,groundTexture:assets.textures['field-color']??assets.textures.meadow,roadTexture:assets.textures.soil,groundColor:'#6c765e',roads:[{width:6.5,length:WOLFPINE_HALF*2,yaw:Math.PI/2,name:'far-kings-pine-road'},{x:0,z:72,width:4.5,length:WOLFPINE_HALF,name:'far-north-ridge-road'},{x:0,z:-48,width:4.5,length:96,name:'far-charcoal-track'},{x:48,z:48,width:4.5,length:96,yaw:Math.PI/2,name:'far-bent-spear-track'},{x:96,z:24,width:4.5,length:48,name:'far-bent-spear-link'}]}));stream=new CellWindow({cellSize:WOLFPINE_CELL,radius:WOLFPINE_ACTIVE_RADIUS,create:buildCell,dispose:disposeCell});character=new Character(assets,physics,player,worldRoot);character.getTick=()=>authority.state.tick;character.onActionRequest=action=>authority.dispatch({type:'combat_action',playerId:player.id,action}).ok;character.onImpact=()=>{};stream.update(player.position[0],player.position[2]);input.active=true;input.captureCamera=true;}
function snapshot(){player.position=character.root.position.toArray() as Vec3;player.yaw=character.root.rotation.y;rememberCurrentArea(player);}function save(){snapshot();saveWorld(authority.state);}function transition(title:string,status:string){const el=document.createElement('div');el.className='realm-transition-loader';el.innerHTML='<div class="realm-loader-card"><div class="sigil"><span>A</span></div><small>WOLFPINE</small><h2></h2><div class="realm-loader-status"></div><div class="realm-loader-track"><i></i></div></div>';el.querySelector('h2')!.textContent=title;el.querySelector<HTMLElement>('.realm-loader-status')!.textContent=status;document.body.append(el);}function travelCrownroad(){save();requestAreaTravel(CROWNROAD_VALE);input.active=false;transition('RETURNING TO CROWNROAD','The pines thin and Greyhaven’s road opens west…');requestAnimationFrame(()=>requestAnimationFrame(()=>location.reload()));}function notify(message:string){notice=message;noticeUntil=performance.now()+6500;}
function discover(now:number){const p=character.root.position;for(const poi of WOLFPINE_POIS){const x=poi.cell.x*WOLFPINE_CELL,z=poi.cell.z*WOLFPINE_CELL,flag='wolfpine-poi:'+poi.id;if(authority.state.progress.includes(flag)||Math.hypot(p.x-x,p.z-z)>22)continue;authority.state.progress.push(flag);notice=`DISCOVERED · ${poi.name}`;noticeUntil=now+6000;saveWorld(authority.state);}}
function interact(now:number){const p=character.root.position;if(p.distanceTo(westGate)<6){travelCrownroad();return;}if(p.distanceTo(charcoalCamp)<8){player.stamina=stats(player).stamina;notice='Wolfpine Charcoal Camp · fire, water and a moment off the road · stamina restored';noticeUntil=now+6500;save();return;}if(p.distanceTo(bentSpear)<9){if(!authority.state.progress.includes('wolfpine-bent-spear-inspected'))authority.state.progress.push('wolfpine-bent-spear-inspected');notice='The Bent Spear Stockade · palisade occupied, wolf tracks crossing the north trail';noticeUntil=now+7000;save();return;}if(p.distanceTo(northRoad)<7){notice='North Ridge Road · the upland routes toward Stonewake and Giant’s Step are not open yet';noticeUntil=now+7000;}}
function hud(){ui.innerHTML='<div class="compass">N · WOLFPINE</div><div class="location"><small>THE OUTER ROAD</small><span>King’s West Gate</span></div><div class="quest"><small>WOLFPINE</small><p>Find the charcoal camp. The Bent Spear Stockade controls the trail beyond.</p></div><div class="vitals"><div class="health"><i></i><span></span></div><div class="stamina"><i></i></div></div><div class="interaction" hidden></div><div class="controls">WASD Move · Shift Sprint · Space Dodge · Mouse Look · E roads / sites</div><output id="performance"></output><aside id="ironward-state"></aside>';}
function updateHud(now:number){const max=stats(player),health=ui.querySelector<HTMLElement>('.health i'),stamina=ui.querySelector<HTMLElement>('.stamina i'),label=ui.querySelector<HTMLElement>('.health span')!;if(health)health.style.width=player.health/max.health*100+'%';if(stamina)stamina.style.width=player.stamina/max.stamina*100+'%';label.textContent=Math.ceil(player.health)+' / '+max.health;const p=character.root.position,west=p.distanceTo(westGate),camp=p.distanceTo(charcoalCamp),stockade=p.distanceTo(bentSpear),north=p.distanceTo(northRoad),prompt=ui.querySelector<HTMLElement>('.interaction')!;let text='';if(west<6)text='E · Return through King’s West Gate to Crownroad Vale';else if(camp<8)text='E · Rest at Wolfpine Charcoal Camp';else if(stockade<9)text='E · Inspect the Bent Spear Stockade';else if(north<7)text='E · Read the North Ridge road';prompt.hidden=!text;prompt.textContent=text;if(input.take('KeyE')&&!shell.blocked)interact(now);ui.querySelector<HTMLElement>('.location span')!.textContent=wolfpineLocationName(p.x,p.z);const gfx=(globalThis as any).__alderwatchStreamedGraphics;ui.querySelector<HTMLElement>('#ironward-state')!.textContent=`WOLFPINE · ${stream.active.size}/${stream.maxActive} CORE · ${stream.residentSize}/${stream.maxResident} RESIDENT · 121 ADDRESSABLE CELLS · GFX Q${Number(gfx?.quality??1).toFixed(2)}`;ui.querySelector<HTMLElement>('#performance')!.textContent=`${fps} FPS · ${renderer.info.render.calls} draws`;ui.querySelector<HTMLElement>('.quest p')!.textContent=now<noticeUntil?notice:`${WOLFPINE_MOOD}. The King’s road remains visible beneath the streamed forest.`;}
function mapLandmarks():AreaMapLandmark[]{return WOLFPINE_POIS.map(p=>({label:p.name,position:[p.cell.x*WOLFPINE_CELL,0,p.cell.z*WOLFPINE_CELL] as Vec3,kind:p.kind==='gate'?'gate':p.kind==='camp'?'danger':'site'}));}
function frame(now:number){const frameDt=last?(now-last)/1000:.016,dt=Math.min(frameDt,.05);last=now;frames++;fpsClock+=frameDt;if(fpsClock>1){fps=Math.round(frames/fpsClock);frames=0;fpsClock=0;}shell.update();yaw+=input.dx*.003;pitch=T.MathUtils.clamp(pitch+input.dy*.002,ACTION_CAMERA.minPitch,ACTION_CAMERA.maxPitch);distance=T.MathUtils.clamp(distance+input.wheel*.85,ACTION_CAMERA.minDistance,ACTION_CAMERA.maxDistance);acc+=dt;while(acc>=1/60){character.preStep(1/60,input,yaw,!shell.blocked);physics.step();character.postStep(1/60);tickVitals(authority.state,1/60);authority.state.tick++;acc-=1/60;}stream.update(character.root.position.x,character.root.position.z);if(!shell.blocked){discover(now);updateHud(now);}autosave+=dt;if(autosave>10){save();autosave=0;}const p=character.root.position,aim=p.clone().add(new T.Vector3(0,1.25,0));camera.position.copy(p).add(new T.Vector3(-Math.sin(yaw)*Math.cos(pitch)*distance,1.35+Math.sin(pitch)*distance,Math.cos(yaw)*Math.cos(pitch)*distance));const rayDir=camera.position.clone().sub(aim),rayLength=rayDir.length();rayDir.normalize();const hit=physics.castRay(new RAPIER.Ray(aim,rayDir),rayLength,true,undefined,undefined,character.collider,character.body);if(hit&&hit.timeOfImpact<rayLength)camera.position.copy(aim).addScaledVector(rayDir,Math.max(.7,hit.timeOfImpact-.25));camera.lookAt(aim);sun.position.copy(p).add(SUN_OFFSET);sun.target.position.copy(p);sun.target.updateMatrixWorld();renderer.render(scene,camera);input.endFrame();requestAnimationFrame(frame);}
async function init(){await RAPIER.init();await assets.load(message=>document.querySelector('#load-status')!.textContent=message);if(!authority.state.progress.includes('entered-wolfpine')){authority.state.progress.push('entered-wolfpine');notice='WOLFPINE DISCOVERED · the King’s East Gate now opens into the outer realm';noticeUntil=performance.now()+8500;}buildWolfpine();hud();shell=new AreaGameplayShell({areaId:WOLFPINE,areaName:'Wolfpine',ui,authority,input,player:()=>player,bounds:{minX:-WOLFPINE_HALF,maxX:WOLFPINE_HALF,minZ:-WOLFPINE_HALF,maxZ:WOLFPINE_HALF},landmarks:mapLandmarks,renderHud:hud,save,equipVisual:item=>character.equip(item),notify});shell.mountHud();document.querySelector('#loading')!.remove();saveWorld(authority.state);requestAnimationFrame(frame);}
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});window.addEventListener('pagehide',()=>{if(character)save();stream?.dispose();surfaces?.dispose();for(const material of forestMaterials.values())material.dispose();});init().catch(error=>{console.error(error);document.querySelector('#load-status')!.textContent='Wolfpine could not load: '+(error instanceof Error?error.message:String(error));});
